### ISSUE TITLE
Make logging more "pay-for-play" by avoiding unnecessary allocations

### ISSUE THREAD

**Issue by justinvp** [aspnet/Logging#100]
Note: I'd be happy to submit a PR; I just wanted to first see if the owners are open to these suggestions.

There are opportunities to make logging more "pay-for-play," avoiding unnecessary allocations when possible.

For example, here's the current implementation of the `WriteVerbose` extension method:

```c#
public static void WriteVerbose([NotNull] this ILogger logger, string format, params object[] args)
{
    logger.Write(LogLevel.Verbose, 0,
        string.Format(CultureInfo.InvariantCulture, format, args), null, TheMessage);
}
```

With the current implementation, even when `LogLevel.Verbose` is disabled, this still results in allocations due to the call to `string.Format`.

A caller could workaround this by calling `IsEnabled(LogLevel.Verbose)` before calling `WriteVerbose`, but why not include the `IsEnabled` check inside the extension method itself?

For example:

```c#
public static void WriteVerbose([NotNull] this ILogger logger, string format, params object[] args)
{
    if (logger.IsEnabled(LogLevel.Verbose))
    {
        logger.Write(LogLevel.Verbose, 0,
            string.Format(CultureInfo.InvariantCulture, format, args), null, TheMessage);
    }
}
```

With the change above, the user doesn't have to know about or remember to check `IsEnabled`. The user simply calls `WriteVerbose` and gets the perf benefit without having to write any other code!

Next, consider the following usage where `streamIndex` and `count` are `int` and `id` is `ulong`.

```c#
_logger.WriteVerbose("OnReceived({0}, {1}, {2})", streamIndex, count, id);
```

This call will result in several allocations: the `params object[] args` array is allocated and the value types are boxed. It'd be nice if some additional extension method overloads were added to avoid these allocations when the `LogLevel` is disabled.

For example, the following generic overloads avoid the params array allocation and avoid boxing when the `LogLevel` is disabled:

```c#
public static void WriteVerbose<T>([NotNull] this ILogger logger, string format, T arg)
{
    if (logger.IsEnabled(LogLevel.Verbose))
    {
        logger.Write(LogLevel.Verbose, 0,
            string.Format(CultureInfo.InvariantCulture, format, new object[] { arg }), null, TheMessage);
    }
}

public static void WriteVerbose<T1, T2>([NotNull] this ILogger logger, string format, T1 arg1, T2 arg2)
{
    if (logger.IsEnabled(LogLevel.Verbose))
    {
        logger.Write(LogLevel.Verbose, 0,
            string.Format(CultureInfo.InvariantCulture, format, new object[] { arg1, arg2 }), null, TheMessage);
    }
}

public static void WriteVerbose<T1, T2, T3>([NotNull] this ILogger logger, string format, T1 arg1, T2 arg2, T3 arg3)
{
    if (logger.IsEnabled(LogLevel.Verbose))
    {
        logger.Write(LogLevel.Verbose, 0,
            string.Format(CultureInfo.InvariantCulture, format, new object[] { arg1, arg2, arg3 }), null, TheMessage);
    }
}
```

This is consistent with what other logging libraries do to make logging "pay-for-play" (e.g. [see NLog](https://github.com/NLog/NLog/blob/00d53bc3b234917517e2fdc1735f8b4af2d5d8aa/src/NLog/Logger.cs#L860-L866))

Looking through the aspnet repositories, there are many places in the codebase that could benefit from these suggestions.

**Comment by Eilon** [comment]
I suspect that for someone more perf-conscious they would already be checking `IsEnabled` before calling the logger at all because even with the pattern you propose there are likely a lot of other allocations going on, such as preparing data parameters to pass into logging.

And with the proposed pattern, there would now be *two* calls to `IsEnabled`, thus reducing performance for the people who care about it most.

**Comment by justinvp** [comment]
> And with the proposed pattern, there would now be two calls to IsEnabled, thus reducing performance for the people who care about it most.

Someone more perf-conscious who is already checking `IsEnabled` already has *two* calls to `IsEnabled` happening, just look at the current implementations of `Write` (they all call `IsEnabled`):

 - [NLog](https://github.com/NLog/NLog/blob/00d53bc3b234917517e2fdc1735f8b4af2d5d8aa/src/NLog/Logger.cs#L157)
 - [Serilog](https://github.com/aspnet/Logging/blob/9899629df27168151a4e977534f2befba7134690/src/Microsoft.Framework.Logging.Serilog/SerilogLogger.cs#L42)
 - [Console](https://github.com/aspnet/Logging/blob/9899629df27168151a4e977534f2befba7134690/src/Microsoft.Framework.Logging.Console/ConsoleLogger.cs#L29)

I'd argue that it's worth making the common scenarios (the helper extensions) as performant as possible by default. Pit of success.

**Comment by Eilon** [comment]
Ah, interesting, I hadn't noticed that there are already two calls. However I'm not sure that making the 2 into 3 makes things better.

In all reality, is the one extra allocation of an array worse than an extra method call to delegates? I'd have to say that without seeing real numbers on this I have to hesitate on such a change. This is the type of perf work where using intuition instead of numbers can lead to some potentially bad changes.

So, I think this is an interesting area to investigate: it's certainly a goal for logging to add only minimal overhead to a running application, and if hotspots in the codebase are identified then those should be tackled and addressed.

**Comment by justinvp** [comment]
> In all reality, is the one extra allocation of an array worse than an extra method call to delegates?

It's more than one extra allocation. Consider a call to the following:

```c#
_logger.WriteVerbose("OnReceived({0}, {1}, {2})", streamIndex, count, id);
```

With the current API and implementation, this is at least 5 unnecessary allocations when the Verbose level isn't enabled:

 1. `streamIndex` (`int`) is boxed to an `object`
 2. `count` (`int`) is boxed to an `object`
 3. `id` (`ulong`) is boxed to an `object`
 2. the `object[]` params array is allocated
 3. the call to `string.Format` allocates a new `string` (and the implementation of `string.Format` takes time to parse the format string, and may have additional allocations inside its implementation).

**Comment by justinvp** [comment]
I modified the sample app to measure the performance difference between the existing implementation vs. the proposed improvements. The results show a decent improvement.

Below are the results of a few test runs when Verbose isn't enabled. `A` is the elapsed time of the existing implementation, `B` is the elapsed time of the proposed changes.

```
A: 00:00:00.8806144
B: 00:00:00.1702717
A/B     : 5.17181892234587
B/A     : 0.193355570837815
(A-B)/A : 0.806644429162185
(B-A)/B : 4.17181892234587
 
 
A: 00:00:01.0186282
B: 00:00:00.1662137
A/B     : 6.1284250335562
B/A     : 0.163174060957668
(A-B)/A : 0.836825939042332
(B-A)/B : 5.1284250335562
 
 
A: 00:00:01.0502144
B: 00:00:00.1692758
A/B     : 6.20416149266463
B/A     : 0.161182135761993
(A-B)/A : 0.838817864238007
(B-A)/B : 5.20416149266463
```

Implementation here: https://gist.github.com/justinvp/9de6d8dfe19be4c36ee0

**Comment by muratg** [comment]
@kichalla did you get a chance to look into this? Let's try to get it in Beta 6.

**Comment by kichalla** [comment]
I created a new gist(based on @justinvp's gist) with updated code which reflects the latest in Logging repo and also removed code which I felt is not necessary for our scenario(example: registering multiple loggers like Console, NLog etc)

https://gist.github.com/kichalla/47a4b7b4ede18abfd0ee

- When the log is *not* enabled, having extra IsEnabled check in the extension method is on average 6 times faster than the extension method not having this check.
- When the log level is enabled, the extra IsEnabled check in the extension method is almost comparable with the one not having the check.

@davidfowl @loudej @Eilon @muratg

**Comment by Eilon** [comment]
I think the ultimate case is that the code doing the logging needs to do this check, and if we have the log methods also do the check that would mean that there's double-cost for the `IsEnabled` check, which is what we want to avoid.

My stance is this:
* Code that has true performance concerns must check `IsEnabled` on its own anyway. This is to prevent other logging costs (such as gathering data to log) from costing.
* Code that isn't performance critical... can do whatever it wants.

**Comment by justinvp** [comment]
Developers don't know they must check `IsEnabled` on its own for the best perf. There are lots of uses in the aspnet libraries that would benefit from their own `IsEnabled` check that currently aren't doing the check. We can go fix all those places, but if someone has to remember to do it, they're going to forget and more misses are going to creep in.

The proposed helper methods wouldn't preclude the ability to avoid the extra `IsEnabled` check. For the most perf-sensitive cases where any extra `IsEnabled` calls are really too expensive, the extra `IsEnabled` call can be avoided by a perf-aware developer by checking `IsEnabled` on their own and then choosing to call a logger method that takes the array that doesn't do the extra `IsEnabled` check.

Note: As I mentioned before, there's already double `IsEnabled` checks going on (once up-front by the developer, and then again right before the log event is actually written out), so this is already happening. If multiple `IsEnabled` checks are really an actual perf issue, a slightly alternative API design could be used that would minimize the `IsEnabled` checks.

Usage would look something like:

```c#
_logger.Verbose.Log("OnReceived({0}, {1}, {2})", streamIndex, count, id);
```

Here `Verbose` is a property that does the `IsEnabled` check inside its implementation once before returning a logger. If the level isn't enabled, it returns a "NullLogger" which affectively does nothing (all calls to it are no-ops without any further `IsEnabled` checks). If the level is enabled, it returns an actual logger.

Such a design would support multiple calls to the level:

```c#
var verbose = _logger.Verbose;
if (verbose.IsEnabled)
{
   verbose.Log("OnReceived({0}, {1}, {2})", streamIndex, count, id);
   string blah = computeSomethingExpensive();
   verbose.Log("Blah happened {0}", blah);
}
```

**Comment by davidfowl** [comment]
@kichalla To add more data to the mix. Make sure that the args passed to Log aren't value types. Most of the log statements throughout the stack are either strings are objects. I want to make sure we have all of the right data.

**Comment by kichalla** [comment]
Commits: e635b4bc2d379dd84b1d1f10a7b0d0eb4ec2a81b to 7c01b9c3639801d89bd88bb607600c57dfd4cabf
