### ISSUE TITLE
Add Debug level to logging

### ISSUE THREAD

**Issue by lukewaters** [aspnet/Logging#103]
This logging level would be below verbose, and would indicate that sensitive application data is to be logged.  

With this change, the LogLevel enum would be changed to this

```
    public enum LogLevel
    {
        Debug = 1,
        Verbose = 2,
        Information = 3,
        Warning = 4,
        Error = 5,
        Critical = 6,
    }
```

**Comment by PureKrome** [comment]
How does `Debug` differ from `Verbose`? Some people use `Trace` instead, but `Verbose` sounds like an acceptable _catchall_. I can't see the value of both `D` and `V`.

**Comment by lukewaters** [comment]
This level differs from verbose in that log messages will contain data that would be omitted from verbose messages due to security concerns.  This bug works with issue #104 to allow messages to be conditionally evaluated, with secure information omitted from messages when log level is set to Verbose, and included in those log messages when the log level is set to debug

**Comment by ycrumeyrolle** [comment]
Guidelines should be updated to explain the differences between debug and verbose.
https://github.com/aspnet/Logging/wiki/Guidelines

**Comment by Eilon** [comment]
@lukewaters can you take a crack at this?

**Comment by Eilon** [comment]
(And should this bug be closed as well?)

**Comment by lukewaters** [comment]
Yep, I'll get to work on the docs

**Comment by Eilon** [comment]
Thanks! :book:
