### ISSUE TITLE
The type 'ILoggerFactory' exists in both 'Microsoft.Framework.Logging.ILoggerFactory, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Microsoft.Framework.Logging.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

### ISSUE THREAD

**Issue by vijayantkatyal** [aspnet/Logging#111]
in project.json

if i use:

"Microsoft.Framework.Logging": "1.0.0- * ",
"Microsoft.Framework.Logging.Console": "1.0.0- * "

instead of:

"Microsoft.Framework.Logging": "1.0.0-beta2",
"Microsoft.Framework.Logging.Console": "1.0.0-beta2"

i'm getting error:

The type 'ILoggerFactory' exists in both 'Microsoft.Framework.Logging.ILoggerFactory, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Microsoft.Framework.Logging.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

**Comment by Eilon** [comment]
@vijayantkatyal are you using just the latest NuGet packages, or also the latest XRE/KRE? You can't mix and match builds, so if you're using beta2 NuGet packages, you have to use the beta2 XRE/KRE. If you want to use the latest NuGet packages, get the latest XRE as well.

**Comment by vijayantkatyal** [comment]
all of nuget packages and kre version are set to beta2 version.

i think when i use * instead of beta2, this will fetch new versions(beta3, beta4) instead of beta2.

there should be a way to check the compatibility.

![image](https://cloud.githubusercontent.com/assets/1795103/6204323/35906efe-b56d-11e4-8115-3dda4beb5fcd.png)

**Comment by Eilon** [comment]
Correct, `*` will pull in the absolute latest, which is a lot newer than `beta2`. These compat problems are mostly a problem while the whole project is in pre-release. Once it hits the stable version, these types of issues will be much rarer.

**Comment by vijayantkatyal** [comment]
:+1:
