### ISSUE TITLE
Support of saving Logging data to a Database.

### ISSUE THREAD

**Issue by vijayantkatyal** [aspnet/Logging#112]

**Comment by davidfowl** [comment]
Using what kinda of technology? Entity Framework? Sql? MongoDB etc..... This would be another logger provider.

/cc @rowanmiller

**Comment by vijayantkatyal** [comment]
Entity Framework (default option). but i think other options also applicable according to someone needs.

i found a solution using NLog for Entity Framework.

https://github.com/ladenedge/NLog.EntityFramework. will try with ASP.NET Beta 2 and EF beta2.

**Comment by PureKrome** [comment]
@vijayantkatyal What you're talking about are `Targets` for NLog ([which has a nice list of already provided targets](https://github.com/nlog/nlog/wiki/Targets)) or `Sinks` for Serilog ([which also has a nice, rich list](https://github.com/serilog/serilog/wiki/Provided-Sinks)).

Sure, NLog (or Serilog) is not what everyone will want to use. :disappointed: 

> This would be another logger provider.

Yep - it's _not_ part of the core logging package but each target (eg. MSSql, RavenDb, LogEntries) etc would be a separate-package-per-target IMO. 

currently, (I think) there is:
- `install-package Microsoft.Framework.Logging.Console`
- `install-package Microsoft.Framework.Logging.Serilog`

So some new ones could be .. eg. 
- `install-package Microsoft.Framework.Logging.MSSql`
- `install-package Microsoft.Framework.Logging.LogEntries'

Put it this way @vijayantkatyal - _I don't want any db dependencies in the common logging library._

>Entity Framework (default option)

ewwwww at the default option, comment. Do you mean, EF as the first extra package to make? Or, are what you're really saying is: _I want to log to a MS-SQL DB? Do you really care -how- it's stored in the db .. but just that it is stored?_ If that's the case, then go right ahead (now) and use NLog's database target or that other repo you linked to, above (which btw, it also using NLog :stuck_out_tongue: ). If it's not and you really want a dedicated EF (or MS-SQL DB) package then yeah .. the Team has to decide if the effort is worth it (considering there's options already out there).

Right now, there's nothing stopping people from leveraging NLog with this Logging library to achieve what they want -> so nothing is red flagging / blocking them _right now_. Hopefully Serilog will be the other equal-option too :smile:

So - do we really need all these extra packages when we can just use NLog/Serilog?

**Comment by vijayantkatyal** [comment]
i think for now using existing options (NLog / Serilog) will be best. :+1:
