### ISSUE TITLE
Add ILoggerFactory.MinimumLevel

### ISSUE THREAD

**Issue by lukewaters** [aspnet/Logging#113]
This should be set to Verbose by default, anything logged at a level below MinimumLevel will not be sent to any registered logger.

**Comment by Eilon** [comment]
How exactly is this method used? Note that the logger factory implementation is not generally something that is customized. How would an app tweak the minimum level?

**Comment by lukewaters** [comment]
@lodejard  described this behavior in a comment on one of my previous pull requests

> The second step is to add an ILoggerFactory.MinimumLevel property which defaults to Verbose. The Logger instances at that point will check the level against the _factory.MinimumLevel in IsEnabled and WriteCore, and won't pass the call along to the providers' ILogger instances if the argument is lower than the property.

>So, all sensitive information is logger at Debug, and to see it the app must set loggerFactory.MinimumLevel = LogLevel.Debug in code before it will flow.

**Comment by Eilon** [comment]
Got it, thanks!

**Comment by davidfowl** [comment]
It's not a method

**Comment by lukewaters** [comment]
Fixed in #114
