### ISSUE TITLE
API review: DiagnosticsLogger and other related types

### ISSUE THREAD

**Issue by muratg** [aspnet/Logging#117]
- DiagnosticsLogger -> TraceSource
- DiagnosticsLoggerProvider -> TraceSourceProvider
- etc.

Also make DiagnosticsScope private.

**Comment by BrennanConroy** [comment]
I can't make DiagnosticsScope private. I could make the constructor private, but then would need to provide a method to create them, or make the constructor internal, or the class internal, either way, also requires the Testing project being allowed to see internals.

**Comment by glennc** [comment]
Move it to an internal namespace instead of making it private. We don't use InternalsVisibleTo
