### ISSUE TITLE
API review: LoggerExtensions changes

### ISSUE THREAD

**Issue by muratg** [aspnet/Logging#119]
- Move to Interfaces assembly
- Rename Write* methods to Log* (This is a big change across repos)

**Comment by BrennanConroy** [comment]
Moving to interfaces assembly would require adding a dependency on Microsoft.Framework.Logging to the .Interfaces assembly creating a circular dependency

**Comment by anurse** [comment]
There are a bunch of dependencies that have to come too (like LoggerStructureFormat) but then the dependencies should be fine. I'm going to do this as part of some work I'm doing for integrating Logging into the Runtime Core (as a submodule). PR to come soon.

**Comment by anurse** [comment]
Actually, I'm not going to do the Log* renames, so we might want to split this out or adjust it a bit...
