### ISSUE TITLE
API review: LoggerStructureBase and LoggerStructureFormat polish

### ISSUE THREAD

**Issue by muratg** [aspnet/Logging#124]
**LoggerStructureBase**
- Rename to ReflecionBasedLogValues (Check with Glenn)
- Remove Message (another work item tracks removal of this from the interface)

**LoggerStructureFormat**
- Move to .Internal namespace
- Rename class to FormattedLogValues
- Should follow pattern similar to LoggerStructureBase
- Remove Message (another work item tracks removal of this from the interface)

**Comment by BrennanConroy** [comment]
@glennc ReflecionBasedLogValues?
Also, LoggerStructureFormatter is only used in the Logging repo so I'm thinking move it to .Internal namespace too (and renaming, LogValuesFormatter?)

**Comment by glennc** [comment]
Yes to both of those questions.
