### ISSUE TITLE
Erorrs in VS but everything is ok for "k run"

### ISSUE THREAD

**Issue by colotiline** [aspnet/Logging#135]
Hello.
When I try to use `NLog` in Visual Studio, I've got 3 errors. But everything works fine when I use `k run`.
Screenshot: http://i.imgur.com/kk5f8LJ.png

`project.json`
```json
{
	"version": "1.0.0-*",
	"dependencies": {
		"Microsoft.Framework.Logging": "1.0.0-*",
		"Microsoft.Framework.Logging.Console": "1.0.0-*",
		"Microsoft.Framework.Logging.NLog": ""
	},
	"commands": {
		"Mailer": "run"
	},
	"frameworks": {
		"aspnet50": {
		},
		"aspnetcore50": {
			"dependencies": {
				"System.Console": "4.0.0-beta-22523"
			}
		}
	}
}
```

How to resolve this issue?

**Comment by BrennanConroy** [comment]
If you look closely you will see that the VS errors are for CoreCLR. I'm guessing that you are using DesktopCLR from the command line which will work (and VS doesn't show any errors for DesktopCLR).
I believe NLog is not available on CoreCLR. You can wrap the usages of it in #ifdef aspnet50 for VS to work.

**Comment by colotiline** [comment]
Thanks.
