### ISSUE TITLE
TraceSourceLoggerProvider > InitializeTraceSource is no use

### ISSUE THREAD

**Issue by leshin** [aspnet/Logging#141]
The Listeners and Switchs always to the same with _rootSourceSwitch !!

https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging/TraceSourceLoggerProvider.cs#L16

**Comment by davidfowl** [comment]
?

**Comment by leshin** [comment]
Why use TraceSource parentTraceSource = GetOrAddTraceSource(parentSourceName) ?
All the created logger by TraceSourceLoggerProvider that always use the _rootSourceSwitch and _rootTraceListener !
How to set different switch and listener for each logger?

**Comment by davidfowl** [comment]
What's the scenario you're trying to accomplish? The pattern here allows you to filter traces by prefix. It means that you can turn tracing on for Microsoft.AspNet and get all of the logs:

http://www.tugberkugurlu.com/archive/logging-in-the-owin-world-with-microsoft-owin--introduction

Check out this blog for an example.

**Comment by leshin** [comment]
Oh, I see !  I forgot can configure the switch and listener in the web.config.  Thank you very much!
