### ISSUE TITLE
[NLog] Created scopes are not printed as expected for async operations

### ISSUE THREAD

**Issue by suhasj** [aspnet/Logging#156]
The BeginScope for NLog provider creates an object and pushes it in the `NestedDiagnosticsContext` stack. This stack is stored in a ThreadLocalStorage which is good for synchronous operations. If we create the scope string using async methods or have async methods in the Log calls, the scopes are not shared and hence the output is not scoped as expected. The issue looks to be in the NLog assembly but opening it here to see if can fix it or at least be aware of the behavior

**Comment by 304NotModified** [comment]
Hi,

The NLog code will be moved to a new repository. (here)[https://github.com/NLog/NLog.Framework.logging]

We will try fix this also.
