### ISSUE TITLE
Add sugar around BeginScope

### ISSUE THREAD

**Issue by HaoK** [aspnet/Logging#158]
- BeginScope(object)
- BeginScope(string, params object[])): support for something like the LogVerbose: "Executing {display}", display to automatically generate the ILogValue

**Comment by kichalla** [comment]
I think this issue has been addressed few days back.
- ILogger's BeginScope is renamed to `BeginScopeImpl`
https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging.Interfaces/ILogger.cs#L36

- New logger extension to take in format string
https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging.Interfaces/LoggerExtensions.cs#L558
