### ISSUE TITLE
Remove ReflectionBasedLogValues type and instead use Custom formatted log values

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Logging#171]
This should probably be shared source somewhere.

https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging/ReflectionBasedLogValues.cs

**Comment by muratg** [comment]
Move to Common.

**Comment by kichalla** [comment]
commit 3912fc89c8217cd89e6e6568b63be260f2587032
