### ISSUE TITLE
LogEventLevel Debug for SerilogLogger?

### ISSUE THREAD

**Issue by wobuzhudao** [aspnet/Logging#183]
Is the case for `LogEventLevel.Debug` missing from `SerilogLogger.ConvertLevel(...)` for some reason? If I try to configure with Debug as the minimum level, I don't get debug messages. If I try to set the minimum level to Debug from the LoggerFactory, I get a `NotSupportedException`.

**Comment by Eilon** [comment]
@nblumhardt ? I think you were going to look at having a new home for the Serilog adapter?

**Comment by davidfowl** [comment]
The fix is in this  https://github.com/aspnet/Logging/pull/182

**Comment by nblumhardt** [comment]
:+1: - which is heading towards https://github.com/serilog/serilog-framework-logging (though the naming feels questionable). Aiming to have a first cut published in a few days.

**Comment by nblumhardt** [comment]
Package with the fixed level mapping is out now (details at the link above).

**Comment by ORuban** [comment]
Hi, could you also look to the NLogLogger? Debug messages are also missed, suggested PR (https://github.com/aspnet/Logging/pull/188).

**Comment by muratg** [comment]
@ORuban can you file a bug for the NLogLogger?
