### ISSUE TITLE
What happened to AddConsole

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/Logging#186]
Trying to add loggin to a unit test, but fail to find the AddConsole overload - what am I doing wrong:

https://github.com/aspnet/Logging/blob/dev/samples/SampleApp/Program.cs

**Comment by davidfowl** [comment]
Can you show your project and share more information about the versions of things that you're using?

**Comment by ErikEJ** [comment]
Sorted - Missed that is needed the seperate .Console MyGet package
