### ISSUE TITLE
Changing LogLevel enum to a enum with flags

### ISSUE THREAD

**Issue by SergeBerwert** [aspnet/Logging#190]
It would be grate to change the LogLevel enum to:

```c#
[Flags]    
public enum LogLevel
    {
        Debug = 1,
        Verbose = 2,
        Information = 4,
        Warning = 16,
        Error = 32,
        Critical = 64,
    }
```

With this it would be easy to select different levels, not just by hierarchy. You could filter for example Debug and Error or whatever you need.

**Comment by Eilon** [comment]
Is that a common thing? BTW most logging implementations will let you filter however you want by specifying some syntax (e.g. a lambda) to filter.

**Comment by SergeBerwert** [comment]
The advantage of this would be you could filter like this:

            var logLevel = LogLevel.Verbose;
            var filter = LogLevel.Debug | LogLevel.Information | LogLevel.Warning;
            var enable = (filter & logLevel) > 0;

This would filter log messages if the level is Debug, Information or Warning. And this is the fastest implementation for this scenario possible. This you could easy specified as a lambda but I would be faster than do something with contains or every other alternative.

**Comment by Eilon** [comment]
You can do pretty much the same filter with about as much code:

```c#
var enable =
    logLevel == LogLevel.Debug ||
    logLevel == LogLevel.Information ||
    logLevel == LogLevel.Warning;
```

**Comment by muratg** [comment]
Closing this one as @Eilon's suggestion should work.
