### ISSUE TITLE
Why are there public types in `Internal` namespaces?

### ISSUE THREAD

**Issue by justinvp** [aspnet/Logging#191]
Why are there `public` types in `Internal` namespaces?

 - [Microsoft.Framework.Logging.Internal.FormattedLogValues](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging.Abstractions/Internal/FormattedLogValues.cs)
 - [Microsoft.Framework.Logging.Internal.LogValuesFormatter](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging.Abstractions/Internal/LogValuesFormatter.cs)
 - [Microsoft.Framework.Logging.Console.Internal.IConsole](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging.Console/Internal/IConsole.cs)
 - [Microsoft.Framework.Logging.Internal.TraceSourceScope](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging.TraceSource/Internal/TraceSourceScope.cs)

**Comment by Eilon** [comment]
The `.Internal` namespace is for stuff we want to keep public so people can "use them at their own risk" but we make no guarantees about compatibility.
