### ISSUE TITLE
Add a DebugLoggerProvider that writes to Debug.WriteLine

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Logging#194]
Would be almost identical to the existing `ConsoleLoggerProvider` but it would write to `Debug.WriteLine`. It would enable itself only when the debugger is attached.

We should have this provider in the runtime by default so that any app will log messages to the debugger output, e.g. in Visual Studio.

**Comment by DamianEdwards** [comment]
Something like the one at https://github.com/jongalloway/ndc2015-aspnet5-workshop/blob/master/Labs/4%20-%20Dependency%20Injection%20%26%20Unit%20Testing.md#configure-a-logger-so-you-can-see-the-request-id-messages

**Comment by hishamco** [comment]
It will be nice if the logger will be added automatically by the runtime if the debugger is attached
:+1:

**Comment by muratg** [comment]
We think this can be done in DNX instead of a separate package

**Comment by muratg** [comment]
@kichalla We can potentially do this in DNX by bringing logging abstractions to DNX layer when you bring ILogger to DNX.  

https://github.com/aspnet/dnx/issues/1118

**Comment by davidfowl** [comment]
i would avoid the dnx for now and keep it localized to hosting

**Comment by DamianEdwards** [comment]
@davidfowl any particular reason? Because of the churn we're expecting in the DNX? We have other issues RE bringing the `LoggerFactory` down to DNX so it seems odd to not do it all at once.

**Comment by davidfowl** [comment]
Putting things int the dnx requires care in order to avoid pinning before the application loads. That plus the currently refactoring going on it seems unwise to make that layering decision at this point. We need an easy way to move things without pinning it before the app runs

**Comment by DamianEdwards** [comment]
If that's the case why don't we just put it in the templates only? Hosting still isn't really optional for apps anyway so maybe better to require it to be added by the app explicitly.

**Comment by davidfowl** [comment]
+1. We should at least do the feature for beta6 it's trivial. We can discuss moving it in by default at a later date.

**Comment by DamianEdwards** [comment]
K. What package should we put it in? Microsoft.Framework.Logging?

**Comment by davidfowl** [comment]
Separate package like the other providers

**Comment by DamianEdwards** [comment]
And you get a package! And you get a package! You all get packages!

**Comment by PureKrome** [comment]
![Developers Developers Developers!!!](http://upboat.me/att/packages/for-all-the-developers!.jpg)

**Comment by victorhurdugaci** [comment]
@davidfowl and @DamianEdwards do you like `Microsoft.Framework.Logging.Debug` as package name?

**Comment by DamianEdwards** [comment]
@victorhurdugaci yeah that's fine

**Comment by victorhurdugaci** [comment]
@DamianEdwards, @davidfowl do you want the template to add the logger or do you want it in hosting?

**Comment by DamianEdwards** [comment]
All of the project templates, inc. Empty.

**Comment by victorhurdugaci** [comment]
The templates part of this issue is here: https://github.com/aspnet/Templates/issues/124
