### ISSUE TITLE
LogLevel.Debug for NLog Logger

### ISSUE THREAD

**Issue by ORuban** [aspnet/Logging#196]
It seems like mapping between Microsoft.Framework.Logging.LogLevel and NLog.LogLevel is not fully correct:
- has missed Microsoft.Framework.Logging.LogLevel.Debug
- Microsoft.Framework.Logging.LogLevel.Verbose pointed to NLog.LogLevel.Debug instead of Trace

The main problem is that NLog.Logger.Debug method does not write any logs.
You can check the following PR: https://github.com/aspnet/Logging/pull/188

**Comment by muratg** [comment]
@ORuban thanks for the PR!  @kichalla Please have a look at the PR and if looks good, merge.

**Comment by kichalla** [comment]
Commit 0d6b4fcc2067e595452261c605fae8d9f15f0c82
