### ISSUE TITLE
Add CompositeLoggerProvider

### ISSUE THREAD

**Issue by hishamco** [aspnet/Logging#204]
Introducing a new ```CompositeLoggerProvider``` which is nothing but an aggregation for one or more ```LoggerProvider``` is very helpful when we want to log into different logger provider, e.g. we may wanna log into ```FileLoggerProvider``` and ```WindowsEventLoggerProvider``` in production and log into ```DebugLoggerProvider``` while the debugger is attached. So instead create each logger itself, we can pass a punch of loggers into this provider and it will take care for the rest (logs into different sources simultaneously).
Although this provider is trivial at the first glance but it might be very handy in many scenarios ..

**Comment by Eilon** [comment]
Can you show a code sample of what this might look like? How is it different from just adding several providers to the system?

**Comment by hishamco** [comment]
Sure, I will try to show a code sample soon. Regarding the second question the ```CompositeLoggerProvider``` doesn't different too much from  just adding several providers to the system, behind the scene it abstracts the creating of the loggers (DI) by passing a list of loggers and the provider will take care about the rest, also this is very handy if one of the providers goes down

**Comment by hishamco** [comment]
```csharp
public class CompositeLoggerProvider : ILoggerProvider
    {
        private readonly IList<ILogger> _loggers;

        public CompositeLoggerProvider(IList<ILogger> loggers)
        {
            _loggers = loggers;
        }

        public ILogger CreateLogger(string name)
        {
            return new CompositeLogger(_loggers);
        }
    }

public class CompositeLogger : ILogger
    {
        private readonly IList<ILogger> _loggers;

        public CompositeLogger(IList<ILogger> loggers)
        {
            _loggers = loggers;
        }

        public IDisposable BeginScopeImpl(object state)
        {
            return null;
        }

        public bool IsEnabled(LogLevel logLevel)
        {
            return true;
        }

        public void Log(LogLevel logLevel, int eventId, object state, Exception exception, Func<object, Exception, string> formatter)
        {
            foreach (var logger in _loggers)
            {
                logger.Log(logLevel, eventId, state, exception, formatter);
            }
        }
    }
```

**Comment by Eilon** [comment]
The code sample seems identical to registering multiple providers. If the scenario of a logging "going down" is an important one, wouldn't it be better if that was just built-in to the logging system?

**Comment by hishamco** [comment]
@Eilon this is just a sample code .. not the final :smile: , I know it will be better if that was built-in but this one case, and while the logger is accept a list of loggers, so we can add and remove loggers dynamically.
I hope to hear a feedback from the others to let you guys decide about this ..

**Comment by hishamco** [comment]
In nutshell it's an aggregate logger that logs into multiple sources

**Comment by Eilon** [comment]
Closing because there does not seem to be an obvious need for this.
