### ISSUE TITLE
Console logging coloring is weird on linux

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Logging#210]
Running the console logging on Ubuntu 14.04 LTS, it colors weirdly:

![image](https://cloud.githubusercontent.com/assets/328122/8464455/1f58095e-1ff7-11e5-9400-873a228324fa.png)

First message doesn't have the highlighting on the lines but others have.

**Comment by muratg** [comment]
@BrennanConroy

**Comment by BrennanConroy** [comment]
The only time we touch the background color in the console logger we turn it red for critical messages. So I'm not sure how this is happening

**Comment by tugberkugurlu** [comment]
The code which causes this issue is here if you want to try to repro: https://github.com/tugberkugurlu/k-http/tree/d961ebeab7c5601bf4679c2bc833e12a6b1c0a99

**Comment by muratg** [comment]
Let's investigate this for beta 6.

**Comment by BrennanConroy** [comment]
This is fixed in beta6 with: 18e367d36f2dac1e5072fa746590da85a779c5c5
