### ISSUE TITLE
Missing [NotNull] checks

### ISSUE THREAD

**Issue by justinvp** [aspnet/Logging#215]
I was going to submit a PR that added some missing `[NotNull]` checks with associated `Assert.Throws<ArgumentNullException>(() => ...);` tests, but it doesn't look like the `throw new ArgumentNullException(...)` code is being generated when the libraries are built.

 - Is this by design?
 - Is `[NotNull]` still the preferred way to add null checks?
   - If so, should `[NotNull]` be added anyway, without tests?
   - Otherwise, should `if (value == null) throw new ArgumentNullException(...)` checks be added instead, with tests?

A couple examples of where `[NotNull]` is missing (not exhaustive):
 - https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging/LoggerOfT.cs#L21
 - https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging.Console/ConsoleLogger.cs#L25

**Comment by Eilon** [comment]
Yes, use `[NotNul]`, but as you noted, it's not implemented yet, so you can't write unit tests for them. Having said that, even once it's implemented we don't plan to write unit tests for such cases anyway because they're not super helpful.

**Comment by muratg** [comment]
We should probably add the missing `[NotNull]` checks to the code without the unit tests for now. We'll be discussing implementation of actual functionality in Beta 7.

**Comment by 304NotModified** [comment]
Which `[NotNull]` is this? The [`NotNullAttribute` of Jetbrains](https://www.jetbrains.com/resharper/help/Reference__Code_Annotation_Attributes.html#NotNullAttribute)?

**Comment by muratg** [comment]
We had our own implementation that didn't really work.  It's now removed.  Instead we're using proper null checks within the methods.  

Closing this one.
