### ISSUE TITLE
DebugLogger nuget package doesn't contain Debug.WriteLine

### ISSUE THREAD

**Issue by ravengerUA** [aspnet/Logging#216]
Microsoft.Framework.Logging.Debug nuget package on Myget doesn't contain Debug.WriteLine() in the code.

**Comment by davidfowl** [comment]
That's right. it's in this package https://www.nuget.org/packages?q=System.Diagnostics.Debug. The System* packages are where the BCL types exist.

**Comment by ravengerUA** [comment]
I'm talking about this line
````C#
            if (string.IsNullOrEmpty(message))
            {
                return;
            }

            message = $"{ logLevel }: {message}";
            * System.Diagnostics.Debug.WriteLine(message, _name); *
````

Debug.WriteLine marked with ConditionalAttribute and won't go to compiled code, when you compile and publish this code to nuget packages.

**Comment by kichalla** [comment]
@davidfowl https://github.com/aspnet/Logging/pull/207/files#r33876417

**Comment by Eilon** [comment]
Yes, this never worked at all due to the comment @kichalla pointed out.

**Comment by Eilon** [comment]
@victorhurdugaci can you take a look at this for beta 6?
