### ISSUE TITLE
Azure Streaming Log with Trace

### ISSUE THREAD

**Issue by YZahringer** [aspnet/Logging#218]
Hello,

"System.Diagnostics.Trace.TraceInformation("Test Trace);" only write in the debug output window.

This should not write in the IIS logs? This should also work with Azure Streaming Log?

**Comment by jarroda** [comment]
Any help on this issue?  I am unable to get log output to show in the Azure web app log stream.

**Comment by npnelson** [comment]
+1 on this. I can't get this to work either.  I don't think it was working before beta8, but now that beta8 requires Kestrel, that might complicate the issue even more.  It would be nice to get an official statement, even if the statement happens to be "we won't be supporting this anytime soon"

**Comment by muratg** [comment]
@kichalla Did you recently do an investigation similar to this?

**Comment by kichalla** [comment]
@muratg No. For the packagesearch website I used Serilog framework + Azure DocumentDb

**Comment by muratg** [comment]
@Eilon I remember you were discussing this (logging in Azure) in another issue somewhere, but I can't seem to find it.  What was the outcome?

**Comment by Eilon** [comment]
Sorry I don't recall.

**Comment by muratg** [comment]
@davidfowl @lodejard What are your thoughts on this?  Should we recommend people to use something like Serilog or should we have an implementation that does this?

**Comment by Eilon** [comment]
Would be really great to support Azure streaming logs automatically. Can we talk to an Azure person to see what we have to do to be compatible? Does it just listen to some particular output, e.g. console? Or something?

**Comment by muratg** [comment]
I'll ping @davidebbo

**Comment by davidebbo** [comment]
I have an experimental project that should make that work today: https://github.com/davidebbo-test/ConsoleInterceptor. Give it a try and see how it fares.

**Comment by npnelson** [comment]
I got the consoleinterceptor to stream logs without any trouble, but I couldn't get them to upload to Blob storage by enabling Application Logging (blob) on the Azure web site.  I'm not sure how the Application Log (blob) works for classic ASP.NET apps.

Perhaps a classic ASP.NET app drops the log files in a different path than the console interceptor?  

It's probably user error on my part - I didn't try too hard to get it to work yet

**Comment by davidebbo** [comment]
Blob/Table storage is not supported at this point. For class .NET, it works via a registered trace listener, but that concept doesn't exist in ASP.NET 5 afaik. It's something we'll need to solve.

**Comment by qJake** [comment]
Is this still an issue? I'm running ASP.NET Core 1.0 RC1, and I have tried `Trace.WriteLine()` and `Trace.TraceXXX()`, and neither are writing to the application log. I don't even see an application log when I view my log directory via FTP, and I don't see any messages when I attach to the log via `azure site log tail`.

Am I doing something wrong, or is this still being worked on? Not being able to trace out an issue when deployed to Azure is frustrating. :confused:

**Comment by Tratcher** [comment]
There was a problem where HttpPlatformHandler would not flush the logs to the stream frequently: https://github.com/aspnet/IISIntegration/issues/57

We have a fix prepared for that, but we still need to get it deployed to azure and verify it.

**Comment by nulltoken** [comment]
Hey, @davidebbo just announced "You can now git deploy http://ASP.NET  Core RC2 projects to your Azure Web Apps. #aspnetcore #azure #kudu" in https://twitter.com/davidebbo/status/733040676879929344.

Is this bug still opened or do we still have to proxy the logs through `ConsoleInterceptor` or such?

**Comment by muratg** [comment]
This should be working now. If there are still issues, please file another bug.

**Comment by davidebbo** [comment]
@muratg what's the best way to test this? Specific, what does tracing code look like in RC2? I don't think it's `System.Diagnostics.Trace.TraceInformation("...");`, right?

**Comment by kichalla** [comment]
An example of how you can set it up: https://github.com/aspnet/Logging/blob/dev/test/Microsoft.Extensions.Logging.Test/TraceSourceLoggerTest.cs#L16-L23

and then its the usual `logger.LogWarning(")` etc.

**Comment by davidebbo** [comment]
I'm not seeing any log file getting created at all. My web.config has this:

    <aspNetCore processPath="dotnet" arguments=".\AspNetCoreRC2.dll" stdoutLogEnabled="true" stdoutLogFile="\\?\%home%\LogFiles" forwardWindowsAuthToken="false" />

What am I missing?

**Comment by muratg** [comment]
cc @moozzyk

**Comment by moozzyk** [comment]
@davidebbo - has the application started successfully? Do you see any entries from AspNetCoreModule in the (counterpart of) eventlog? Can you share your application so that I can try it?

**Comment by davidebbo** [comment]
@moozzyk Try https://github.com/davidebbo-test/AspNetCoreRC2VS. Just git deploy it to an Azure Web App, and then edit the web.config as above.

Yes, it runs fine. It just doesn't seem to create an logs at all.

**Comment by davidebbo** [comment]
And yes, there is a startup message from core module:

    <Event>
        <System>
            <Provider Name="IIS AspNetCore Module"/>
            <EventID>1001</EventID>
            <Level>0</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2016-05-19T23:10:11Z"/>
            <EventRecordID>11903046</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD00155DF7B4CB</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Process '4924' started successfully and is listening on port '24820'.</Data>
        </EventData>
    </Event>

**Comment by davidebbo** [comment]
@moozzyk I see, the problem is that you gave the wrong info [here](https://github.com/projectkudu/kudu/issues/2014#issuecomment-220400330) :)

> remove the stdoutLogFile attribute or set the value to \\?\%home%\LogFiles and set stdoutLogEnabled to true

`stdoutLogFile` needs can't be set to `\\?\%home%\LogFiles`, because that's a folder. Instead, it needs to be something like `\\?\%home%\LogFiles\corelogs`. Then it seems to work well enough!

**Comment by moozzyk** [comment]
@davidebbo - crap - I copied it directly from the code but it was from the code where we come up with the folder and then we append the file. Apologies!

**Comment by davidebbo** [comment]
No problem, it's good that it works!

We should think about making this easier for Azure users, though, so they don't have to manually change `stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout"`.

I'll start another issue.

**Comment by moozzyk** [comment]
You don't need to - one already exists: https://github.com/aspnet/IISIntegration/issues/167

**Comment by moozzyk** [comment]
As a workaround - you can just remove the `stdoutLogFile` attribute entirely and publish-iis will set it correctly depending on whether you publish to Local file system or Antares (with VS)

**Comment by davidebbo** [comment]
Too late, I opened #429

**Comment by davidebbo** [comment]
@moozzyk in that case, we should change the VS template to do this. I just have whatever it generated, and so will most users.

**Comment by moozzyk** [comment]
This is one of the option we discussed but it was too late to rush anything for RC2 without risking regretting it later.
