### ISSUE TITLE
Console output

### ISSUE THREAD

**Issue by adamhathcock** [aspnet/Logging#219]
Right now the LogConsole class writes to the Error stream.  I don't want to do that :)

Should I invest extending the code and make my own IConsole or should I do a PR to allow a custom IConsole?  Or something else?

Thanks.

**Comment by Eilon** [comment]
Is there a reason you don't want it to write to the error stream?

**Comment by adamhathcock** [comment]
I could have sworn Console logging wasn't working unless it was on the Out stream.  Retesting things on VS2015 final with beta5 is proving me wrong.

**Comment by Eilon** [comment]
By default certainly on Windows both the Out stream and the Error stream are written to the visible console. Only if you do a redirect (e.g. `foo.exe > foo.txt`) do you generally have to worry about Out vs. Error.

**Comment by adamhathcock** [comment]
Thanks for the info
