### ISSUE TITLE
Clarification of BeginScope extension method

### ISSUE THREAD

**Issue by trevorreeves** [aspnet/Logging#222]
The `ILogger` `BeginScope` extension method provides the same method signature as the message logging methods.  Which implies that string messages (potentially with log values specified as well) can be provided as the scope state.

Now of course, multiple nested scopes can be created, which implies that multiple scope-messages are specified, hence any log calls inside one of these scopes will possibly have multiple string messages attached to it (potentially each bringing with them some log values).

From what I can see currently, no logging provider honours log messages specified as scope state; the current Serilog provider doesn't support the messages provided as scope state (only the log values extracted from it), nor from what I can tell does the NLog provider.

So my point is that even though it's an extension method, `BeginScope` gives the impression from its signature, that it should be more commonly used than `BeginScopeImpl`, which 'feels' more low level/internal.  However, its method signature is not currently supported by any provider.  This is misleading and confusing to consumers.

A further point of discussion is whether it would even be appropriate to record multiple 'scope messages' for each log message.

**Comment by kichalla** [comment]
> From what I can see currently, no logging provider honours log messages specified as scope state; the current Serilog provider doesn't support the messages provided as scope state (only the log values extracted from it), nor from what I can tell does the NLog provider.

Serilog has a sink for ElasticSearch where you can see these nested scoped log values & messages. https://github.com/serilog/serilog-dnx-prerelease
Also there is an [ElmLoggerProvider](https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNet.Diagnostics.Elm/ElmLogger.cs) where the scoping provides a visual representation of the nested scopes and messages.

> A further point of discussion is whether it would even be appropriate to record multiple 'scope messages' for each log message.

An example of where  this is useful is with ElasticSearch. We create(by default in hosting layer) a logging scope which has the current request's identifier and this scope is available for all the log messages further down the pipeline. Now this helps in searching in ElasticSearch where you could say something like...where request id ='id' and orderstate='confirmed' etc.

**Comment by trevorreeves** [comment]
Thanks for replying.

1). Forgive me if I'm getting this completely wrong, but Serilog-dnx-prerelease contains some sinks and enrichers.  I was referring to the SerilogLoggerProvider  : https://github.com/serilog/serilog-framework-logging/blob/dev/src/Serilog.Framework.Logging/SerilogLoggerProvider.cs#L43

Which tries to cast the scope state to ILogValues to get the values out of the log message.  But doesn't do anything with the message itself (i.e. stateStructure.ToString()), so any sinks will not know about any scope messages.

2). Yes I see, this feature makes more sense in that diagnostic scenario.

I'm happy to close this now - though if you have time to clear up my misunderstanding around Serilog I would grateful :-)
