### ISSUE TITLE
[NLog] Filtering logging by type or event id

### ISSUE THREAD

**Issue by suhasj** [aspnet/Logging#23]
Hooking up the current NLog provider helps in logging but the log file generated has log statements from framework components as well. Should we provide a way to customize the log statements based on types or/and event ids too ?

**Comment by veccsolutions** [comment]
Since this is now a nuget package will it be fixed? I do have code available I can put in a pull request to fix the issue with callsite showing the framework logging classes/methods instead of the correct one.

**Comment by Eilon** [comment]
@veccsolutions this is still just a sample that isn't published anywhere. It exists to help us validate our design and is not intended to be full featured. Expect the sample to eventually be deleted.

**Comment by 304NotModified** [comment]
Hi,

The NLog provider code will be moved to a new repository. [here](https://github.com/NLog/NLog.Framework.logging)

I think this issue can be closed in this repos.

Thanks for submitting feedback @suhasj !

**Comment by Eilon** [comment]
@304NotModified awesome, thanks! We'll be deleting the NLog provider here most likely this week.

**Comment by Eilon** [comment]
@304NotModified the removal is tracked here: https://github.com/aspnet/Logging/issues/341

BTW do you want to send us a PR to update the Readme file at https://github.com/aspnet/Logging/blob/dev/README.md to point to NLog?

**Comment by 304NotModified** [comment]
@Eilon sure, will do that when it's done at our site. Can we take over the current code copyright issues?

**Comment by Eilon** [comment]
@304NotModified not sure what issue that is. Can you email me at elipton_AT_microsoft.com?

**Comment by 304NotModified** [comment]
@Eilon The mail has been sent :)

**Comment by Eilon** [comment]
Thanks, I just sent you a reply.
