### ISSUE TITLE
Static LogManager

### ISSUE THREAD

**Issue by adamhathcock** [aspnet/Logging#231]
I was wondering if there was a place for a static logging context instead of having to have ILoggerFactory injected into each constructor then creating ILogger for each class I want to use logging.

In log4net, typically you just add the line that looks something like this: "private static readonly ILog log = LogManager.GetCurrentClassLogger()" and most other logging frameworks (NLog, Serilog) have something similar.

Besides having to initialize the LogManager, is there a reason there isn't a static LogManager?  Would I be doing myself a disservice by creating one?

**Comment by davidfowl** [comment]
Statics have all the same downsides they always had. It makes things harder to test or be multi-tenant. The fact that we avoid statics completely means we don't have to think about those problems. Our tests can run in parallel freely without the fear of shared static state.

You can of course create your own static but this library won't be providing any out of the box for you.
