### ISSUE TITLE
FormattedLogValues is allocated per-logger call. Can that be avoided as a ctor? 

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Logging#234]
Can the formatter-worker be created-and-used at logger site instead?

![formattedlogvalues](https://cloud.githubusercontent.com/assets/249088/9283173/8871e1ba-4286-11e5-900b-0fae8f286be0.jpg)

**Comment by muratg** [comment]
@DamianEdwards As we have improved the perf of the stack overall, did this become more important?

**Comment by pakrym** [comment]
`FormattedLogValues` is a struct now.
