### ISSUE TITLE
NLog LogLevels are mismatched.

### ISSUE THREAD

**Issue by czema** [aspnet/Logging#237]
In NLog, Trace is the lowest level and Debug is the second lowest.  In MS Logging, Debug is the lowest and Verbose is second lowest.  NLogLoggerProvider.cs::75 needs to be changed.

    private global::NLog.LogLevel GetLogLevel(LogLevel logLevel)
        {
            switch (logLevel)
            {
                case LogLevel.Debug: return global::NLog.LogLevel.Trace;
                case LogLevel.Verbose: return global::NLog.LogLevel.Debug;
                case LogLevel.Information: return global::NLog.LogLevel.Info;
                case LogLevel.Warning: return global::NLog.LogLevel.Warn;
                case LogLevel.Error: return global::NLog.LogLevel.Error;
                case LogLevel.Critical: return global::NLog.LogLevel.Fatal;
            }
            return global::NLog.LogLevel.Debug;
        }

**Comment by adamhathcock** [comment]
Serilog has a similar issue.  Both NLog and Serilog have Verbose/Trace being the lowest level while Debug is the second lowest.  MF.Logging has Debug being the lowest.

What is the reasoning?  Any chance MF.Logging can change this?  I realize this could be too late. 

I'm used to log4net where there is no Trace/Verbose just Debug so I've been confused for a while.

**Comment by nblumhardt** [comment]
+1 if it is at all possible to consider a change at this point; a bit awful having Verbose => Debug and Debug => Verbose :-)

**Comment by aggieben** [comment]
I prefer Debug as lower than Verbose.  In an ideal world, one could have:
```csharp
enum LogLevel
{
    Critical,
    Error,
    Warning,
    Information,
    Verbose,
    Debug,
    Trace
};
```

I'm actually having problems with `Microsoft.Framework.Logging.Serilog.SerilogLogger.ConvertLevel()`:

```
2015-09-03 13:48:14 [Error] CanReadToken: Runtime Exception! Specified method is not supported.
System.NotSupportedException: Specified method is not supported.
   at Microsoft.Framework.Logging.Serilog.SerilogLogger.ConvertLevel(LogLevel logLevel)
   at Microsoft.Framework.Logging.Serilog.SerilogLogger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   at Microsoft.Framework.Logging.Logger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   at Microsoft.Framework.Logging.LoggerExtensions.LogDebug(ILogger logger, String data)
   at Cm.Core.Security.Authentication.SessionTokenValidator.CanReadToken(String securityToken) in C:\Users\Benjamin\Projects\cm-core\src\Cm.Core\Security\Authentication\SessionTokenValidator.cs:line 49
```

**Comment by czema** [comment]
Looks like you are using an older beta of Microsoft.Framework.Logging.  Beta-7 doesn't include Serilog.  Please see https://github.com/serilog/serilog-framework-logging

As for your particular problem, if you look at the [beta-4 version of Serilog](https://github.com/aspnet/Logging/blob/1.0.0-beta4/src/Microsoft.Framework.Logging.Serilog/SerilogLogger.cs#L93) you will see that LogLevel.Debug does not have a mapping, you need to use LogVerbose.

**Comment by aggieben** [comment]
@czema sorry - I deleted my comment because I realized I was commenting in the wrong repo (and that my problem not what I thought it was at first blush, as you pointed out).

**Comment by nblumhardt** [comment]
@czema @aggieben the Serilog provider moved over to be maintained by the Serilog project: https://github.com/serilog/serilog-framework-logging

The more time I spend with this the more of an annoyance I think it might turn out to be. At RTM, anyone wanting to take advantage of the structured logging support in _Microsoft.Framework.Logging_ is likely to do it via one of the already-existing Serilog sinks ([there are many](https://github.com/serilog/serilog/wiki/Provided-Sinks)). Having two levels with the same names but different semantics will make this awkward to say the least :-)

**Comment by nblumhardt** [comment]
(Should add, I'm happy to PR this if it's a viable change.)

**Comment by PureKrome** [comment]
Another plus :one: to making `Trace`/`Verbose` as the lowest and `Debug` and 2nd lowest.

**Comment by 304NotModified** [comment]
+1

**Comment by tugberkugurlu** [comment]
:+1: change this, break me :smile: PowerShell also has Debug as the lowest level.

**Comment by tugberkugurlu** [comment]
sorry, I was thinking this is the serilog repo, got excited. I would say Debug is the correct lowest level. PowerShell also has Debug as the lower level.

**Comment by nblumhardt** [comment]
@tugberkugurlu just to clarify why I think this is a worthwhile change, I don't think it's so much a question of correctness, since "debugging" and "verbose logs" go hand in hand. For example:

> The Write-Verbose cmdlet writes text to the **verbose** message stream in Windows PowerShell. Typically, the verbose message stream is used to deliver information about command processing that is used for **debugging** a command.

https://technet.microsoft.com/en-us/library/hh849951.aspx

It's probably one of those things where whichever you see first seems like the natural choice (as with many things you can find valid rationales for both).

My +1 was with respect to ease of integration with NLog and Serilog, which are going to appear in .NET apps alongside this library (and in suites of apps especially while large teams move onto ASP.NET 5.

My $0.02 of course :-) Cheers!

**Comment by PureKrome** [comment]
@ ASPNET team - any feedback on this issue? Thoughts:

1. We're going to change it (before RTM)
2. We're too busy to think about this _but we will answer this before RTM_
3. We're too busy to think about this _and will deal with it POST RTM_
4. We're not going to change it because XXXX reason(s).

Cheers :)

**Comment by 304NotModified** [comment]
Good sum up @purekrome!

**Comment by Eilon** [comment]
I think we're considering "merging" the Debug and Verbose values back into one. We had split them apart a while ago for some reasons that we don't think are needed anymore. If that's the case, we might be able to simplify things a bit.

**Comment by PureKrome** [comment]
Thanks @Eilon for the prompt update :+1: Very much appreciated :smiley:

**Comment by nblumhardt** [comment]
+1 also, thanks @PureKrome and @Eilon! :-)

The merging idea sounds like a winner to me, FWIW.

**Comment by davidfowl** [comment]
What @Eilon is failing to mention is that by merging we we're going to call it Verbug or Debose :smile:

**Comment by PureKrome** [comment]
![lol](http://i.imgur.com/QaSg0LD.gif)

**Comment by adamhathcock** [comment]
+1 for Verbug

**Comment by muratg** [comment]
This has recently changed.

**Comment by 304NotModified** [comment]
Changed in what?

**Comment by muratg** [comment]
https://github.com/aspnet/Announcements/issues/124

**Comment by 304NotModified** [comment]
Thanks!
