### ISSUE TITLE
dnu restore doesn't find the beta6 packages for NLog

### ISSUE THREAD

**Issue by gnewtzie** [aspnet/Logging#238]
I'm having an issue where the beta 6 packages can't be found when doing a dnu restore on a project. The main Microsoft.Framework.Logging package can be found but not the NLog package for beta 6.

"Microsoft.Framework.Logging": "1.0.0-beta6",

I've tried `1.0.0-*`, `1.0.0-beta6`, `1.0.0-beta6*`, `1.0.0-beta6-11503`... they all don't find the package anymore. Only if i had already cached it in my dnu package cache is the package resolved.

**Comment by michalstepien** [comment]
I have the same error.

**Comment by glennc** [comment]
@gnewtzie What feeds are you restoring from?

@victorhurdugaci Can you take a quick look at this and see what's going on?

**Comment by shirhatti** [comment]
We don't plan to ship a package for `NLog`
We have prototyped what using `NLog` might look like, but it is not officially supported. You are always welcome to grab the source from [here](https://github.com/aspnet/Logging/tree/dev/src/Microsoft.Framework.Logging.NLog) and use it.

**Comment by michalstepien** [comment]
Ok, thanks, in this sample is use: https://github.com/aspnet/Identity/tree/dev/samples/IdentitySample.Mvc
