### ISSUE TITLE
LoggerExtensions in Abstractions Folder

### ISSUE THREAD

**Issue by ardalis** [aspnet/Logging#240]
LoggerExtensions.cs should be moved out of the Abstractions folder. It's already not in that namespace.

**Comment by davidfowl** [comment]
I don't understand the suggestion.

**Comment by ardalis** [comment]
LoggerExtensions isn't an abstraction, but the file is in the Abstractions folder.

The class isn't in the Abstractions namespace, which adds weight to the argument that the class does not belong in that folder.

**Comment by glennc** [comment]
LoggerExtensions contains extension methods for ILogger, which is an abstraction and in the same namespace as LoggerExtensions. Are you arguing that we move the extension methods out of the assembly of the type they are extending?

**Comment by ardalis** [comment]
I think my understanding of the project organization wasn't very good when I opened this issue. I had thought that Abstractions was a folder within the Logging project, not necessarily its own package, and having the extensions within that folder, but in a different namespace, seemed odd to me. Now I see that it is in fact a separate package, which does change things a bit. I still think it a bit odd that there doesn't appear to be any use of a namespace for Abstractions, and my initial reaction to seeing non-interfaces/base types in an Abstractions namespace is confusion, but if you're basically treating the extensions as extensions on the interfaces (which appears to be the case), and not as a place where real logic is occurring, then it makes sense for things to stay as they are.

Sorry for the long comment - I'll close the issue. Thanks.
