### ISSUE TITLE
Question: is App_Data still a thing?

### ISSUE THREAD

**Issue by jods4** [aspnet/Logging#242]
In old-school ASP.NET, `App_Data` was a special folder. Because ASP.NET watched files for changes (and restarted when say, an .aspx page changed) it was ill-advised to modify files or folders at runtime.

To support scenarios where you _want_ to write files at runtime (e.g. dynamic images generation, file-based database, **or log files**) `App_Data` was a special folder, inside which you could freely write.

It is my understanding that there is still some watching going on, e.g. IIS would restart automatically if you change ASP.NET 5 code in some .cs files. So my question is: what is the recommended place to put files that you want to write into, e.g. log files? Is it OK to put them anywhere? Is there an `App_Data` equivalent?

**Comment by muratg** [comment]
https://github.com/aspnet/Hosting/issues/344 

cc @victorhurdugaci

**Comment by Eilon** [comment]
`App_Data` didn't really have anything to do with restarting apps as far as I know.

There were only two special things about `App_Data` from what I recall:

1. It was not servable by the web server
2. It was writeable by the app

Item (1) isn't an issue anymore because in ASP.NET 5 apps only the content in the `wwwroot/` folder is servable. So you can put data files anywhere in the app except that folder.

Item (2) I *think* was just an issue due to Code Access Security, which isn't a thing anymore. Apps are fully trusted to write whatever they want within the application. This assumes that the server has the correct file permissions set, but that's orthogonal to ASP.NET.

**Comment by davidfowl** [comment]
> It is my understanding that there is still some watching going on, e.g. IIS would restart automatically if you change ASP.NET 5 code in some .cs files. So my question is: what is the recommended place to put files that you want to write into, e.g. log files? Is it OK to put them anywhere? Is there an App_Data equivalent?

You should assume that file watching is a development feature only. You have to shutdown the application yourself if you want to have it restart (on IIS at least).

**Comment by jods4** [comment]
OK so the short answer is: 
Put your log files anywhere you like in the app folder but outside `wwwroot`

Thanks.

**Comment by Eilon** [comment]
Pretty much!

**Comment by Eilon** [comment]
Or perhaps even better, send the logs to a remote server. If your server is in a cloud environment, the file system might not be a reliable place to put data.

**Comment by blowdart** [comment]
In addition you should consider putting your log files on a separate drive to your OS. Log files take up a lot of space if they're detailed, and it's better if they're off the OS drive, so failure is more graceful.

Web Apps should be on their own drive as well as a matter of course to minimise problems of path transversal in buggy apps.

**Comment by jods4** [comment]
Thanks for the additional tips.
The app is an on-premise enterprisy thing and filesystem is what the customer wants.

@blowdart Since you mention space...
The goal here is not to log everything ASP.NET 5 logs, but only some app-specific data with relevant information for troubleshooting (e.g. notably uncaught exceptions). So the log is expected to be pretty small and will surely be configured on a rolling fashion (say, keep 1 month of log).

Given that, do you think it makes sense to use ASP.NET 5 built-in logging abstractions and my own key, e.g. `Logger<MyApp>`  -- or skip that and directly use a third-party logger such as NLog (which would probably be at the _actual_ logger in the first case anyway).

**Comment by blowdart** [comment]
I can't answer the question of which logger because I'm just the security person, but I would say if you're logging uncaught exceptions an attacker can probably detect those (via status code 500), run fiddler, keep sending the same request over and over and, well, there we go :)

**Comment by jods4** [comment]
@blowdart we're going on a tangent here I'm afraid, but I'm curious :smiley: 

You are right of course about that. But is this something that an application should care about?
To succeed in bringing your server down this way an attacker would have to spam it hard. If you are a public property exposed to DoS attacks and want to prevent them, wouldn't that be the job of a dedicated proxy that filters incoming requests, prevents DDoS and so on? I am no expert in security, but spamming a server with 5xx responses seems highly suspicious to me.

Then, you still need to have _some_ error reporting don't you? Old ASP.NET used to log uncaught exceptions into the Windows Event Log by default. Wasn't that just as unsecure (by the same logic)?

**Comment by blowdart** [comment]
Security tangents are what I excel at :) Windows will truncate the event log by default at 64k. So it was better than non-rotating logs. But yea, you'd hopefully have a proxy, waf or something else in front of your app, but just in case you'd also harden the app config as part of defence in depth.

**Comment by jods4** [comment]
OK thanks. I did not know that Event Log was cut by default at 64K. I am surprised as it seems the event log contains a lot of data for 64K on my machine (or maybe there's a GPO that raised that limit here).

Good logging framework (e.g. NLog) let you rotate your logs by size as well, so that's an option of course.

**Comment by blowdart** [comment]
Of course generally you'd have a secure this OS roll-out script anyway, right? :)

(I went looking for the default size, and can find 20Mb back in the 2003 days. So yea, it's probably greater. My memory is awful, apologies)
