### ISSUE TITLE
Logger null exception

### ISSUE THREAD

**Issue by ngonzalezromero** [aspnet/Logging#248]
i have this method

```c#
    public void ExceptionLogAndThrow<T, TY>(ILogger<TY> logger, string message,   [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0) where T : Exception, new()
        {
            var ex = (T)Activator.CreateInstance(typeof(T), message);
            logger.LogError(message, ex, memberName, sourceFilePath, sourceLineNumber);
            throw ex;
        }
```

but fails with the following error

```
   Microsoft.Framework.Logging  -> System.AggregateException: An error occurred while writing to logger(s). ---> System.NullReferenceException:
```

Startup class

```c#
    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerfactory, IApplicationEnvironment appEnv)
        {
            var url = $"{Configuration["AppSettings:DBConnection:Mongo:Url"]}/{Configuration["AppSettings:DBConnection:Mongo:MongoDbNames:Logs"]}";
            var log = new LoggerConfiguration().MinimumLevel.Information().WriteTo.MongoDB(url).CreateLogger();

            loggerfactory.AddSerilog(log);
        }
```

proyect.json

```json
       "dependencies": {
       "Microsoft.AspNet.Server.Kestrel": "1.0.0-beta7",
       "Microsoft.AspNet.Mvc": "6.0.0-beta7",
       "Microsoft.AspNet.Server.IIS": "1.0.0-beta7",
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta7",
    "Microsoft.Framework.Configuration": "1.0.0-beta7",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta7",
    "Microsoft.Dnx.Runtime": "1.0.0-beta7",
    "Microsoft.Framework.Logging": "1.0.0-beta7",
    "Serilog.Framework.Logging": "1.0.0-beta7-10052",
    "Serilog": "1.5.11",
    "Serilog.Sinks.MongoDB": "2.0.13",
    "Csiro.Api.Domain": "1.0.0-*",
    "Csiro.Util.Infrastructure": "1.0.0-*",
    "Csiro.Api.Repository": "1.0.0-*",
    "Csiro.Api.Service": "1.0.0-*",
    "Csiro.Api.Util": "1.0.0-*",
    "FluentValidation": "5.6.2"
    },
```

**Comment by Eilon** [comment]
@ngonzalezromero can you debug this and see what the inner exceptions of the aggregate exceptions are? That will tell you the real exception that's happening.

**Comment by ngonzalezromero** [comment]
System.AggregateException: An error occurred while writing to logger(s). ---> System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Serilog.Framework.Logging.SerilogLogger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   en Microsoft.Framework.Logging.Logger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Microsoft.Framework.Logging.Logger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   en Microsoft.Framework.Logging.Logger`1.Microsoft.Framework.Logging.ILogger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   en Microsoft.Framework.Logging.LoggerExtensions.LogError(ILogger logger, String format, Object[] args)
   en ApiUtil.ExceptionLogAndThrow[T](Object logger, String message, String memberName, String sourceFilePath, Int32 sourceLineNumber) Serilog.Framework.Logging.SerilogLogger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   en Microsoft.Framework.Logging.Logger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)<---

**Comment by Eilon** [comment]
The top of the stack is Serilog itself. @nblumhardt , any idea on this?

**Comment by ngonzalezromero** [comment]
I tried without serilog 

      loggerfactory.AddConsole();

and no error occurred
perhaps serilog is the problem

**Comment by muratg** [comment]
Closing as this looks like a serilog issue.

**Comment by nblumhardt** [comment]
Yes, looks like this was in the Serilog integration code. There's been a fair bit of change since September, I'd suspect this is no longer an issue (at least, there have been no other reports). 

@ngonzalezromero please feel free to open  ticket on https://github.com/serilog/serilog-framework-logging referencing this one if you still observe an error here.

(@Eilon, sorry I missed your comment the first time around!)
