### ISSUE TITLE
Add support for filtering by source/wildcard/level to debug and console

### ISSUE THREAD

**Issue by rynowak** [aspnet/Logging#251]
We want to have a simple experience for using an IConfiguration to setup various log levels for various log sources.

Straw man:
```
public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
{
    loggerFactory
        .AddConsole(Configuration.Get<ConsoleLoggerOptions>("logging"))
        .AddDebug(Configuration.Get<ConsoleLoggerOptions>("logging"));
}

```

Once this is done, it needs to go into the template with some reasonable defaults for all of the framework components we include in the template.

**Comment by muratg** [comment]
@rynowak Do we want this in V1, or is this a post V1?

**Comment by rynowak** [comment]
We added the support for this to Console logger. IMO we can live without it for debug logger for now.

The remaining work here is to make sure the template is in good shape. We tried to ship this in the template in rc1, but ran into blocking bugs and reverted the change.

**Comment by muratg** [comment]
@rustd Is the template work re: console logger tracked in TFS or GitHub?

**Comment by rustd** [comment]
Template work is GitHub. If there are any tooling changes required then it is TFS

**Comment by muratg** [comment]
@rustd Please file a ticket on templates repo if you'd like to have these in the templates in RC2.
