### ISSUE TITLE
Move Microsoft.Framework.Logging.Testing to this repo

### ISSUE THREAD

**Issue by Eilon** [aspnet/Logging#252]
It's in https://github.com/aspnet/Testing/ right now.

There are currently some circular references in the repo-to-repo dependencies that we'd like to fix, and this is one of them. The idea of putting this package here is that if you're referencing the regular runtime package, you may very well want the companion test-helper package as well.

Note: the package needs to stay in the `/src` folder because this is a "runtime" package, even if it's test helpers.

**Comment by Eilon** [comment]
Related: https://github.com/aspnet/HttpAbstractions/issues/418

**Comment by kichalla** [comment]
718ac11d11dc8b3fd0a96c4d866d164f073ef23b

**Comment by kichalla** [comment]
https://github.com/aspnet/Logging/pull/266

**Comment by heathyates** [comment]
Is Microsoft.Framework.Logging.Testing now called Microsoft.Extensions.Logging?

**Comment by kichalla** [comment]
Its `Microsoft.Extensions.Logging.Testing`

**Comment by heathyates** [comment]
@kichalla 
I tried that and I am getting this in my project.json. I am getting other rc1-final packages without issues? 
![image](https://cloud.githubusercontent.com/assets/1896424/11515637/7d443414-9844-11e5-914e-5f1d75f10073.png)
I am using `https://www.nuget.org/api/v2`

**Comment by kichalla** [comment]
you are right, I do not see it in nuget.org... @Eilon , this package is available on myget's aspnetmaster feed though...is this expected?

**Comment by TJSoftware** [comment]
'M.E.L.T.' is just a test project to verify if the logging tools are working.  I would not expect that to be deployed to NuGet.  What functionality do you need from 'M.E.L.T.'?

![image](https://cloud.githubusercontent.com/assets/4823412/11515828/2b2f1f9c-983d-11e5-91b3-3018f6bd652e.png)

**Comment by heathyates** [comment]
@TJSoftware I am honestly not sure why this is in my test project folder. I'll remove it and see if it introduces any breaking changes.

**Comment by kichalla** [comment]
@TJSoftware the names here are confusing...its `Microsoft.Extensions.Logging.Testing`(under `src` folder in the image above) and not ` Microsoft.Extensions.Logging.Test`...the `Microsoft.Extensions.Logging.Testing` project just contains some mock implementations of loggers which are used in different repos' unit testing and so probably its not very useful for outside users as you can write your own mock implementations

**Comment by TJSoftware** [comment]
@kichalla I saw that too just after I posted.  @heathyates If you are using a clone of the Logging app, there may be changes still.  I found out with [this comment](https://github.com/aspnet/Logging/issues/292#issuecomment-160706959) some features are added just to see if the Logging program works.  I would assume that these are there as not only a test, but as an example to learn from.
