### ISSUE TITLE
[Design] Errored loggers causing cascade loops?

### ISSUE THREAD

**Issue by benaadams** [aspnet/Logging#255]
If a logger throws an exception it will be rethrown; and then potentially relogged, which may then throw an exception due to the errant logger, etc, etc or move up throw the exception chain until it rises to the top level of the app?

Should a logger that keeps throwing errors be disconnected for a time?

Also all the error messages say ["An error occurred while writing to logger(s)."](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging/Logger.cs#L87); whether its ```Log```, ```IsEnabled``` or ```BeginScope```

**Comment by muratg** [comment]
@benaadams do you have a repro, or is this theoretical? We had some discussions about exceptions in the loggers (wheter to prevent any exception from loggers or not), and our feeling like loggers should throw exceptions.  Of course cascade loops are probably should not happen.

**Comment by benaadams** [comment]
Was theoretical; happy to close it - likely to be more a setup issue also.
