### ISSUE TITLE
Optimize BeginScope to avoid having to pass a pre-calculated string to it

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Logging#261]
This will avoid having to create strings for the scope message before a log message is ever logged. This currently shows up in the profiles for the plaintext benchmark.

@lodejard is putting together a design PR for this.

**Comment by muratg** [comment]
Just talked to @lodejard.  Moving is issues to RC2.

**Comment by lodejard** [comment]
Closed, this is implemented by ilogger's define messages and lazy evaluation of string message and trace identifier.
