### ISSUE TITLE
Move LoggerExtensions to sub-namespace of current namespace.

### ISSUE THREAD

**Issue by YEVHENO** [aspnet/Logging#267]
As developer I want to be able not to use class LoggerExtensions. I want to be able implement extension methods for ILogger: LogDebug, LogError etc. Here there is a problem: if I use namespace Microsoft.Extensions.Logging, LoggerExtensions is always visible.

**Comment by Eilon** [comment]
Hmm not sure what to do about that - it's a general problem with extension methods. If the extension method is in the same namespace and assembly as its target, it'll always be available.

The trade-off here is whether it should be made more complex for the most common case (using the built-in extension methods), or whether there should be more ease of customization.

I think in this case we find it unlikely that many will want to re-implement the LogWarning, LogInfo, etc. methods. But we've seen many people add their own unique log methods, such as LogDatabaseError, LogUserInfo, etc.

I'd like to learn more about how your methods are different from the built-in ones - maybe there's room for improvement in the built-in ones?

**Comment by YEVHENO** [comment]
The problem with existing logger extension methods is the following: they do not allow change formatter. I want implement my own extension methods. For instance name LogError is quite reasonable for me. But it would be quite confusing to have two sets of such extension methods.

**Comment by Eilon** [comment]
Can you share more about what you want to do with a custom formatter?

**Comment by YEVHENO** [comment]
Unfortunately I'm not supposed share logs format that I need to write. It should be more complex than existing formatter. And I cannot achieve what I need with that level of customization.

**Comment by Eilon** [comment]
Can you solve this by writing a custom ILoggerProvider instead? Ultimately the formatters are just about converting the data into a string format, which is intended to be *human*-readable, so the exact format generally doesn't matter a whole lot. An ILoggerProvider, on the other hand, gets the raw data values, so it can store those in a machine-readable format.

**Comment by YEVHENO** [comment]
I can definitely solve this by writing custom ILoggerProvider and ILogger. If I do formatting inside ILogger implementation, that would simply mean that it should ignore formatter passed through Log method. Then, what is the purpose of the formatter and why it should be a part of Log method signature?

**Comment by Eilon** [comment]
The formatter is just about converting the data to strings for loggers that don't understand structured data. If I understood, your logger *does* understand structured data and is less interested in the human-readable string. Is that correct?

**Comment by YEVHENO** [comment]
My expectation was that logger should not understand data structure and formatter should be responsible for that.

**Comment by Eilon** [comment]
If a logger wants to support structured logging then it needs to at least understand that the logs have structure, though it need not know what that structure is. That is, it needs to know that in addition to a human-readable string there are also key/value pairs, but it doesn't have to care about what is in those key/value pairs.

Can you provide more details about what is special about your implementation of the formatter? Even just a rough outline of what it does, and why.

**Comment by YEVHENO** [comment]
This is what existing formatter does if I pass state and error: string.Format(CultureInfo.CurrentCulture, "{0}{1}{2}", state, Environment.NewLine, error).

Let's say I want to have something like this: string.Format(CultureInfo.CurrentCulture, "{0}|:|{1}: {2}", state, error, error.StackTrace).

**Comment by Eilon** [comment]
That seems like a fairly minimal change that doesn't affect human readability. I'm not saying it's bad, but it doesn't seem to be in the spirit of keeping the formatter as a human-readability processor.

**Comment by pakrym** [comment]
Moving LoggingExtenions would be a huge breaking change.
