### ISSUE TITLE
Add LoggerMessage.Define overloads for 0, 4, 5, and 6 args

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Logging#272]
Please add a non generic version of `LoggerMessage.Define` because there are cases in which the logged message doesn't have any parameters

**Comment by kichalla** [comment]
Ideally using `Define` is not required in the case where you are *not* using a message format string and do not have any parameters to pass. `Define` was optimized for these cases for perf reasons. 

That said, we currently have an extension for `DefineScope` which does not take in any arguments...probably this should be removed to keep it consistent with `Define` @rynowak 
https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/LoggerMessage.cs#L20

**Comment by Eilon** [comment]
We should have overloads for: no parameters, and also need to add overloads for 4, 5, and 6 args.
