### ISSUE TITLE
Console Logger's colors on Mac are incorrect

### ISSUE THREAD

**Issue by kichalla** [aspnet/Logging#281]
Example:

![ansiconsoleonmac](https://cloud.githubusercontent.com/assets/6559784/10844254/6f5df986-7ebb-11e5-905b-33ca346d496f.png)

**Comment by BrennanConroy** [comment]
Is this mono? It has color issues.

**Comment by muratg** [comment]
@kichalla Does CoreCLR have the same issue?

**Comment by muratg** [comment]
@BrennanConroy Do you know if CoreCLR has this issue?  If this is Mono only, we can move to Backlog.

**Comment by BrennanConroy** [comment]
I haven't noticed, I'll check

**Comment by BrennanConroy** [comment]
CoreCLR and Mono have the same colors looks like, what is actually wrong with the colors?

**Comment by BrennanConroy** [comment]
Colors have changed a bit since this issue, and they look fine now, closing.
