### ISSUE TITLE
Change name of Switches in configuration for ConsoleLogger

### ISSUE THREAD

**Issue by rynowak** [aspnet/Logging#282]
_From @rustd on October 30, 2015 20:40_

hange name of the switch from Switches -> LogLevel or something better.

_Copied from original issue: aspnet/Configuration#324_

**Comment by rynowak** [comment]
_From @divega on October 30, 2015 21:4_

@rynowak does this bug belong in Logging?

**Comment by rynowak** [comment]
Yep. I'll move it.

**Comment by rustd** [comment]
Can you please update the templates as well once we have a successful coherence-signed build with these changes /cc @joeloff

**Comment by rynowak** [comment]
Leaving this open to track the change to the templates. This just went into release.

**Comment by rynowak** [comment]
As of 12 PST this still hasn't made it through coherence signed.

**Comment by rustd** [comment]
:(

**Comment by rynowak** [comment]
This has gone into release in templates
