### ISSUE TITLE
Support buffering per-scope in Console Logger

### ISSUE THREAD

**Issue by rynowak** [aspnet/Logging#284]
We want to add a feature that will buffer all outgoing log messages while inside a scope, so they can be grouped and separated with a trailing newline.

This will make the formatting much more readable for understanding units of work.

**Comment by muratg** [comment]
Two questions around this:
- If apps (let's say a console app, long running process) doesn't close the scope, do we have a leak, and no log output? 
- What happens when there are multiple threads writing to the Console logger?

**Comment by muratg** [comment]
Punting for now.

**Comment by muratg** [comment]
Closing this as we're preparing to move this repo over to Extensions.
