### ISSUE TITLE
Consider move NullLogger to Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by troydai** [aspnet/Logging#288]
https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Testing/NullLogger.cs is helpful in situation to prevent null instance been injected.

```
private ILogger _logger;

public Component(ILogger logger)
{
    _logger = logger ? new NullLogger();
}
```

Leave it in the `Microsoft.Extensions.Logging.Testing` packages make the application to depend on additional package and namespace.

**Comment by muratg** [comment]
Triaged out.

**Comment by Mnuzz** [comment]
Broken link - It's a good habit to link to the commit and not the branch
