### ISSUE TITLE
Logger dynamic reload does not work for webapps on Linux coreclr

### ISSUE THREAD

**Issue by kirthik** [aspnet/Logging#290]
When I change the logging level in .json file while the web app is running, changes are not reflected on console for Linux on coreclr. If I restart the app, then changes are reflected. Dynamic reload works on Console app on the same platform.

For reference here is my code

`HomeController`  - 
```
private readonly ILogger _logger;
public HomeController(ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger<HomeController>();
        }

public IActionResult Index()
        {
            _logger.LogInformation("In HomeController Info");
            _logger.LogWarning("In HomeController warning");
            _logger.LogCritical("In HomeController Unexpected critical error starting application");
            _logger.LogError("In HomeController error");

            return View();
        }
```

`appsettings.json` - 
```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Verbose",
      "System": "Information",
      "Microsoft": "Information",
      "WebApplication1.Controllers": "Warning"
    }
  }
}
```

**Comment by pranavkm** [comment]
This one seems odd. I was able to get a minimal repro by adding a `FileSystemWatcher` to the application's Startup. For Mvc applications events are raised until the first request following which the watcher never raises events. The issue reproes with the minimal Mvc sample (no views) and one with everything compiled (so no DNX file watchers). The issue doesn't repro with vanilla Kestrel (I used the Kestrel sample app).

Any ideas on where I should investigate further? @Tratcher \ @davidfowl \ @rynowak

**Comment by Eilon** [comment]
Do you have a guess as to where the bug is? In ASP.NET? CLR? OS?

**Comment by pranavkm** [comment]
@davidfowl, the issue seems to crop up once we invoke `ILibraryManager.GetReferencingLibraries'. Here's the minimal repro steps:

```C#
public void ConfigureService(IServiceCollection services)
{
    services.AddMvcCore();
}

public void Configure(IApplicationEnvironment app)
{
    var fsw = new FileSystemWatcher(AppContext.BaseDirectory);
    fsw.EnableRaisingEvents = true;
    fsw.Changed += (sender, e) =>
    {
        Console.WriteLine(e.FullPath);
    };
    
    app.Run(context =>
    {
        var routeContext = new RouteContext(context);
        var libraryManager = context.RequestServices.GetRequiredService<ILibraryManager>();
        // Until this line is hit, the FSW continues to raise events.
        libraryManager.GetReferencingLibraries("foo");
        
        var content = Encoding.UTF8.GetBytes("Hello world");
        return context.Response.Body.WriteAsync(content, 0, content.Length);
    });
}
```

Are we overwhelming it with watches when we invoke `GetReferencingLibraries`? That said, since the implementation of `ILibraryManager` is going to change, I'm going to hold off on digging into it any further.

**Comment by pranavkm** [comment]
@Eilon, both @kirthik and I have been using Ubuntu machines. I'm not sure if this issue also affects OSX.

**Comment by davidfowl** [comment]
I'm not sure how ILibraryManager could be affecting anything. It's looking up a dictionary entry.

**Comment by pranavkm** [comment]
Should I dig into it further or just wait until we swtich to the CLI's implementation of `ILibraryManager`?

**Comment by pranavkm** [comment]
Not seeing this with an app running on dotnet.
