### ISSUE TITLE
ILogger.BeginScopeImpl naming question

### ISSUE THREAD

**Issue by MarkPflug** [aspnet/Logging#291]
What is "Impl" supposed to mean? Why would this method not just be called BeginScope?

**Comment by Eilon** [comment]
It's a scary looking name because it's meant to be scary :smile: 

It is so named because it is a core implementation of the interface but users generally shouldn't call it. There's instead an extension methods for `BeginScope` that provides more user-friendly versions of the method.

**Comment by ranjancse26** [comment]
Why it is publicly exposed if it's not supposed to be called at all :smile:

**Comment by Eilon** [comment]
@ranjancse26 it's exposed because people implementing loggers need to implement it, but should never be called by an app.

And BTW, your car *does* expose the engine: there's a latch to open up the hood. But generally only a mechanic looks under there (and, of course, a few other curious souls!).

**Comment by ranjancse26** [comment]
@Eilon Thanks for replying. Now I understand. You nailed the :car:  scenario.

**Comment by Eilon** [comment]
You're welcome!
