### ISSUE TITLE
Remove dependence Microsoft.Extensions.PlatformAbstractions

### ISSUE THREAD

**Issue by loqix** [aspnet/Logging#293]
https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs#L45
RuntimeEnvironmentHelper.IsWindows cann't run on .net core console host app, it can instead RuntimeInformation.IsOSPlatform(OSPlatform.Windows)

**Comment by davidfowl** [comment]
@loqix in RC1 that's the case, but in RC2 it won't be. https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Extensions.PlatformAbstractions/DefaultRuntimeEnvironment.cs#L63

We'll likely remove the dependency anyways since it makes sense.

**Comment by muratg** [comment]
Fixed in https://github.com/aspnet/Logging/commit/67388033a4bec697832a6e748722e36664181b7b
