### ISSUE TITLE
Access to unformatted strings

### ISSUE THREAD

**Issue by MikeyBurkman** [aspnet/Logging#295]
So I'm working on a provider that would send our errors/warnings to an external error tracking application. I can't send the entire formatted message there, as it would result in a unique occurrence of that error message every time. (Not to mention some possible privacy concerns.) I would like to send the unformatted message as a way of tracking the message.

For instance, given the line:

```
_logger.LogInformation("User typed '{input}' on the command line", input);
```

I would want to send only `"User typed '{input}'"` to the external system. However, there doesn't appear to be way to do this. I could cast the "state" object in ILogger.Log() to ILogValues or FormattedLogValues, but neither gives me access to the original format string. (And even then, that type of casting from object seems hackish at best.) Any thoughts?

**Comment by MikeyBurkman** [comment]
As an addendum to this, there are certain types that our logger will always have to obfuscate for security purposes. While I can enumerate the keys/values from ILogValues, I don't seem to be able to change the values at all. Again, having access to both the format string and the values would allow me to get around this.

**Comment by kichalla** [comment]
@MikeyBurkman Regarding the original format string, there is an item in the log values list with key called `{OriginalFormat}` representing it

**Comment by MikeyBurkman** [comment]
That seems... not very type-safe... That's also is assuming an undocumented implementation detail of a class inside a namespace that contains the word "Internal". I mean, it does work for now, but it's hardly something I would trust to put in production code.

**Comment by kichalla** [comment]
cc @loudej @lodejard

**Comment by muratg** [comment]
@MikeyBurkman Agreed, you should not use internal implementation details. 

Your use case is still not clear to me, but if you want to track the message, can't you just use the state object as an identifier?

**Comment by adamchester** [comment]
Just FYI - [Serilog/serilog-framework-logging](https://github.com/serilog/serilog-framework-logging) does currently [rely on the internal {@OriginalFormat} key](https://github.com/serilog/serilog-framework-logging/blob/ab9e43fd263d923fa49833026333ccb709220679/src/Serilog.Framework.Logging/SerilogLoggerProvider.cs#L50)

**Comment by cwe1ss** [comment]
> @muratg Your use case is still not clear to me, but if you want to track the message, can't you just use the state object as an identifier?

This use case is important if you don't use EventIds. In this case the OriginalFormat-string is the only way to do reports on your logs. You would just use `SELECT COUNT(*) FROM logs WHERE OriginalFormat = "User typed '{input}'"` to filter for certain log messages or `SELECT TOP 10 OriginalFormat, COUNT(*) FROM logs GROUP BY OriginalFormat ORDER BY 2 DESC` to get the log messages with the most occurences.

I can understand that EventIds are a burden for many people and for many smaller projects. So I agree that this is an important topic. Maybe this key could be exposed as a property to hide the implementation details?

**Comment by nblumhardt** [comment]
:+1: for exposing `OriginalFormat` as a property, this would be nicer for the Serilog integration to work with. As @cwe1ss mentions, it's a core part of the story for message template-based structured logging.

@muratg @MikeyBurkman `"OriginalFormat"` is exposed in a public dictionary - so not strictly an internal implementation detail.

Let me know if you need any more info on the use case; `OriginalFormat` is critical for us.

Cheers!

**Comment by pakrym** [comment]
We are going to keep `OriginalFormat` as the way to access unformatted string.

**Comment by lodejard** [comment]
Hi, just thought I'd add 2¢ talking about how the logger was designed and intended to be used.

Yes, `{OriginalFormat}` is public surface area and you can use it in production code. It is not an implementation detail - the logging fwk itself never uses it - and is provided specifically so log providers can do things like serilog does. A custom formatter that provides colorization of values on command line, for example, or using the original format as a way to categorize messages when an application doesn't provide distinct event IDs.

The punctuation around it is to enable a log provider to differentiate systemic properties from event properties.

Also TState *should not* be as-cast as a known class. The only two things a logging provider should do with TState is pass it to the formatter to access the stringified log line, and as-cast it as the name-value interface to access the properties of a message which has structure.

**Comment by lodejard** [comment]
One other note about the reasons the system ended up with that design...

TState can be a value-type struct, which means if an event is logged thousands of times a second - and nobody is recording that category+severity combination - then there are no objects or strings allocated on the heap to be gc later. If the API used an abstract class or interface as as the event state parameter then it couldn't be allocation-free. Casting a struct to an interface boxes it, so there would be an allocation to call log.

The reason for the formatter func is more obvious - you don't pay memory and CPU to format string messages that don't get logged. And in cases where the provider is doing it's own formatting you don't pay for the default formatting of a message string that isn't used.
