### ISSUE TITLE
Remove ILoggerFactory.MinimumLevel

### ISSUE THREAD

**Issue by Eilon** [aspnet/Logging#298]
This property has two things going against it:
1. Everyone thinks it does something other than what it does. (This can be mitigated by a rename of some sort.)
2. It's not needed anymore. It was added to avoid sensitive information being logged inadvertently. This was later decided to be a non-issue.

This is teh codez: https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/ILoggerFactory.cs#L14-L17

@lodejard @muratg @DamianEdwards

**Comment by lodejard** [comment]
:+1: this should have been removed a while ago!

**Comment by muratg** [comment]
Agreed!

@JunTaoLuo :gift:

**Comment by JunTaoLuo** [comment]
merged to dev

**Comment by joeaudette** [comment]
so is there a new way to set the loglevel?

**Comment by Eilon** [comment]
@joeaudette the thing is, this never set the log level. That's why we're removing it. It just sets the minimum *allowed* log level. Each individual logger (e.g. DebugLogger, ConsoleLogger, EventLogLogger, SerilogLogger, etc.) has their own configuration and settings to decide what they track.

**Comment by joeaudette** [comment]
that makes sense, Thanks!

**Comment by joeaudette** [comment]
just to help others since breaking change announcements usually provide the old and the new way of doing things.
old way:

    loggerFactory.MinimumLevel = LogLevel.Warning;
    loggerFactory.AddConsole();

new way:

    loggerFactory.AddConsole(minLevel: LogLevel.Warning);

**Comment by JunTaoLuo** [comment]
@joeaudette thanks for the suggestion.

**Comment by sunsided** [comment]
@joeaudette that makes things clearer indeed.

**Comment by Eilon** [comment]
BTW, you *always* needed `loggerFactory.AddConsole(minLevel: LogLevel.Warning);` to get the right behavior. So in theory a properly-configured app should just remove the call to `loggerFactory.MinimumLevel`, but everyone was confused, so it was more complicated :smile:
