### ISSUE TITLE
AddEventLog(EventLogSettings) extension XML doc does not properly document the API

### ISSUE THREAD

**Issue by Mertsch** [aspnet/Logging#303]
The following 1.0.0-rc1-final code copies the XML doc of ```AddEventLog(this ILoggerFactory factory, LogLevel minLevel)``` but there is no ```minLevel```, you need to set a filter within ```EventLogSettings```.

```
/// <summary>
/// Adds an event logger that is enabled for <see cref="T:Microsoft.Extensions.Logging.LogLevel"/>s of minLevel or higher.
/// 
/// </summary>
/// <param name="factory">The extension method argument.</param><param name="settings">The <see cref="T:Microsoft.Extensions.Logging.EventLog.EventLogSettings"/>.</param>
public static ILoggerFactory AddEventLog(this ILoggerFactory factory, EventLogSettings settings)
```

**Comment by davidfowl** [comment]
@Mertsch care to send a pull request?

**Comment by Mertsch** [comment]
@davidfowl yes, will do so within the next 2 days.

**Comment by muratg** [comment]
@JunTaoLuo you can get the PR in once it's sent.

**Comment by Mertsch** [comment]
PR is here https://github.com/aspnet/Logging/pull/306

**Comment by JunTaoLuo** [comment]
Merged to dev after minor grammar update. Thanks @Mertsch!
