### ISSUE TITLE
NullReferenceException in RuntimeEnvironmentHelper under .NET 4.5 using Logging

### ISSUE THREAD

**Issue by adamhathcock** [aspnet/Logging#309]
I wrote this under DNX but maybe it's more appropriate here: https://github.com/aspnet/dnx/issues/3218

Basically, the usage of a DNX specific thing causes an exception when trying to use Console logging.  I have a sample and more details on the other issue.

**Comment by davidfowl** [comment]
Yep, it's a bug. It should be resolved in RC2.
