### ISSUE TITLE
ILoggingFactory should not implement IDisposable

### ISSUE THREAD

**Issue by dotnetjunkie** [aspnet/Logging#319]
A similar issue has been raised [here](https://github.com/aspnet/Mvc/issues/3726). Abstractions should not implement `IDisposable`, as @nblumhardt explained this very clearly almost six years ago (and quoted by @ploeh):

> an interface [...] generally shouldn't be disposable. There's no way for the one defining an interface to foresee all possible implementations of it - you can always come up with a disposable implementation of practically any interface.

While the default `LoggingFactory` implementation can (and probably must) be disposable, the interface shouldn't be.

**Comment by ploeh** [comment]
:+1:

**Comment by Eilon** [comment]
@lodejard thoughts on this?

**Comment by muratg** [comment]
@rynowak What are your thoughts on this (and [the corresponding MVC bug](https://github.com/aspnet/Mvc/issues/3726))?  

We should follow similar patterns...

**Comment by Eilon** [comment]
Discussed with @rynowak and @lodejard and we agree the interface shouldn't implement `IDisposable`.

**Comment by Eilon** [comment]
@lodejard putting on your plate.

**Comment by Eilon** [comment]
After further consideration, we think this change would be incorrect. The disposability of `ILoggerProvider` objects in an `ILoggerFactory` is a contractual obligation and needs to be enforced. Because `ILoggerProviders` are constructed outside a container, there is no central location for them to be disposed aside from the `ILoggerFactory`.

**Comment by ploeh** [comment]
Interfaces aren't contracts: https://blogs.msdn.microsoft.com/kcwalina/2004/10/24/api-design-myth-interface-as-contract
