### ISSUE TITLE
Logging not working in Azure

### ISSUE THREAD

**Issue by steve-warwick** [aspnet/Logging#320]
Maybe I'm just missing something, but it appears to me that logging is not working in Azure. I verified that logging works as expected locally.I can see messages in the "Debug" window. In the "Diagnostics logs" blade I have  "Application  Logging (FileSystem)" set to on. The level is set to "Verbose". I have "Application Logging (Blob)" set to on, level set to "Verbose" and configured to a local storage account. I assume I should see log files in the server explorer under "my service/Log Files/application", but I see nothing. I see nothing in blob storage either. I made sure the application logging settings were set in the portal as well. At this point I don't know what else to try. It's really frustrating that there is nothing the logging documentation that explains how to setup and view the logs in Azure. I would try to remote debug it in Azure, but apparently this isn't working either. It works for ASP.NET 4.X, but not for ASP.NET 5 apps. I can attach to the WebApp, but I can't set any breakpoints. I don't see anything in the debug window when attached to the WebApp in Azure. I see something called "Stream Logs" under "View Settings/Logs". In that window it says "Application logging (persisted in Microsoft Azure Storage) is not enabled. Click the Configure Logging link above to enable it". When I click this link it attempts to take me into the Azure portal somewhere, but fails with "The Microsoft Azure Portal encountered an error while trying to access your subscription" No matter what I try I can't get past this, yet I can log into the portal just fine my self. Visual studio explorer is logged into the portal just fine as well. So, I have no idea how this thing is suppose to work, but either I'm totally missing something or there is a bug here. Any thoughts or suggestions?

**Comment by muratg** [comment]
@kichalla Could you please investigate?

**Comment by kichalla** [comment]
@steve-warwick which logger are you using? Is this a custom logger that you implemented? I ask as we do not have an out of the box logger to log in Azure. Could you share how your logger code looks like?

The following website is running ASP.NET 5 RC1 version and uses Serilog framework to log into Azure Document Db, so logging works fine in general.
http://packagesearch.azurewebsites.net/

**Comment by kichalla** [comment]
@steve-warwick ping

**Comment by steve-warwick** [comment]
I assumed there was a default azure logging framework built into the Azure for ASP.NET 5. Looks like I made an incorrect assumption. Is this going to be case for GA? Seems like a glaring omission to me. The link you provided above doesn't show anything. Could you provide a link that works?

**Comment by kichalla** [comment]
That link was only to the website that is using the logging and doesn't show any logs actually. Following is some info on how to use Serilog's framework to add logging to your app in Azure:

**project.json**(note that the following packages do not work on core clr)
```
"Serilog.Framework.Logging": "1.0.0-rc1-final-10071",
"Serilog.Sinks.AzureDocumentDb": "1.5.4"
```

**In Startup's Configure method:**
```
// endPointUri and accountKey come from document db connection string
var logger = new LoggerConfiguration()
    .MinimumLevel
    .Warning()
    .WriteTo
    .AzureDocumentDB(endpointUri, accountKey)
    .CreateLogger();

loggerFactory.AddSerilog(logger);
```

**Comment by kichalla** [comment]
Closing this issue now. If you run into any issue feel free to open an issue.
