### ISSUE TITLE
LogLevel Debug not shown in Console logger

### ISSUE THREAD

**Issue by DasJott** [aspnet/Logging#325]
AddConsole(LogLevel.Debug) does not show strings from Loggers doing

_logger.LogDebug("Foo");

**Comment by muratg** [comment]
This should work in theory. Could you share a basic repro?  Is this on CoreCLR Or full CLR.

**Comment by sescandell** [comment]
@DasJott are you in a "IIS" Context?

I had to use `AddDebug(LogLevel.Debug)` in order to make it working (in a IISExpress run from VS15).

**Comment by DasJott** [comment]
Sorry, I am a few days in offline world.
This bug appears in a small project running in dnx on Linux.
Every level works perfectly, except the debug one.
Do I Miss an include or something?
Am 07.01.2016 4:47 nachm. schrieb "Stéphane" <notifications@github.com>:

**Comment by muratg** [comment]
@DasJott When you're back, could you please share your repro?  DNX version you're using, your project.json, and a simple program.cs would suffice.

**Comment by DasJott** [comment]
Of course I will. I try  as soon as possible.
Am 09.01.2016 10:27 nachm. schrieb "Murat Girgin" <notifications@github.com

**Comment by DasJott** [comment]
I attached the whole small project, simply zipped.

In Startup.cs, line 31, is where the loglevel is set.
In BundleService.cs, line 27 should originally be LogDebug, but as that doesn't appear anywhere, I chose LogVerbose for now.


[HelloMvc.zip](https://github.com/aspnet/Logging/files/85134/HelloMvc.zip)

**Comment by muratg** [comment]
@BrennanConroy Could you take a look?

**Comment by BrennanConroy** [comment]
So there is a MinimumLevel value in the LoggerFactory which is causing your Debug logs to not be shown, you can set this value in your Startup.cs. It has since been removed in RC2 see https://github.com/aspnet/Announcements/issues/122

**Comment by DasJott** [comment]
Okay, that was not intuitive. Didn't try it though...
Can I get the rc2 somehow using the version manager?
Thanks for figuring it out for me, @BrennanConroy!

**Comment by BrennanConroy** [comment]
Change your feed to https://myget.org/F/aspnetvnext/api/v2 and change your dependencies.
