### ISSUE TITLE
Logger from Type name shouldn't include generic parameters

### ISSUE THREAD

**Issue by lodejard** [aspnet/Logging#326]
At the moment I believe an ILogger for `MyNamespace.MyClass<AnotherNamespace.AnotherType>` will  return a logger category name which ends with the `<AnotherNamespace.AnotherType>`

It shouldn't, really, because the logging configuration decisions should be made only on the `MyNamespace.MyClass` portion. Especially because systems which do logger configuration inheritance are based on a `.` delimiter the portion of the name `MyClass<AnotherNamespace` defeats that convention.

**Comment by muratg** [comment]
:+1:

**Comment by Eilon** [comment]
The poor type beautifier... and all the work that went into... copying existing code from another project :frowning:

**Comment by kichalla** [comment]
d14f47546320901e4d29b8fa03504af001640fa7
