### ISSUE TITLE
how to fix  Failed to add reference to 'System.Collections.Concurrent'?

### ISSUE THREAD

**Issue by endink** [aspnet/Logging#327]
Cant use Logging with .net Framework 4.5.1 project, some denpendeny missed when nuget restoring and throw: Failed to add reference to 'System.Collections.Concurrent'. Please make sure that it is in the Global Assembly Cache.
Maybe because of EntityFramework?

**Comment by muratg** [comment]
This doesn't seem to be the right place for this bug.  @anurse Do you remember discussing about this elsewhere?
