### ISSUE TITLE
Move TestLogger and helpers to aspnet/Logging

### ISSUE THREAD

**Issue by SonjaKhan** [aspnet/Logging#33]
Move the [following files](https://github.com/aspnet/Mvc/tree/dev/test/Microsoft.AspNet.Mvc.Core.Test/Logging) into the Logging Repo so we can easily test Logging from any repo without having to create (or replicate) supporting classes.

**Comment by davidfowl** [comment]
Can we do this? They are in the Testing repository right now. I can't remember what we decided to do with them:
/cc @glennc @muratg @lodejard

**Comment by muratg** [comment]
@davidfowl sure..

**Comment by BrennanConroy** [comment]
We just moved these to the testing repo because of the logging API review. So what do we want to do?

**Comment by muratg** [comment]
Thanks Brennan, yup that was the decision from the API review.  I think we should keep these in Testing repo.  Unless someone objects, I think we should close this one.

**Comment by BrennanConroy** [comment]
Ping

**Comment by muratg** [comment]
Closing this one. @davidfowl please reopen if you think we should change this back.
