### ISSUE TITLE
Release Microsoft.Extensions.Logging.NLog?

### ISSUE THREAD

**Issue by 304NotModified** [aspnet/Logging#339]
We are a bit confused. There is some code here to get NLog working with ASP.Net 5, but it isn't released as NuGet package. Why not? Are there any troubles with this code? Do we (NLog) need to provide our own package?

Cheers,
Julian (NLog team)

Edit: I see this is related: https://github.com/aspnet/Logging/issues/292 (https://github.com/aspnet/Logging/issues/292#issuecomment-160706959)

PS: There is also a PR, which is unclear if it will be merged or rejected: https://github.com/aspnet/Logging/pull/262

**Comment by davidfowl** [comment]
> There is some code here to get NLog working with ASP.Net 5, but it isn't released as NuGet package. Why not?

We don't own that product so we shouldn't be releasing it on nuget. 

> Do we (NLog) need to provide our own package?

Yes! We ideally want to delete this code from our repository. It was here to help validate our extensibility but we'd want the NLog team to own it (similar to how serilog took over).

**Comment by 304NotModified** [comment]
Thanks for the quick response!

We will fix a package soon. If that is done, the code can be removed here :) 

I will let you know!
