### ISSUE TITLE
Delete NLog provider

### ISSUE THREAD

**Issue by Eilon** [aspnet/Logging#341]
It has moved to https://github.com/NLog/NLog.Framework.logging.

**Comment by BrennanConroy** [comment]
79d0820b8685f957151603d935c5cacc2700c4ac

**Comment by marcind** [comment]
You could have at least kept the rc1-final build of the package on nuget.org :(

**Comment by Eilon** [comment]
@marcind can you use https://github.com/NLog/NLog.Framework.logging (though I'm not sure what NuGet feed that is on, if any)? @304NotModified has been working on that.

It was actually a mistake that we ever published the NLog provider we wrote - it was always intended as just a sample to prove out the design of `ILogger`. Of course you could just take the old sample code from here and re-use it...

**Comment by marcind** [comment]
Nah, it's all good. The sudden disappearance of the package broke our automated deployment, but turns out we're not using it anyway.
