### ISSUE TITLE
Proposal: remove code duplication with T4 templates

### ISSUE THREAD

**Issue by 304NotModified** [aspnet/Logging#343]
Code duplication is a source of issues and less code is less bugs.

I see a lot of code duplication in 
[LoggerExtensions.cs (Abstractions)](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs)

That can be easily removed with a T4 template (run at build time). This will ensure that the consistency of the code. 

What do you think? PR accepted on this one?

**Comment by muratg** [comment]
We won't be accepting PRs as we're closing on RC2.  We can possibly consider this post RC2.

**Comment by pakrym** [comment]
T4 templates is a visual studio feature that is not easily supported outside it.

We usually use console apps for code generation (see https://github.com/aspnet/KestrelHttpServer/tree/release/2.2/tools/CodeGenerator) but for now there are no plans of switching LoggerExtensions.cs to use this model.
