### ISSUE TITLE
Close old milestones

### ISSUE THREAD

**Issue by 304NotModified** [aspnet/Logging#344]
I think there are some GitHub milestones that can be closed? (https://github.com/aspnet/Logging/milestones)

e.g. 1.0.0-beta8 and 1.0.0-rc1.

![image](https://cloud.githubusercontent.com/assets/5808377/12498306/def648d4-c0a1-11e5-8111-2d2b28a17e3f.png)

**Comment by muratg** [comment]
Yup, will do

**Comment by Eilon** [comment]
@muratg Backlog, really? :trollface: 

I just closed the old milestones...

**Comment by Eilon** [comment]
Not sure why I forgot to close this issue.
