### ISSUE TITLE
Logger.BeginSope(sParam) should add sParam to output

### ISSUE THREAD

**Issue by DasJott** [aspnet/Logging#347]
When I foudn BeginScope with string as parameter, I immediately thought how cool the idea of scopes is for logging. I thought it would add the given text to every logmessage put out while begin in the scope.

But sadly you have to chance to recognize you are within a scope by looking at the output.

I would expect something like: `NamespaceName.ClassName[0] (ScopeName)`
or anything that makes clear, we are within a scope and in which one.

**Comment by muratg** [comment]
@DasJott The string input could be arbitrarily long though, so making this change would potentially make the output less readable.  I assume you're talking about the ConsoleLogger here.

That being said, you can always have a wrapper ILogger which adds the scope to each log message and call your logger of choice (i.e. ConsoleLogger) and use it via DI, which would help you have the behavior you want.

**Comment by DasJott** [comment]
Thanks, @muratg! Maybe I could simply derive from Logger and implement the behavior I want, yes. I guess I will do that. 
But what sense does that scope thing make if it hasn't any effect?

**Comment by muratg** [comment]
Main reason is you may have a set of logical operations (i.e. in a using statement) that would be best logged together. For example [TraceSource logger scope](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.TraceSource/TraceSourceScope.cs) helps that logger to start (when scope is created) and stop (when scope id disposed) tracing operations.

**Comment by ranjancse26** [comment]
Even I am very upset about this missing thing. The scope is valid from a developer point of view. How would the user understand the scoping without breaking his head :-1: 

For now, I am doing a custom coding

logger.PurchaseOrderScope(LogLevel.Information, "Purchace Order: 00655321")

 public static IDisposable PurchaseOrderScope(this ILogger logger, LogLevel logLevel,
            string purchaseOrder)
        {
            LogMessage(logger, logLevel, purchaseOrder);
            return _purchaseOrderScope(logger, purchaseOrder);
        }

        private static void LogMessage(ILogger logger, LogLevel logLevel, string message)
        {
            switch (logLevel)
            {
                case LogLevel.Critical:
                    logger.LogCritical(message);
                    break;
                case LogLevel.Debug:
                    logger.LogDebug(message);
                    break;
                case LogLevel.Error:
                    logger.LogError(message);
                    break;
                case LogLevel.Information:
                    logger.LogInformation(message);
                    break;
                case LogLevel.None:
                    break;
                case LogLevel.Verbose:
                    logger.LogVerbose(message);
                    break;
                case LogLevel.Warning:
                    logger.LogWarning(message);
                    break;
                default:
                    break;
            }
      }

**Comment by cesarbs** [comment]
@DasJott @ranjancse26 Which logger are you guys using? For the console logger, [you can pass an `includeScopes` parameter](https://github.com/aspnet/Logging/blob/6352e15273fe0b660cc554a284317345db2393d0/src/Microsoft.Extensions.Logging.Console/ConsoleLoggerFactoryExtensions.cs#L53) which will make it print out the scopes.

**Comment by pakrym** [comment]
@cesarbs is correct. Turn IncludeScopes on to see scopes in console logger.
