### ISSUE TITLE
Update Descriptions/Readme

### ISSUE THREAD

**Issue by NickCraver** [aspnet/Logging#349]
I think (*hope*) the intent of this library (especially abstractions) is to be a nice common library for people to use inside and outside of ASPNet Core. I plan on using it that way in our libraries. The intent of scope for use isn't really clear on GitHub though (the only place with more information than the NuGet description). Can this be clarified one way or the other?

Currently the tagline is:
> Common logging abstractions for DNX and ASP.NET 5.

And the Readme says:

> Contains common logging abstractions for ASP.NET 5. Refer to the [wiki](https://github.com/aspnet/Logging/wiki) for more information

> This project is part of ASP.NET 5. You can find samples, documentation and getting started instructions for ASP.NET 5 at the [Home](https://github.com/aspnet/home) repo.

I think it'd help a lot with easing people's trepidation of including such a library outside ASPNet  if these bits were clearer that it's a intended (and possibly supported?) use case.

**Comment by ejsmith** [comment]
Yes, I want to use this for my library as well.

**Comment by Eilon** [comment]
The readme, package descriptions, and other metadata, should all no longer say ASP.NET anywhere at all. (Well, ok, there's still a footer at the bottom of the readme, but it's the standard footer we use everywhere.)
