### ISSUE TITLE
[Discussion] Logging API change

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Logging#350]
Changes from https://github.com/aspnet/Logging/issues/331 see announcement https://github.com/aspnet/Announcements/issues/148

**Comment by cwe1ss** [comment]
> The Log... functions are now in 3 flavors
>
> `Log....(this ILogger logger, EventId eventId, Exception exception, string message, params object[] args);`
> `Log....(this ILogger logger, EventId eventId, string message, params object[] args);`
> `Log....(this ILogger logger, string message, params object[] args);`

Wouldn't it be good to also have `Log....(this ILogger logger, Exception exception, string message, params object[] args);` to support writing Exceptions without an EventId? As far as I understood, those EventIds are optional, right?

**Comment by tuespetre** [comment]
While I can understand the move from `ILogValues` to `IReadOnlyList<KeyValuePair<string,object>>`, I feel that the overloads should have been left in place. `params object[]` can feel very hokey and I would much prefer to define explicit classes that implement `IReadOnlyList<KeyValuePair<string,object>>` to represent the state of logged events.

**Comment by muratg** [comment]
We are closing this issue because this was just an announcement issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
