### ISSUE TITLE
Consider making TraceSourceLogger public

### ISSUE THREAD

**Issue by danroth27** [aspnet/Logging#353]
All of the other ILogger implementations are public, but TraceSourceLogger is internal. Should it be public?

**Comment by muratg** [comment]
@lodejard do you remember why we made this internal?

**Comment by muratg** [comment]
@lodejard :grey_question:

**Comment by Eilon** [comment]
I think the answer to why we did it is obvious :smile:

**Comment by muratg** [comment]
OK, should we even release this particular package then? :)

**Comment by Eilon** [comment]
To clarify my snarky remark: I think it's because we weren't thinking straight :beer: :cocktail:

**Comment by muratg** [comment]
:smirk_cat: 

@BrennanConroy Let's make these public.

**Comment by BrennanConroy** [comment]
da3bc9cc84a642aba89b629f970681b14d188938
