### ISSUE TITLE
Make filtering a first class citizen and remove provider specific filters

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/Logging#369]
There is an ongoing discussion about the noise of log events here: #359 - I created this new issue because it discusses a specific solution - I hope that's ok! I will just provide an overview for people who haven't seen the other conversation.

I strongly believe that this ILogger will be used *a lot* in many libraries and applications in the future. For this reason, being able to filter logs based on their namespace will be a very important topic.
 
Right now, there is no clear recommendation. I read a few times that we should forward everything to another logger (Serilog, log4net, ...) and do the filtering there. However, there are also providers who already provide filtering mechanisms (e.g. ConsoleLogger). 
I'm sure this library will get many more first class providers (Application Insights, DB, ...) in the future, which would remove the need to have a 3rd party logger like Serilog/log4net. However, each provider has to decide about whether and how to implement filtering. This will result in a chaos where each provider must be configured differently or doesn't support filtering at all.

During the discussion in the other thread, @lodejard [created an example FilterLogger](https://github.com/aspnet/Logging/commit/bf2314a9a139ae04fd7310d5df99b0cbe968ae35#diff-459e7bd4d619a1efc2739dff9398cf91R28) which acts as a LoggerFactory-wrapper and can be used like this:

```csharp
/// How to wrap filtering provider around other providers factory
loggerFactory
	.WithFilter(new FilterLoggerSettings
	{
		{ "Microsoft", LogLevel.Warning },
		{ "System", LogLevel.Warning },
		{ "SampleApp.Program", LogLevel.Debug },
	})
	.AddEventLog();
```

I really like this concept and would love to see something like this included as a core concept for v1 because it has many important advantages:
* You could completely remove the provider specific filters from ConsoleLogger etc.
* Writing new providers would be very easy too (which leads to fast adaption)
* Every provider would support this feature automatically
* There would be a consistent API
* There's no cost to it if you don't want to use it.

I'm sure this would remove the need to have another logger (Serilog, ...) for most people! (since providers for most used targets will show up over time)

As an example, here's my real-life scenario:
* Console: We usually don't output anything in Production but we have it running in no-op mode so that we can turn it on in case we need to do some on-server troubshooting (shouldn't happen though :-) ...). In Development, this is the most important provider and we constantly change the levels and namespaces based on our needs.
* We log application startup errors in Production to EventLog in case our persistent store (e.g. Application Insights) isn't available (or didn't initialize correctly). This way we can still have some monitoring for startup crashes. We also have it enabled in Development to make sure it works. Right now we log "Critical" for everything and "Error" for Microsoft.AspNet.Hosting (because [startup errors are not considered critical right now](https://github.com/aspnet/Hosting/issues/612) )
* We use a persistent log store (e.g. Application Insights, Stackify, ...) for our production environment. We log almost everything for our namespace but only "Warning+" for Microsoft. We might have to change the level based on our needs. In Development, we only send a little bit to make sure it works.

**Comment by ejsmith** [comment]
I agree with this as well. It seems like ILoggerFactory should have the ability to set log levels for categories.

**Comment by ejsmith** [comment]
I think this could be as simple as adding 1 method to the ILoggerFactory interface:

`void SetLogLevel(string categoryName, LogLevel minLogLevel);`

**Comment by lodejard** [comment]
+1 for making the provider filter example an actual package. It's also an interesting question if the filtering in the other providers could then rely on it for implementation.

**Comment by ejsmith** [comment]
Hmm... not that I thought about this some more. I think I am against adding filtering. I think these interfaces should just address the needs of applications or libs that want to add logging. So just the ILogger and ILoggerFactory is all that would be needed. Things like log level filtering can live in concrete implementations of these interfaces.

**Comment by cwe1ss** [comment]
@ejsmith this would be in Microsoft.Extensions.Logging or in a completely separate package. Definitely not in the Abstractions package. This functionality would only be needed by actual host applications who configure providers - libraries wouldn't have to worry about this.

**Comment by ejsmith** [comment]
OK, sounds good. :-)

**Comment by muratg** [comment]
@lodejard What kind of design were you thinking here?  Just making [this](https://github.com/aspnet/Logging/commit/bf2314a9a139ae04fd7310d5df99b0cbe968ae35)

cc @Eilon

**Comment by lodejard** [comment]
Yes, that would be about the extent of it. The second question would be if there is overlap between this and the filtering built-in to some of our providers, would those providers use this as an implementation detail. But that's about deduplication and isn't strictly necessary.

**Comment by cwe1ss** [comment]
I have been using Louis' filter project with great success in my project so far. As described in my initial post, we have several different providers (Console, EventLog, SqlServer) and we use Louis implementation together with a `Configuration` provider to read the switches from a file that looks like this:
```json
{
  "Console": {
    "IncludeScopes": true,
    "Switches": {
      "Default": "Trace",
      "Microsoft": "Information"
  },
  "EventLog": {
    "LogName": "MyLog",
    "Switches": {
      "Default": "Warning",
      "Microsoft": "Error"
  }
}
``` 
So we combine the provider specific settings with the filter settings and we don't use any third-party logging system like Serilog, ...

I'm convinced that category-based filtering is a must-have for almost everyone. I don't think that anyone would want to have *all* "DEBUG" logs from *all* loggers in his database when he has to debug an issue. 

So I think the future of this topic really depends on how you see this library. If you want people to always forward events to some other logging systems like Serilog, then not having a centralized filtering logic is fine. However, IMO even if you don't want people to use this library exclusively, this will happen anyway over time - see myself as evidence nr 1 :-)

If you want people to use this library exclusively, then I don't see any reason why any provider would not want to support filtering. So why not solve this problem directly in the core library?

**Comment by cwe1ss** [comment]
To further discuss the actual implementation of Louis, I noticed the following which might be important to discuss: 

Right now, your providers use `ILogger.IsEnabled` to decide whether a log event should be written. As far as I've seen they only look at the provider specific filter settings for this. 
Since filtering happens outside of the ILogger in Louis' code, this method might not be useful anymore.

Do you think that it should be removed if Louis' code would be integrated or do you still see value in it? e.g. providers could check if they are enabled at all, ...

**Comment by kichalla** [comment]
3affa0e59179ffbb02a8b46204c53b61b4ad51f3

**Comment by frankfajardo** [comment]
@cwe1ss I like the idea of reusing the `ILogger.IsEnabled` to enable to provider.
