### ISSUE TITLE
Exceptions aren't logged by EventLogger (dev branch)

### ISSUE THREAD

**Issue by fubar-coder** [aspnet/Logging#375]
It seems that in commit 4528bdbc2816a8b5f933d9c6cf2da806ce4a72ea, the [MessageFormatter](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs#L365) helper function in [LoggerExtensions.cs](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs) was changed to _not_ include the exception. The ConsoleLogger logs the exception by itself, but the EventLogger doesn't.

**Comment by muratg** [comment]
@BrennanConroy could you take a look?

**Comment by BrennanConroy** [comment]
This was an intentional change
@lodejard

**Comment by fubar-coder** [comment]
It was an intentional change that the exception is not included in the event log?

**Comment by lodejard** [comment]
Sure, the Exception.ToString should be added to the body. Might want to have two newlines between the message and the exception for readability.

**Comment by fubar-coder** [comment]
That would cause the ConsoleLogger to output the exception twice - which is not really useful/wanted.

**Comment by muratg** [comment]
@lodejard did you mean EventLogger should be changed to include Exception.ToString()?

**Comment by lodejard** [comment]
Yes

**Comment by fubar-coder** [comment]
Then I misunderstood you. I'm sorry.

**Comment by lodejard** [comment]
No problem, what I wrote could have meant either thing. :)

**Comment by lodejard** [comment]
So we were both right :D

**Comment by BrennanConroy** [comment]
6b07c6ae4aadf3b605d161bc8f6cc36de1619efc
