### ISSUE TITLE
Suggestion for log event levels

### ISSUE THREAD

**Issue by artganify** [aspnet/Logging#377]
Currently, the severity of an application event is defined by `Microsoft.Extensions.Logging.Abstractions.LogLevel`, which specifies a few common log event levels along with their value as integer. Since this is an 'abstraction' assembly, one might expect that the defined log event levels are applicable to every possible implementation of those abstractions. However this is not the case since every logging framework interprets log event levels and severities in a different way. It is very confusing that the severity *Debug* might result in *Trace*, depending on the underlying logging facility.

My suggestion: Turn the `LogLevel` enumeration into a struct containing a 'value' integer (similar to Java enums), allowing to define an arbitary range of log event levels.

    public partial struct LogLevel : IEquatable<LogLevel>, IComparable {

        public int Value { get; }

        public LogLevel(int value) {
            Value = value;
        }

    }

and then (maybe predefined...)

    public static readonly LogLevel Trace = new LogLevel(int.MaxValue);
    public static readonly LogLevel Debug = new LogLevel(int.MaxValue);
    public static readonly LogLevel Information = new LogLevel(10000);
    // etc.

That way, one can define its own log levels (by extending the partial implementation) or define completely new ones. Log levels are mapped to logging providers by range (e.g. in *Serilog*, *Verbose* is lowest, so everything below *10000* maps to *Verbose*).

Worth considering?

**Edit**

I want to add that the concept of 'log levels 'is fairly old and might be outdated. In the 'age' of semantic logging, log levels are nothing more but metadata - so why make it an essential part of the logging facility?

**Comment by Eilon** [comment]
Having completely arbitrary log levels seems like it will make this interface/abstraction be incompatible with almost every logging system out there. A goal of logging is to preserve fidelity as much as reasonably possible. Does anyone really need four billion log levels? It's nearly guaranteed to lose fidelity when logging this data to any real logger. Another problem is that there could be multiple loggers registered with the system (this is entirely common - e.g. ConsoleLogger + Serilog + Debug) - I would hope that they each report/render/display/store/save very similar log levels. Plus, these log levels are just big conceptual buckets. Log level 649825601 and 649825602 seems a bit extreme.

I think the current choice of a handful of extremely common log levels will cover the 99.99% case. If an application needs more fine grained control then it can use other techniques to capture that data, such as using categories, event ids, or structured log data.

**Comment by artganify** [comment]
@Eilon 
> I would hope that they each report/render/display/store/save very similar log levels

This is exactly the issue I wanted to address. With the current implementation, a log rendering of the `Microsoft.Extensions.Logging.LogLevel.Trace` level looks like this:

| Framework | Mapped level |
|-----------|--------------|
| NLog      | Debug        |
| Loggr     | Verbose      |
| Elmah     | Debug        |
| serilog   | Debug        |

The Microsoft.Extensions.Logging package defines '*Trace*' as "*Logs that contain the most detailed messages*", which is equal to '*Verbose*'. However for debug we've got "*Logs that are used for interactive investigation during development.*" Tracing is therefore clearly different from debugging and more 'severe', yet 3 of 4 implementations treat it the other way round. And this is mostly what's going to be rendered within the log outputs. Confusing. isn't it?

The intention of my approach wouldn't be to provide an 'arbitary' amount of log levels or allow to more fine-grain the log severity (yep, it could be a nasty side-effect, tho), but to allow multiple 'log level names' to be mapped to the same severities or close ranges and then implementations could pick the range up that fit's most to the one provided.

After all, and already mentioned, one might argue that it's questionable to have log levels in the abstraction/framework at all. The idea of log levels was just to have a flag that decides: 'Who might be interested in this event?'. With a constant shift towards out-of-process logging, structured logging etc, filters etc., they are just meta-information that can be treated the same way as event ids, categories and other log properties, as you mentioned. :)

Since I don't have a recipe ready to fix the problem of losing fidelity with arbitary log levels (which I strongly agree upon!), this issue can be closed.
