### ISSUE TITLE
Please keep default foreground color, don't override with ConsoleColor.Grey

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/Logging#378]
Please keep default foreground color, don't override with ConsoleColor.Grey
`Microsoft.Extensions.Logging.Console.ConsoleLogger:249`
```cs
 return new ConsoleColors(ConsoleColor.Gray, DefaultConsoleColor);
```
This grey really does not do wonders on default OSX terminals (white background)

**Comment by Eilon** [comment]
Yeah we should set the foreground color only when we set the background color - that's needed to ensure readability. But for all other console writes it should be 100% default.

**Comment by NinoFloris** [comment]
Exactly

**Comment by davidfowl** [comment]
Fix for RC2? This is a pretty bad.

**Comment by Eilon** [comment]
Yes RC2.

**Comment by BrennanConroy** [comment]
So Error, Warning, and Information are now going to be the same color as Debug/Trace?

**Comment by Eilon** [comment]
The place where it renders the log level should have explicit foreground and background colors set. But then it should completely unset all colors and use the console's default foreground/background.

**Comment by BrennanConroy** [comment]
Alright, what background color would we like to have for Error/Warning/Information?

**Comment by Eilon** [comment]
For the "labels" use whatever seems normal :smile: is what it's doing now for those acceptable?

**Comment by BrennanConroy** [comment]
They use the default background color but set the foreground color

**Comment by Eilon** [comment]
Chatted with @BrennanConroy , we're on the same page.

**Comment by BrennanConroy** [comment]
bc8ba8aa66773afaab5a4698ecadf4cd5247c2b7
