### ISSUE TITLE
Shouldn't CreateLogger<T> return ILogger<T>?

### ISSUE THREAD

**Issue by HakanL** [aspnet/Logging#379]
When I call CreateLogger<T> I expected the return type to be ILogger<T> so that I can wire up my classes to expect ILogger<T> in the constructor and call CreateLogger from the LoggerFactory to create the required type.

**Comment by davidfowl** [comment]
It does in RC2 https://github.com/aspnet/Logging/issues/312

**Comment by HakanL** [comment]
Ah, sorry, I didn't see that, I guess I just searched open issues before I posted. Is RC2 coming up on NuGet shortly?

**Comment by davidfowl** [comment]
Nope. The date is still TBD. https://github.com/aspnet/Home/wiki/Roadmap

**Comment by HakanL** [comment]
Got it, thanks!
