### ISSUE TITLE
Fix DebugLogger to log exception details

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Logging#388]
@BrennanConroy recently fixed `EventLogLogger` to log exceptions, but `DebugLogger` didn't get the same love: https://github.com/aspnet/Logging/commit/6b07c6ae4aadf3b605d161bc8f6cc36de1619efc#diff-9bbe2418382dbe1fba6ad79cb1f4a081R104.

That would be great if the debug logger could log exception details: https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Debug/DebugLogger.cs#L75.

/cc @davidfowl

**Comment by muratg** [comment]
@BrennanConroy Could you review the remaining implementations and do the same thing across the board?

**Comment by ORuban** [comment]
Hi, I have created a PR https://github.com/aspnet/Logging/pull/391 using the same way as for EventLogLogger.

And actually I have a question about formatting: 
- in TraceSourceLogger the only one Environment.NewLine is added before exception // [link to code](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.TraceSource/TraceSourceLogger.cs#L38)
- in EventLogLogger (and so in this PR for DebugLogger) there are two Environment.NewLine(s) before exception // [link to code]
(https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.EventLog/EventLogLogger.cs#L104)

So maybe add/remove one Environment.NewLine ?

**Comment by BrennanConroy** [comment]
@loudej You said 2 newlines for EventLogLogger, how about for DebugLogger?

**Comment by BrennanConroy** [comment]
@lodejard 
Whoops, used your other one, see above

**Comment by BrennanConroy** [comment]
9f4dee96995c6a0aa4a239128fd174120ebfe4b8

**Comment by PinpointTownes** [comment]
Thanks! :clap: :clap:
