### ISSUE TITLE
Proposal/feature: Auto-incremented event ids or as reference types

### ISSUE THREAD

**Issue by artganify** [aspnet/Logging#389]
The current `Log` invocation on the main `ILogger` requires an `EventId` which is, in my opinion a pretty useful thing (though it could also be just an optional event property because not every company/product/framework works with event ids in the first place). What I'm worrying about a little is the fact that it's an *id*, meaning an *identifier* and thus should be unique within a certain scope. This however is not the case for some of the extension methods provided by `LoggerExtensions`. For instance `public static void LogDebug(this ILogger logger, string message, params object[] args)` internally calls the API like this:

    logger.Log(LogLevel.Debug, 0, new FormattedLogValues(message, args), null, _messageFormatter);

If I call the extension method twice, it means two application messages will inevitably get the same event id (0).

Suggenstions:

* Make the `EventId` a reference type (still with implicit cast to `int`?) so a `null` value can be provided (Results in: This event has no event id).

* ...or maybe create a static counter where each non-client submitted event id is automatically incremented (e.g. atomic). Though I'm not sure if that would work for the following case:

Example:

     logger.LogDebug(10, "Event id is 10"); // internal counter: 10
     logger.LogDebug("Event id should be 11"); // internal counter 10 + 1
     logger.LogDebug(9, "... and now it's again less than 10?"); // reset counter? or just ignore?

**Comment by muratg** [comment]
`EventId` is a struct that can take be either an int, or a string. `EventId`s can be used to distinguish between different event types/scopes. They are not meant to be unique per log line.

**Comment by Eilon** [comment]
They can't be auto-incrementing because the values, if set, are intended to be *unique per logger category* for the lifetime of the universe (seriously). If they were autogenerated, there would be no guarantee that after an app restarts that the numbers would be the same, which would invalidate all previously recorded logs.
