### ISSUE TITLE
Offer a better way to configure logging for DI scenarios

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Logging#397]
Currently, you have to inject `ILoggerFactory` in your `Configure` method and call `AddDebug`/`AddConsole` to register the listeners you want to add in your application. This is a weird pattern, that clearly differs from all the other stacks, that use `IServiceCollection` extensions for that.

That would be great if we could do something like that:

```csharp
public void ConfigureServices(IServiceCollection services) {
    services.AddLogging(options => {
        options.AddDebug();
        options.AddConsole();
    });
}
```

/cc @davidfowl @muratg

**Comment by herecydev** [comment]
Basically [this](https://github.com/aspnet/Logging/issues/346), no?

**Comment by PinpointTownes** [comment]
Yep, exactly that, thanks! :clap: 
Closing as a duplicate of https://github.com/aspnet/Logging/issues/346.
