### ISSUE TITLE
System.Console Color stuff is crazy expensive

### ISSUE THREAD

**Issue by benaadams** [aspnet/Logging#408]
Is calls System.Console.GetBufferInfo which is 1/3 as expensive as actually writing the messages (which is also relatively expensive)

![](http://aoa.blob.core.windows.net/aspnet/console.png)

![](http://aoa.blob.core.windows.net/aspnet/console2.png)

![](http://aoa.blob.core.windows.net/aspnet/console3.png)

**Comment by Eilon** [comment]
@davidfowl any work here for 1.0.0? Want someone else to investigate?

**Comment by BrennanConroy** [comment]
Should re-measure now that https://github.com/dotnet/corefx/issues/7823 is in.

**Comment by muratg** [comment]
ping @davidfowl. We can assign this to someone else...

**Comment by davidfowl** [comment]
@benaadams do you have new measurements?

**Comment by benaadams** [comment]
Looks like its still an issue, glancing at the top functions in this unrelated issue  https://github.com/aspnet/KestrelHttpServer/issues/1319#issuecomment-274992730

**Comment by pakrym** [comment]
GetBufferInfo can't be avoided when colors have to be set. We now have `DisableColors` mode that makes things much faster.
