### ISSUE TITLE
This repo has no master branch, which breaks links in API reference

### ISSUE THREAD

**Issue by svick** [aspnet/Logging#412]
This repository has no `master` branch, but "View on GitHub" links in API reference link to that branch, which results in broken links.

For example, [the API reference page for `ILogger`](https://docs.asp.net/projects/api/en/latest/autoapi/Microsoft/Extensions/Logging/ILogger/index.html) links to https://github.com/aspnet/logging/blob/master/src/Microsoft.Extensions.Logging.Abstractions/ILogger.cs, which is 404, while the same link, but to the `dev` branch (https://github.com/aspnet/logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/ILogger.cs), is fine.

**Comment by muratg** [comment]
@pranavkm

**Comment by pranavkm** [comment]
Odd we missed this. Created master based on `1.0.0-rc1`

**Comment by muratg** [comment]
Thanks @pranavkm and thanks @svick for reporting this!
