### ISSUE TITLE
Console logger not using colors on windows

### ISSUE THREAD

**Issue by rynowak** [aspnet/Logging#415]
Previously we had the console logger set the color for the label (`info`, `warn`, `fail`, etc). It's not setting the color anymore on windows/powershell.

**Comment by danroth27** [comment]
@BrennanConroy @muratg

**Comment by cesarbs** [comment]
Happens on cmd too.

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/cli/issues/1977

**Comment by cesarbs** [comment]
Should we close this since it's a CLI issue?

**Comment by mikeharder** [comment]
I think we should keep this open until we have verified everything works correctly with new CLI.  We should verify the following scenarios:

1. Coloring works when using `dotnet run`
2. Coloring works when using `dotnet app.dll`
3. Coloring is disabled (no control characters) when redirecting the output of `dotnet run` or `dotnet app.dll` (e.g. to a file)

**Comment by muratg** [comment]
@BrennanConroy Please verify when we have the right CLI

**Comment by BrennanConroy** [comment]
Fixed with the CLI we just grabbed.
