### ISSUE TITLE
Console logger colorizing whole first line on OSX

### ISSUE THREAD

**Issue by rynowak** [aspnet/Logging#416]
Previously we had the console logger set the color for the label (`info`, `warn`, `fail`, etc). It's now setting the color for the whole first line on OSX

**Comment by muratg** [comment]
@BrennanConroy

**Comment by BrennanConroy** [comment]
That's probably because the change is for dev only https://github.com/aspnet/Logging/pull/411

**Comment by BrennanConroy** [comment]
This change was made in RC3 @rynowak was testing RC2
