### ISSUE TITLE
Consider logging exception stack traces

### ISSUE THREAD

**Issue by cesarbs** [aspnet/Logging#421]
Using any of the `Log*` overloads that take an `Exception` as argument only logs the exception type and message.

Consider logging a stack trace for levels `Error` and `Critical` at least. Would be interesting for `Debug` and `Trace` too. Definitely not for `Information` and `Warning`.

**Comment by 304NotModified** [comment]
I think all the log levels should behave the same. So all including stacktrace.

**Comment by cwe1ss** [comment]
Are you talking about a specific provider (eg Console)? As far as I understand, the logger itself takes the whole exception object and forwards it to the providers, so they are free to log as much as they want.

**Comment by NickPolyder** [comment]
Hello. Is this still considered a bug and needs to be solved?
 I'm currently looking for a good point to start contributing to the repo.

**Comment by 304NotModified** [comment]
Hi!

To be honest I don't know what's the proposed change here. 

We could log the exception stacktrace with ${exception}

**Comment by pakrym** [comment]
Console logger already does this, if there is another logger that doesn't please file a new issue.
