### ISSUE TITLE
IsEnabled implementation is inconsistent

### ISSUE THREAD

**Issue by cesarbs** [aspnet/Logging#423]
Part of https://github.com/aspnet/Release/issues/31

This code

    loggerFactory.AddConsole(LogLevel.None);
    loggerFactory.AddDebug(LogLevel.Trace);
    
    var logger = loggerFactory.CreateLogger("MyLogger");
    
    Console.WriteLine(logger.IsEnabled(LogLevel.Trace));
    Console.WriteLine(logger.IsEnabled(LogLevel.Critical));

Prints

    False
    False

But

    loggerFactory.AddConsole(LogLevel.Trace);  // Notice level is swapped here
    loggerFactory.AddDebug(LogLevel.None);
    
    var logger = loggerFactory.CreateLogger("MyLogger");
    
    Console.WriteLine(logger.IsEnabled(LogLevel.Trace));
    Console.WriteLine(logger.IsEnabled(LogLevel.Critical));

Prints

    True
    True

**Comment by cesarbs** [comment]
cc @muratg

**Comment by cesarbs** [comment]
I guess we need to determine whether the expected behavior is about the lowest level supported by all loggers or the highest level supported by at least one logger.

**Comment by kichalla** [comment]
The behavior that you are noticing is by design. The Debug logger also checks if a debugger is attached and is always false in the above scenarios(assuming you did not attach the debugger).  The IsEnabled check looks for at least one logger which can write a log message and in the second case its true with the ConsoleLogger.

**Comment by cesarbs** [comment]
@kichalla Ah, I see. That makes a lot of sense. I'm closing this bug.

**Comment by cesarbs** [comment]
@muratg @Eilon How should I label this since it was not really a bug?

**Comment by muratg** [comment]
Marked as "invalid" :)
