### ISSUE TITLE
Emit a log event rather than just a bunch of values.

### ISSUE THREAD

**Issue by artganify** [aspnet/Logging#425]
## Problem

The current API for performing log operations takes a bunch of values which describe an application event which has occured:

```
void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter);
```

The values passed to the method are probably fine for most scenarios, however I see some issues with this:
- Not everyone agrees with e.g. having an `EventId`, despite being a good practice. Some extension methods of the `LoggerExtensions` respect that, but because the `EventId` is mandatory, they simply pass a _0_ (zero) which ends up in the emitted log event by the various implementations - or not.
- Many people do want event ids. But maybe not as `string` or `integer`, or they just want to have their event ids globally unique, e.g. by using a `Guid` automatically generated by the logging facility.
- A log event should exactly describe what happened, and when it happened. The current contract doesn't allow to e.g. pass a timestamp and no timestamp is being generated by the abstraction framework. It's up to the individual providers to do that. Now imagine one provider takes a little longer to emit a log event - for example when the _Serilog_ provider (first in the provider chain) emits to a custom sink that dispatches the event via a socket and the network is busy for some reason. A following _ConsoleProvider_ might emit the log event several seconds to minutes later, given that events are dispatched sequentially. 

The main issue with the current contract: It's simply not possible to create a single method which contains all possible values to satisfy both, every developer requirement and every provider capabilities. Except maybe this (joke ahead):

```
void Log(DateTimeOffset timestamp, LogLevel logLevel, int corrlationid, EventId eventId, string sourceContext, Category category, IEnumerable<Tags> tags, string message, string messageFormat, object state, Keywords keywords, Exception exception....
```
## Solution

A popular thing many many log frameworks or custom loggers have is a `LogEvent` as an object which mainly contains some metadata about the event and then the rest is payload. This is even a thing in e.g. _ETW_, _SLAB_ (once the 'you should use this!' frameworks by Microsoft itself). So, why not just alter the API the following way:

```
void Log(LogEvent logEvent);
```

True, this would require some mapping by the individual providers if they have their own `LogEvent`, but I think the additional memory to do this is negigible compared to the fact that the current contract actually can cause event information to be missing or wrong, depending on the constellation of providers etc.

So, long story. Worth considering for maybe the final release?

**Comment by davidfowl** [comment]
It's highly unlikely we'll make a change this big to the interface. We could consider adding another one in the future but this would be too much churn at this point. Can't you append more data by using structured  data for TState? See https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/HostingLoggerExtensions.cs for an example of how we do timing and other metadata about the message.

**Comment by artganify** [comment]
@davidfowl I agree that this would be a huge change. I didn't expected this to be present by the RC2 release or even the final one. It's just something I thought about might be worth considering for some later point in the future.

No, unfortunately appending the metadata to the state is not an option. Irregardless of how the individual `LogEvent`s of the various frameworks look like, they all have some 'fixed' payload data, such as the timestamp, the level, maybe exception etc. The `ILogger` contract has this fixed data aswell (log level and exception) - why didn't you guys just made it `Log<TState>(TState state)` in the first place and putting everything inside it? ;) Jk., what I mean by this is that when I'm going to add e.g. a timestamp in the structured data, e.g. creating a property `"Timestamp"`, it's somewhat a magic string the various `ILoggerProviders` have to respect. They already check if the passed state is possibly a `LogEventValues` (which is still somewhat okay since it's type based), but if we're going to start doing this way, I really don't think it's going to end good.

Imagine this (pseudo):

    class CustomProvider : ILoggerProvider
        
        private void ISomeLoggingFramework _actualLogger;
        void Log(LogLevel level, EventId eventId, TState state, (formatter)...) {
            var event = new LogEvent();
            var logEventValues = state as LogEventValues;
            if(state.ContainsKey("Timestamp"))
                event.Timestamp = state["Timestamp"];
            if(state.ContainsKey("Exception"))
                event.Exception = state["Exception"].
            // etc..
        }

Or worse, for example an event like this (in a log viewer):

        ERROR [16:12:22.343] "Database": "Database connection lost":
            Properties:
                ActualTimestamp: 16:11:59.222

**Comment by davidfowl** [comment]
Thanks for expanding on the scenario but we're not going to change the interface at this point.
