### ISSUE TITLE
Make logging enablement simpler in Azure Web Apps

### ISSUE THREAD

**Issue by davidebbo** [aspnet/Logging#429]
Today, when git deploying an app to Azure, you end up with this in `web.config`:

    <aspNetCore processPath="dotnet" arguments=".\AspNetCoreRC2.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />

To enable logging (including streaming), you need to change it to:

    <aspNetCore processPath="dotnet" arguments=".\AspNetCoreRC2.dll" stdoutLogEnabled="true" stdoutLogFile="%home%\LogFiles\dotnetcore" forwardWindowsAuthToken="false" />

But Azure Web App already has an existing mechanism to enable logging, and it would be good to just honor it. It works as follows:

- there is a file called `settings.json` in `%home%\site\diagnostics`
- it contains something like this: `{"AzureDriveEnabled":true,"AzureDriveTraceLevel":"Error"}`
- if `AzureDriveEnabled` is true, it logs to files in `%home%\LogFiles\Application`

**Comment by davidebbo** [comment]
I guess this is already tracked by https://github.com/aspnet/IISIntegration/issues/167, though I probably have more info here.

**Comment by moozzyk** [comment]
This should be in IISIntegration linked to https://github.com/aspnet/IISIntegration/issues/167
