### ISSUE TITLE
Questionable design of ILogger.Log<TState>(..., Func<TState, Exception, string> formatter)

### ISSUE THREAD

**Issue by Mertsch** [aspnet/Logging#442]
If we take a look at https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs

You will notice that the message formatter does absolutely nothing with the given Exception object

```
private static string MessageFormatter(object state, Exception error)
{
    return state.ToString();
}
```

From the whole naming and how it used to be in RC1, I was lead to believe that I have to implement something like `return state + \n + error` (pseudo code) for my message formatter.

Then I was looking at https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs I saw that

```
            var message = formatter(state, exception);
[...]
            if (exception != null)
            {
                // exception message
                exceptionText = exception.ToString();
                printLog = true;
}
[...]
                    if (!string.IsNullOrEmpty(message))
                    {
                        Console.WriteLine(
                            message,
                            DefaultConsoleColor,
                            DefaultConsoleColor);
                    }
                    if (!string.IsNullOrEmpty(exceptionText))
                    {
                        Console.WriteLine(
                            exceptionText,
                            DefaultConsoleColor,
                            DefaultConsoleColor);
}
```

The reason why I think is a design flaw is that the `ILogger` implementation has to _assume_ that the provided `formatter` _does not_ use the exception object to format the `message` or else you will have a duplicated exception message in the total output.

I totally agree with the choice to give the `Exception` object to the `ILogger` in order to be able to log it in a somewhat special way, but then again, how should the `formatter` know that.

A workaround would be to specifically _not_ give `exception` to the `formatter`, but that feels like a hack IMO.

What do you guys think? Should
`ILogger.Log<TState>(..., [NotNull] Func<TState, Exception, string> formatter)` be
`ILogger.Log<TState>(..., [NotNull] Func<TState, string> formatter)`?

**Comment by davidfowl** [comment]
While I agree in principal that it's unfortunate the implementation has to assume this, we're not going to be changing the interface at this point. We're pretty much locked down at this point.

**Comment by Mertsch** [comment]
@davidfowl Thanks for the info. Is going back to letting the `formatter` handle both arguments an option? Wouldn't change the interface, but be more consistent.

**Comment by davidfowl** [comment]
It would probably be better to have the formatter only take a single argument at this point,  that or saying that sinks should ignore it altogether. It's really just a fallback for the cases when the logging provider doesn't know how to handle formatting the object and exception passed in... Maybe we should just pass a null formatter.

**Comment by pakrym** [comment]
Nothing we can do here.
