### ISSUE TITLE
Implement Async Logging

### ISSUE THREAD

**Issue by martinfletcher** [aspnet/Logging#444]
Currently, there is no way to do async logging without doing the following:

await Task.Run(() => logger.LogInformation(.....));

Could async versions of the logger methods be added to support async natively? I understand that you could write your own logger implementation to do logging async, using fire and forget (async void) methods - is this still a bad practice in Asp.Net Core?

**Comment by 304NotModified** [comment]
We were thinking about this, but then you need a `await` for every log statement? Sounds unworkable to me. Also i'm curious why this is better then using the async writing feature. Let me know your thoughts!

**Comment by martinfletcher** [comment]
With aspnet 4.x, using fire and forget is a bad idea as the aspnet runtime does not know about the 'fired and forgotten' method call. Is this still the case with aspnet core?

**Comment by davidfowl** [comment]
Logging should be fast and doesn't need to be async. Your logging sink should be doing the hard work outside of the call to log to avoid the slow down. If your logger doesn't do that then you'll need to make another interface, we're not adding async APIs to the logging interface.

> You can use HostingEnvironment.QueueBackgroundWorkItem for such things, so what is the counterpart in aspnet core if native async calls are not an option?

`Task.Run`, if you're holding onto the http context, bad things will happen but that's unrelated to this question (or repository).

**Comment by martinfletcher** [comment]
So the answer (outside of aspnet) is to use async void for the log writing method in a custom sink?

**Comment by nblumhardt** [comment]
@martinfletcher YMMV, but having the sink write the event to a queue (say, `ConcurrentQueue<T>`) and a background worker pull events from the queue to do the heavy lifting, works well for many Serilog sinks. Jump on the [Serilog Gitter](https://gitter.im/serilog/serilog) if you want any pointers/tales of our experiences doing this in core :+1:

**Comment by 304NotModified** [comment]
Also NLog has async target writing, al built in ;) 

/promotion

**Comment by martinfletcher** [comment]
@nblumhardt - Brilliant, I did not realise that Serilog had support for exactly what I want!

Yeah that makes sense, just took a look at the source code, and I can see what you mean.

Thanks for the help :)

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
