### ISSUE TITLE
How to use FilterLoggerFactory as default ILoggerFactory

### ISSUE THREAD

**Issue by epignosisx** [aspnet/Logging#449]
I would like to use [FilterLoggerFactory](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Filter/Internal/FilterLoggerFactory.cs) as the default **ILoggerFactory**. I see there is a [WithFilter](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Filter/FilterLoggerFactoryExtensions.cs) extension method that returns the **FilterLoggerFactory** but it will not affect the ILoggerFactory registered with DI.

Where is the right place to configure FilterLoggerFactory as the default? I'm thinking it would be with the 
[WebHostBuilder](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs)

```c#
public static void Main(string[] args)
{
    var host = new WebHostBuilder()
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseLoggerFactory(new FilterLoggerFactory(new LoggerFactory(), new FilterLoggerSettings()))
        .UseStartup<Startup>()
        .Build();

    host.Run();
}
```

Also, what's the guidance on directly accessing APIs in that have "Internal" in the namespace? In this case **Microsoft.Extensions.Logging.Filter.Internal.FilterLoggerFactory**.

**Comment by SimonTouchtech** [comment]
You could do 

```csharp
public static void Main(string[] args)
{
    var host = new WebHostBuilder()
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseLoggerFactory(new LoggerFactory().WithFilter(new FilterLoggerSettings()))
        .UseStartup<Startup>()
        .Build();

    host.Run();
}
```

In that way you won't access the "internal" class. An alternative is to do it in ConfigureServices:
```csharp
services.AddSingleton(new LoggerFactory().WithFilter(new FilterLoggerSettings()));
```

I'm personally not a fan of either of these methods. I would prefer either some way to set it up either 

1. In connection to the call to ```services.AddLogging()``` (e.g. ```services.AddLogging().WithFilter(...)``` or ```services.AddLogging(new FilterLoggerSettings())```) 
2. Or in ```Configure(...)```, while adding loggers (i.e. a method on ```ILoggerFactory```). 

The first suggestion is probably the easiest to implement given the current implementation.

**Comment by epignosisx** [comment]
Thanks @SimonTouchtech. I really like the:

```
.UseLoggerFactory(new LoggerFactory().WithFilter(new FilterLoggerSettings()))
```

I think the suggestion:
```
services.AddSingleton(new LoggerFactory().WithFilter(new FilterLoggerSettings()));
```

will not be picked up by the web host since it already created its logger so the filtering will not take effect there.

I'm going to keep the issue open to see if I can get some guidance on the usage of classes in the "Internal" namespace.
