### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by svick** [aspnet/Logging#453]
When I try to build this repository on Windows by running `build.cmd`, I get the following error:

```
dotnet-install: .NET SDK version 1.0.0-preview2-003041 is already installed.
[snip]
info: Run target: initialize
info: Run target: build-compile
info:
info: Exec
info:   program: dotnet
info:   commandline: build  src/*/project.json test/*/project.json samples/*/project.json --configuration Debug
info:   workingdir: E:\Users\Svick\git\aspnet-logging
Specify --help for a list of available options and commands.
Unrecognized command or argument 'test/*/project.json'
fail: Exit code 1 from dotnet
```

The same thing happens when I run `build.ps1` from PowerShell.

**Comment by BrennanConroy** [comment]
Do you have older versions of dotnet in the .dotnet\sdk folder?

**Comment by svick** [comment]
I do: 1.0.0-rc2-002416, 1.0.0-preview2-002996 and 1.0.0-preview2-003041.

And after deleting them, the error does not happen anymore, thanks.

Though shouldn't build.cmd work even when I have installed older versions of the SDK in the past?

**Comment by moozzyk** [comment]
In general you don't want rc2 because it is selected over previewX - https://github.com/dotnet/cli/issues/2959 and weird things happen.

**Comment by svick** [comment]
Since build.cmd installs a specific version of the SDK, would it be possible to use exactly that version?

**Comment by muratg** [comment]
@svick Should be possible, but now we have the official "Preview2" of the tooling, I just recommend using that.
