### ISSUE TITLE
BeginScope<TState>(TState state) feels like there is something incomplete there.

### ISSUE THREAD

**Issue by sandorfr** [aspnet/Logging#454]
I maintain an Azure table logger since beta3, and because this thing is bugging me since then, I never published it.

BegingScope has to be implemented as a generic method, but it has no constraint of any kind. It feels almost pointless. Moreover, builtin loggers are not leveraging it.

My first guess was that is was intended as an easier way to allow us to do some cached code generation. But, from what I observed, it seems like the team committed to states deriving from `IReadOnlyList<KeyValuePair<string, object>>`. In that case add a constraint on TState, it's just an interface so it is easy to implement for anyone willing to provide a custom scope. 

This would make it much easier and useful  when supporting scopes.

**Comment by sandorfr** [comment]
I noticed that entityframework team has done things a bit differently and is not implementing `IReadOnlyList<KeyValuePair<string, object>. So we are back to reflection if we want to support scopes and are not satisfied with what `ToString()` method provides.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
