### ISSUE TITLE
Suppress logging for specific requests (e.g. health checks)

### ISSUE THREAD

**Issue by muratg** [aspnet/Logging#459]
_From @sunsided on July 1, 2016 15:57_

We're using ASP.NET Core with Kestrel dockerized in Google Container Engine. The load balancer performs regular health checks (to a customizable route) which, depending on the configuration, can make the logs somewhat to extremely unreadable. That is, we end up with up to hundreds of log lines per second using the standard console logger (possible machines x replication factor x each line a log entry) - without any useful information.

Currently, each requests generates at least some lines similar to

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:12345/foo/bar/
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1962.8502ms 200 application/json; charset=utf-8
```

While I was able to suppress all other messages by writing a custom middleware, I would like to also suppress these log lines if and only if the request comes from a specific IP subnet and/or has known HTTP headers set.

For requests different from health checks, I do want to see log output though (e.g. from `Microsoft.AspNetCore.Mvc.Internal`, etc.).

_Copied from original issue: aspnet/Hosting#807_

**Comment by muratg** [comment]
@davidfowl Thoughts?

**Comment by davidfowl** [comment]
You'd need to write a custom filter. This can't be done declaratively and is log provider specific...

**Comment by sunsided** [comment]
@davidfowl I can see how I would be able to filter based on `HTTP/1.1 GET http://localhost:12345/foo/bar/`, but how would I be supposed to recognize the message

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1962.8502ms 200 application/json; charset=utf-8
```

as a health check out of all possible log messages from `Microsoft.AspNetCore.Hosting.Internal.WebHost`? Wouldn't it make sense to allow setting log levels (or maybe loggers) per route?

**Comment by muratg** [comment]
Closing this as we're preparing to move this repo over to Extensions.
