### ISSUE TITLE
Application Insights as Provider

### ISSUE THREAD

**Issue by ikourfaln** [aspnet/Logging#463]
Hi,
Im just asking if can we use Application Insights as Provider, I mean using directly Application Insights API to log messages in the cloud.
if it is possible, where can I find an implementation of that ?

Thank you

**Comment by 304NotModified** [comment]
It should work but I never used it. I guess there is more info to find on stackoverflow.com

**Comment by 304NotModified** [comment]
Eg. http://stackoverflow.com/a/23381533

**Comment by ikourfaln** [comment]
Thanx, but I know that there is ways to use Application Insights via other Providers such as NLog and especially Serilog ([Serilog.Sinks.ApplicationInsights](https://github.com/serilog/serilog-sinks-applicationinsights)). But Im looking if we can use Application Insights directly as a provider without using a third-party.

**Comment by 304NotModified** [comment]
Too bad no experience so I don't know. Please ask on Stackoverflow

**Comment by herecydev** [comment]
I've done this by leveraging the `Microsoft.ApplicationInsights.TelemetryClient`. You can send lots of different things to application insights, metrics, events, exceptions, etc.

You might struggle mapping the `LogX` methods on the `ILogger` to the Telemetry client; it's hard to communicate the context. But otherwise it's simple.

**Comment by ikourfaln** [comment]
@herecydev  thanx for comment. So what I understand is that its better to use directly Application Insights API (TelemetryClient) rather than using the Logging service of ASP.NET Core !!

**Comment by herecydev** [comment]
@ikourfaln I guess that's up to you and your team, I think it's nice to have a single `ILogger` and if you can make it work in a clean way for you then that's ideal. But if you find that events and metrics aren't the same as logging strings (they're related but distinct) then I would go for a separate abstraction and use both.

**Comment by ikourfaln** [comment]
@herecydev 
I see, Thank you for clarifying.

**Comment by hishamco** [comment]
@ikourfaln this is a [prototype](https://github.com/hishamco/ApplicationInsightsLogging) that I created, I will create a PR if the idea is voted

**Comment by ikourfaln** [comment]
@hishamco thank you

**Comment by 304NotModified** [comment]
there isn't here we (NLog) should do here, right?

**Comment by hishamco** [comment]
@Eilon I already implement an ApplicationInsightsLoggerProvider is there a plan to support it out of the box or shall I make a PR to Entropy repo?

**Comment by Eilon** [comment]
@DamianEdwards @davidfowl @muratg @pakrym thoughts on this? Do we already have something in the works for our Azure integration efforts?

**Comment by davidfowl** [comment]
We're already doing this as part of the Azure integration work. It's been committed here https://github.com/Microsoft/ApplicationInsights-aspnetcore, it's also much more than a logger provider 😄 but the logging is here:

https://github.com/Microsoft/ApplicationInsights-aspnetcore/tree/develop/src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation

Closing this.

**Comment by DamianEdwards** [comment]
We're currently building this as part of a larger effort to improve our integration with Application Insights. It will ship along witb the Visual Studio 2017 release. The work is happening over in the Application Insights repo.

**Comment by ikourfaln** [comment]
Finally, Thank you guys.

**Comment by hishamco** [comment]
Thanks for the details @davidfowl, coz I already build such provider few weeks ago and I expect that Logging repo is the right place for such LoggerProvider

**Comment by gilmishal** [comment]
I am using the latest version on nuget (1.0.2) of `Microsoft.ApplicationInsights.AspNetCore` and I can't reference `.Logging` and get the LoggingProvider - Is there something I am missing?

**Comment by takekazuomi** [comment]
@davidfowl  ILogging's Application Insight integration is only 'core .NET'. It is not in 'Full. NET'. Is 'Full. NET' scheduled?
I want Common logging abstraction that can be used for both 'core .NET' and 'Full .NET'. Now '.NET Full' is incomplete because there is no Application Insight integration.

**Comment by Eilon** [comment]
**Hi, it looks like you are   posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:

1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem.
