### ISSUE TITLE
Make the WebApps logger configurable

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Logging#470]
Right now, in it's rough implementation, it only accepts a parameter. It should be configurable through the configuration system (options?) and you should be able to set an environment variable to configure the max file size, for example.

cc @pakrym

**Comment by muratg** [comment]
@victorhurdugaci Let's have a look when you're back.

**Comment by victorhurdugaci** [comment]
I think pakrym fixed this...

**Comment by victorhurdugaci** [comment]
@pakrym

**Comment by muratg** [comment]
@pakrym remember fixing this?

**Comment by muratg** [comment]
@pakrym If this isn't already done, we can move this out.

**Comment by pakrym** [comment]
Done as part of https://github.com/aspnet/Logging/pull/477
See https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.AzureAppServices/AzureAppServicesDiagnosticsSettings.cs
