### ISSUE TITLE
Discussion, drop vs block on logger

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Logging#472]
From here: https://github.com/aspnet/Logging/pull/468#issuecomment-236306894 

I would prefer to block instead of dropping message but let's discuss it

**Comment by muratg** [comment]
@victorhurdugaci Let's have a look when you're back.

**Comment by nblumhardt** [comment]
If you head towards the "drop" policy, [Serilog.Sinks.Async](https://github.com/serilog/serilog-sinks-async) implements this in [BackgroundWorkerSink](https://github.com/serilog/serilog-sinks-async/blob/dev/src/Serilog.Sinks.Async/Sinks/Async/BackgroundWorkerSink.cs) which can be applied with:

```csharp
    .WiteTo.Async(a => a.SomeOtherSink())
```

Functionally, this is pretty much identical to the background sink here. Just thought I'd leave a note in case you're able to make use of it, as any feedback would be valuable to us. Cheers!

**Comment by victorhurdugaci** [comment]
Thanks @nblumhardt, I'll take a look at that. Maybe I can replace our background sink completely with that implementation.

**Comment by victorhurdugaci** [comment]
fyi @pakrym

**Comment by muratg** [comment]
Closing this as we're preparing to move this repo over to Extensions.
