### ISSUE TITLE
Move NullLogger out of the .Internal namespace

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Logging#473]
It's public API, not internal API.

/cc @victorhurdugaci

**Comment by cesarbs** [comment]
Should it have it's own package? Seems weird to have it in Logging.Abstractions.

**Comment by pranavkm** [comment]
We have precedent for putting the `Null*` type in the Abstractions package. See https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.Extensions.FileProviders.Abstractions/NullFileProvider.cs

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/Logging/commit/2affd93f72139efbfd8b6f359e357f371903688a
