### ISSUE TITLE
ConfigurationChange test flaky on Win2008

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Logging#474]
@victorhurdugaci 
https://github.com/aspnet/Logging/blob/b7bcb771676e2ff8a7dba73ce4f4260f80bb72f9/test/Microsoft.Extensions.Logging.AzureWebAppDiagnostics.Test/LogConfigurationReaderTests.cs#L120

**Comment by victorhurdugaci** [comment]
Logs link?

**Comment by BrennanConroy** [comment]
http://aspnetci/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=127162#_focus=9727

**Comment by JunTaoLuo** [comment]
Although this affects win2008 consistently, it also seems to fail on win 2012 as well. http://aspnetci/project.html?projectId=XPlat&tab=testDetails&testNameId=-3904181696098395131
