### ISSUE TITLE
IDisposable on ILoggerProvider

### ISSUE THREAD

**Issue by herecydev** [aspnet/Logging#475]
Based on some of the discussions of [this issue](https://github.com/aspnet/Logging/issues/99) why is the `ILoggerProvider` interface marked as IDisposable? I understand there was a need for a "flushing" mechanism before application termination, but why has that become an obligation for the providers?

An example of this would be in the [console logger provider](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Console/ConsoleLoggerProvider.cs#L112) or the [debug logger provider](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Debug/DebugLoggerProvider.cs#L30).

Can this not be implemented similar to the [DI pattern](https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection/ServiceProvider.cs#L172-L175)?

**Comment by muratg** [comment]
This would be a breaking change before 2.0.0, so putting this in Backlog milestone for now.

**Comment by pakrym** [comment]
Removing `IDisposable` from `ILoggerProvider` would be a breaking change without much benefit.
