### ISSUE TITLE
Allow extension of LoggingEventSouce

### ISSUE THREAD

**Issue by yodasad** [aspnet/Logging#484]
Is it possible to implement some extension points in the EventSource logging framework?
For instance, it would be very useful if one can implement its own EventSource class with different name (not just "Microsoft-Extensions-Logging") and pass it to the EventSourceLoggerProvider.

**Comment by muratg** [comment]
@yodasad Can't you wrap/inherit `LoggingEventSource` and change the name in your own implementation already?

**Comment by yodasad** [comment]
You are a genius! It is simple as that...
thnx
