### ISSUE TITLE
Where are loggers registered?

### ISSUE THREAD

**Issue by OzieGamma** [aspnet/Logging#486]
Hi,

I am using ASP.NET Hosting, Kestrel, Logging, IOC and Configuration form my Web Api. I have decided not to use MVC though.

When I try to run a simple App, I get the following error:
```Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Api.Router'.```

My `Configure` method:

```csharp
    public void Configure(
        IApplicationBuilder app, 
        IHostingEnvironment env, 
        ILoggerFactory loggerFactory,
        IApplicationLifetime appLifetime,
        IServiceProvider services)
    {
        loggerFactory.AddSerilog();
        appLifetime.ApplicationStopped.Register(Log.CloseAndFlush);
    
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
    
        app.Run(services.GetRequiredService<Router>().Handler);
    }
```

My Router constructor:

```csharp
    public Router(ILogger logger)
    {
        _logger = logger;
    }
```

I tried simply having `Router` as a parameter to `Configure` but that didn't work either.
I guess I am not registering the loggers. It seems weird to me though that the loggers get automatically registered by MVC

**Comment by davidfowl** [comment]
ILogger isn't a service, ILoggerFactory is a service. You create per category ILoggers from an ILoggerFactory. You can also inject
  
   ILogger<Router>

**Comment by OzieGamma** [comment]
Yes but here: https://docs.asp.net/en/latest/fundamentals/logging.html

It clearly shows you can inject the ILogger directly. What am I doing wrong?

**Comment by davidfowl** [comment]
You're injecting `ILogger` instead of `ILogger<Router>`

**Comment by OzieGamma** [comment]
Ah, Ill try that tomorrow and close the issue if it solves my problem

**Comment by OzieGamma** [comment]
Indeed, that solved it.

Why does ILogger exist if we can't inject it? Seems like it is likely to lead to errors.

**Comment by davidfowl** [comment]
It's part of the logger abstraction to the interface has to exist. Just because you can't object it doesn't mean it shouldn't exist. I already explained it's because you need to create a logger per category. To do that you need to provide a category name...

**Comment by OzieGamma** [comment]
Fair enough I guess. It's a bit confusing though.
