### ISSUE TITLE
RegisterChangeCallback fires only once

### ISSUE THREAD

**Issue by RoboBurned** [aspnet/Logging#487]
I am writing a handler to reconfigure logger on configuration file changes.
I get a reload token and subscribes to the changes. On every change I re-register the handler.
But when I change appsettings.json file in file editor I get only one change event.
```
public Startup(IHostingEnvironment env)
{
	var builder = new ConfigurationBuilder()
		.SetBasePath(env.ContentRootPath)
		.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
		.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);
	Configuration = builder.Build();
	var token = Configuration.GetReloadToken();
	Console.WriteLine("Registering for token {0}", token.GetHashCode());
	token.RegisterChangeCallback(WriteToConsole, token);
}
private void WriteToConsole(object state)
{
	Console.WriteLine("ChangeCallback raised for token {0}", state.GetHashCode());
	var token = Configuration.GetReloadToken();
	Console.WriteLine("Registering for token {0}", token.GetHashCode());
	token.RegisterChangeCallback(WriteToConsole, token);
}
```

Output:
```
Registering for token 7563067
#here I change appsettings.json file
ChangeCallback raised for token 7563067
Registering for token 55993668
# here I am changing the file again and again and nothing happens.
```

**Comment by pranavkm** [comment]
You have to re-register the token as part of the callback. See https://github.com/aspnet/Logging/blob/a63a9d05c1938e50f376e316f47c2a44f6c9851f/src/Microsoft.Extensions.Logging.Console/ConsoleLoggerProvider.cs#L58-L62

**Comment by RoboBurned** [comment]
@pranavkm Hi, Yes, I already found that the token can be used only once. However in callback (WriteToConsole) I get a new token and re-register the callback (see code)

**Comment by pranavkm** [comment]
Oops, missed that bit. This does look ok at first glance.

**Comment by muratg** [comment]
@RoboBurned Shouldn't this bug be filed in aspnet/Configuration repo? Does it have anything to do with Logging?

**Comment by RoboBurned** [comment]
@muratg Agree. It was my mistake to post it here. I was working on logger when encountered this issue and was looking at how Console logger handles this.
Should I close this issue and create another in aspnet/Configuration or it is possible to move it there?

**Comment by muratg** [comment]
This issue was moved to aspnet/Configuration#509

**Comment by muratg** [comment]
@RoboBurned done :)
