### ISSUE TITLE
Thread safety and performance

### ISSUE THREAD

**Issue by roji** [aspnet/Logging#493]
I'm looking into switching Npgsql to use Microsoft.Extensions.Logging (https://github.com/npgsql/npgsql/issues/1184), and I'm a little unclear on some important aspects.

[This MSDN article](https://msdn.microsoft.com/en-us/magazine/mt694089.aspx?f=255&MSPPError=-2147217396) says the following:

> Because the only data in the ILogger instance is determined from the generic type T, you might argue that each class could have a static ILogger that each class’s object could leverage. However, assuming the programming standard of ensuring thread safety for all static members, such an approach would require concurrency control within the ILogger implementation (which isn’t there by default), and likely result in a significant bottleneck as locks are taken and released. For this reason, the recommendation, in fact, is to have an individual ILogger instance for each instance of a class. The result, therefore, is an ILogger property on each class for which you wish to support logging [...].

Now, looking inside LoggerFactory.cs, I see the following code:

``` c#
lock (_sync)
{
    if (!_loggers.TryGetValue(categoryName, out logger))
    {
        logger = new Logger(this, categoryName);
        _loggers[categoryName] = logger;
    }
}
return logger;
```

Unless I'm misunderstanding things, it seems that the same logger instances are returned for the same category, implying that loggers are indeed threadsafe, contrary to what the article suggests. This would make it safe to use the static-logger-per-class pattern, which is widely used in logging packages.

Instantiating a logger for each of my class instances would mean contention on the logger factory lock, which seems unacceptable... At the very least, shouldn't the locking code above be replaced with ConcurrentDictionary (I can submit a PR)?

**Comment by benaadams** [comment]
FormattedLogValues in Microsoft.Extensions.Logging.Abstractions already [takes a dependency on ConcurrentDictionary](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/Internal/FormattedLogValues.cs#L18) so it wouldn't be bringing in an extra dependency that isn't already there.

I assume the comment refers to `ILogger` being implemented by 3rd parties and not guaranteeing thread safety in those implementations?

**Comment by roji** [comment]
@benaadams it seems that any 3rd-party implementation of `ILogger` which isn't thread-safe would crash since LoggerFactory itself returns the same logger instance to different threads (as long as the category is the same). In other words, unless LoggerFactory starts allocating a new logger each time CreateLogger is called, which seems like a pretty bad idea performance-wise, all logger implementations must be thread-safe. If this is the case and CreateLogger returns the same instances, then the article should probably be amended to say that it's OK (even recommended) to hold static loggers.

As a general note, this makes total sense to me... At some point a logging implementation will write to an output (e.g. file, console), and synchronization must happen at that point to avoid writing multiple log messages at the same time. In other words, it's an issue to be handled at the very end of the logging pipeline - just as the message is about to be written - and not at the very beginning, by instructing programmers to avoid static loggers in their classes.

I hope this all makes some sense...

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
