### ISSUE TITLE
Log stream is not working

### ISSUE THREAD

**Issue by troydai** [aspnet/Logging#497]
### Scenario:

1. set up an ASP.NET Core web application with Azure.AppServciesDiagnostics logging provider
2. publish to Azure enable application log to file system and enable application log to file system
3. open log stream

<Error>
the log doesn't show.

### Diagnostics: 
1. through console, if manually create a file under log files folder and add content to it, the content will appear in log stream. that means the azure web site log stream is working.
2. serilog, the file sink used here, may not successfully trigger the azure log stream.

**Comment by pakrym** [comment]
https://github.com/serilog/serilog-sinks-file/issues/18

**Comment by muratg** [comment]
@pakrym good to close?
