### ISSUE TITLE
Default implementation of logger for K

### ISSUE THREAD

**Issue by glennc** [aspnet/Logging#5]
- Console.WriteLine
- OutputDebugString
- ETW

**Comment by davidfowl** [comment]
Closing this out as it's generic and we have most (except OutputdebugString)

**Comment by davidfowl** [comment]
@SajayAntony do you want to help out with the ETW provider?

**Comment by SajayAntony** [comment]
@davidfowl  - @KKhurin might be able to help. Will sync up with him.
