### ISSUE TITLE
Consider adding GetDefaultServices() and AddLogging() to Logging

### ISSUE THREAD

**Issue by divega** [aspnet/Logging#50]
Currently Logging defines and provides default implementation of services, e.g. ILoggerFactory but unlike most other framework components it does not define either a GetDefaultServices([IConfiguration]) method or an AddLogging(this IServiceCollection, [IConfiguration]) sugar extension method. Perhaps the reasoning was been that Logging only needs to be added by Hosting, but making this change would improve consistency and abstraction. It would also be useful for testing and for non-Web application scenarios that don't have Hosting but want to take advantage of these basic services without much friction.

**Comment by davidfowl** [comment]
Added it and we're calling it from hosting.

**Comment by davidfowl** [comment]
@lodejard If you think we need to do something about that, reopen the bug. For now the extension method was moved to the Logging repository.
