### ISSUE TITLE
Microsoft.Extensions.Logging.Abstractions not marked CLSCompliant

### ISSUE THREAD

**Issue by PavelSafronov** [aspnet/Logging#500]
The Microsoft.Extensions.Logging.Abstractions assembly is missing the CLSCompliant(true) attribute. Is there a reason for this, or was this merely an accidental omission?

**Comment by muratg** [comment]
@PavelSafronov do you have a use case to have this attribute in the Logging repo?

**Comment by PavelSafronov** [comment]
The use case is writing a CLS-compliant library which uses or extends Microsoft.Extensions.Logging.Abstractions.

Is there a reason _not to_ have this attribute?

**Comment by gulbanana** [comment]
ran into this today. we may drop clscompliant from our own library but it would be nice to not be forced to make the choice

**Comment by MichaCo** [comment]
@muratg I think it is about consistency most of all. I got asked to add that back to my libraries although it has very little value I think?! But some Microsoft.* or aspnet core packages actually do have that set.

https://github.com/search?p=7&q=org%3Aaspnet+CLSCompliant&type=Code
https://github.com/search?l=C%23&q=org%3Adotnet+CLSCompliant&type=Code

Personal opinion: Wouldn't be too bad if everyone would just drop it, kinda annoying to care about it (in static code analysis) ;)

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
