### ISSUE TITLE
Review EventSourceLogger and get it ready for shipping

### ISSUE THREAD

**Issue by Eilon** [aspnet/Logging#504]
Re-review the code at https://github.com/aspnet/Logging/tree/dev/src/Microsoft.Extensions.Logging.EventSource and get it ready for shipping.

Need to ensure that it:
1. Meets all coding guidelines
2. Has appropriate tests
3. Follows the common pattern for loggers

**Comment by pakrym** [comment]
https://github.com/aspnet/Logging/pull/505
