### ISSUE TITLE
Clean up property behavior and doc comments for AzureAppServicesDiagnosticsSettings

### ISSUE THREAD

**Issue by Eilon** [aspnet/Logging#506]
Some random stuff I noticed:

1. The property setters should throw ArgOutOfRange w/ appropriate message for invalid values
2. `BackgroundQueueSize` has no proper doc comment
3. The non-doc comment comment for `BackgroundQueueSize` has a typo: `Gets of sets ...` --> `Gets or sets ...`
4. Would probably be nice for the doc comments to indicate the actual default values, e.g. `The default value for this property is <c>FOO</c>.` or whatever the right doc comment syntax is.

@muratg we should do this for 1.1.0.

**Comment by Eilon** [comment]
(Or whatever version this thing is.)

**Comment by muratg** [comment]
+ #507 & #508
