### ISSUE TITLE
[BREAKING CHANGE] Parameter type changed on TestLogger

### ISSUE THREAD

**Issue by javiercn** [aspnet/Logging#513]
V1:
`public TestLogger(string name, TestSink sink, bool enabled)`

V2:
`public TestLogger(string name, ITestSink sink, bool enabled)`

https://github.com/aspnet/Logging/blob/1.0.0/src/Microsoft.Extensions.Logging.Testing/TestLogger.cs#L15
https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Testing/TestLogger.cs#L15

**Comment by javiercn** [comment]
@Eilon

**Comment by BrennanConroy** [comment]
This package doesn't ship :)
Some kind of exclusion list we add this to?

**Comment by Eilon** [comment]
Yeah, I think we just need to remove the baseline, then the tool won't run (no baseline, nothing to compare).

**Comment by Eilon** [comment]
@javiercn assigning to you to remove the baseline for this non-shipping package.
