### ISSUE TITLE
[BREAKING CHANGE] Parameter type changed on TestLoggerFactory

### ISSUE THREAD

**Issue by javiercn** [aspnet/Logging#514]
V1:
`public TestLoggerFactory(TestSink sink, bool enabled)`

V2:
`public TestLoggerFactory(ITestSink sink, bool enabled)`

https://github.com/aspnet/Logging/blob/1.0.0/src/Microsoft.Extensions.Logging.Testing/TestLoggerFactory.cs#L13
https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Testing/TestLoggerFactory.cs#L13

**Comment by javiercn** [comment]
@Eilon @muratg

**Comment by Eilon** [comment]
Per https://github.com/aspnet/Logging/issues/513#issuecomment-258593762, it sounds like this doesn't ship, so nothing to fix here.
