### ISSUE TITLE
AzureAppServices extension ignore LogLevel

### ISSUE THREAD

**Issue by sergei66666** [aspnet/Logging#517]
Set Application Loging level (File\Blob) in azure portal to any value except Information. For example Trace.
Restart server and start logging.
```
loggerFactory.AddAzureWebAppDiagnostics();
var logger = loggerFactory.CreateLogger<Startup>();

logger.LogTrace("=====WTF-Trace=====");
logger.LogDebug("=====WTF-Debug=====");
logger.LogInformation("=====WTF-Information=====");
logger.LogWarning("=====WTF-Warning=====");
```

Output is:
[Information] =====WTF-Information=====
[Warning] =====WTF-Warning=====

If change log level in azure without server restart we get right output:
[Trace] =====WTF-Trace=====
[Debug] =====WTF-Debug=====
[Information] =====WTF-Information=====
[Warning] =====WTF-Warning=====

**Comment by sergei66666** [comment]
Found reason.
`WebConfigurationReaderLevelSwitch.MinimumLevel `property, which default value is `Information`.
It updates only after configuration changed.

I suppose, that adding property initialization into constructor should resolve the issue
`MinimumLevel = LogLevelToLogEventLevel(convert(reader.Current));`

**Comment by sergei66666** [comment]
Temporary solution.
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env,
    ILoggerFactory loggerFactory)
{
    loggerFactory.AddDebug();
    loggerFactory.AddAzureWebAppDiagnostics();

    // Crutch :)
    var settingsFolder = Path.Combine(WebAppContext.Default.HomeFolder, "site", "diagnostics");
    var settingsFile = Path.Combine(settingsFolder, "settings.json");
    if (File.Exists(settingsFile))
    {
        File.SetLastWriteTime(settingsFile, DateTime.Now);
    }
    ....
```

**Comment by runxc1** [comment]
I am also running into this issue with the Blob Logging
