### ISSUE TITLE
Add switch to turn off console colors

### ISSUE THREAD

**Issue by glennc** [aspnet/Logging#518]
It should be settable in the default json config file we drop in templates, and we will drop an appsettings.production.json that turns them off so that in production there are no colors by default.

// https://github.com/aspnet/Logging/issues/515

**Comment by BrennanConroy** [comment]
I believe @mikeharder did a quick experiment with removing the colors for #515 and there wasn't a noticeable change for that scenario. This will still be good for async production code though.

**Comment by muratg** [comment]
https://github.com/aspnet/Logging/pull/536 should help with perf issues.

**Comment by glennc** [comment]
Closing this in favor of write-behind logging.
