### ISSUE TITLE
Should we be using LoggerFactory.Create or just let DI create ILogger<T>?

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/Logging#522]
I see both examples in the docs. I don't see why the LoggerFactory.Create is necessary as an extra step. e.g.:

```
  public class Foo
  {
    public Foo(ILoggerFactory logFactory)
    {
      _logger = logFactory.Create<Foo>();
    }
  }
```

Feels like DI handling lifetime of ILogger<T> makes more sense. e.g.:

```
  public class Foo
  {
    public Foo(ILogger<Foo> logger)
    {
      _logger = logger;
    }
  }
```

Advice?

**Comment by stefc** [comment]
From my opinion the second one, because the first one is an anti-pattern, Foo should not know anything about construction. 

I also want to mentioned that it's ok to have the signature Foo(ILogger logger) but construct a ILogger<Foo> from the DI.

**Comment by herecydev** [comment]
There's nothing wrong with the first one. The factory pattern is well established and you may need to use an `ILoggerFactory` for that purpose.

```c#
public class Factory
{
    private readonly ILoggerFactory _loggerFactory;

    public Factory(ILoggerFactory loggerFactory) {
        _loggerFactory = loggerFactory;
    }
    public IPerson GetPerson(PersonType type)
    {
        switch (type)
        {
            case PersonType.Rural:
                return new Villager(loggerFactory.Create<Villager>());
            case PersonType.Urban:
                return new CityPerson(loggerFactory.Create<CityPerson>());
            default:
                throw new NotSupportedException();
        }
    }
}
```

With that said, if you can get away with injecting an ILogger<T> directly then I would do so.

**Comment by shawnwildermuth** [comment]
Sounds like what I had assumed, just wanted to make sure I wasn't missing anything.
