### ISSUE TITLE
LoggerExtensions performance concerns

### ISSUE THREAD

**Issue by strohhut** [aspnet/Logging#523]
Say the log level is warning and I have the following in my code:

```CSharp
_logger.LogInformation("Id is {Id}", myIntId);
```

This creates a params array and a `FormattedLogValues` and boxing from int to object will occur although nothing will be logged.

Wouldn't it make more sense to provide some overloads for typical amounts of arguments like

```CSHarp
public static void LogInformation<T1, T2>(this ILogger logger, string message, T1 arg1, T2 arg2)
{
    if (logger.IsEnabled(LogLevel.Information))
    {
        logger.Log(LogLevel.Information, 0, new FormattedLogValues(message, new object[] { arg1, arg2 }), null, _messageFormatter);
    }
}
```

**Comment by benaadams** [comment]
The zero allocation pattern is demonstrated in [KestrelTrace.cs](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/KestrelTrace.cs)

**Comment by strohhut** [comment]
OK, so there are two extremes. Many allocations with `LoggerExtensions` (what most people will use) or minimal allocations with `LoggerMessage.Define` (which seems a bit hidden and the class name `LoggerMessage` is a bit strange for a delegate factory) that basically requires you to create and store a delegate where you would normally reuse a logger.

What about some faster ILogger extensions?

**Comment by roji** [comment]
+1 on this.

**Comment by MichaCo** [comment]
@benaadams @strohhut I actually didn't know about the `LoggerMessage` factory before Ben mentioned it here ~~ 
I tried that in some tests we are doing currently with per request logging and it was a ~20% performance increase when just logging into the void. Interesting... I agree that the logging framework should either promote that option more and make it more first class, or just do some more fancy things internally to improve the performance per default.

**Comment by muratg** [comment]
Assigning to @BrennanConroy for investigation.

cc @mikeharder

**Comment by BrennanConroy** [comment]
You can also easily avoid unneeded allocations by using
```
if (logger.IsEnabled(LogLevel.Information))
{
    logger.LogInformation(...);
}
```

**Comment by strohhut** [comment]
Yeah, that's obvious. But who wants to do that (three lines for every logging statement)?

**Comment by davidfowl** [comment]
People that want to avoid a performance hit. We do it all over the framework. We also use LoggerMessage. These are all valid options we should document.

What does the "what about some faster ILoggerExtensions" suggestion? Is that something concrete? Do you have ideas ok how to make it better?

**Comment by roji** [comment]
@davidfowl see the original post, simply providing some generic overloads to prevent the allocation of the params array in most cases would help - it's standard practice in both logging packages and other APIs...

**Comment by davidfowl** [comment]
Let me dig up the PR where we decided against this change before. Making the extension methods check is enabled by default makes the peformancd worse when the caller checks as well. That was part of the original push back against doing so.

**Comment by roji** [comment]
Note that there are two separate proposals in the original post:
* Add generic overloads to prevent the params array allocation
* Perform an "is enabled" check immediately inside the method

The two are definitely unrelated, I personally feel the first is much more needed than the second.

**Comment by strohhut** [comment]
@davidfowl You are saying that checking `IsEnabled` is slower than those allocations?

But checking `IsEnabled` happens in the delegates created by `LoggerMessage.Define`. And `LoggerMessage.Define` is used for performance reasons as far as I understand.

**Comment by davidfowl** [comment]
> Add generic overloads to prevent the params array allocation

Performance numbers would definitely help this discussion.

Here's the old PR:

https://github.com/aspnet/Logging/pull/101

> But checking IsEnabled happens in the delegates created by LoggerMessage.Define. And LoggerMessage.Define is used for performance reasons as far as I understand.

The problem with the extension methods that check for you is that ends up being the default. If you want to check IsEnabled yourself, you end up paying that `IsEnabled` cost twice (then you end up having to go out of your way to find the extension method without the `IsEnabled` check)

**Comment by glennc** [comment]
We have a bug on docs to increase our documentation of the other logging patterns: https://github.com/aspnet/Docs/issues/2810

Moving this to the discussion milestone until something we want to actually implement falls out of it.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
