### ISSUE TITLE
LoggerFactory.CreateLogger is blocking after Logger is already created

### ISSUE THREAD

**Issue by joncloud** [aspnet/Logging#524]
It looks like `LoggerFactory.CreateLogger` is a blocking call, but generally doesn't need to be. From how I interpret the code the idea is that data between `CreateLogger` and `AddProvider` should be synchronized, e.g., existing loggers get new providers, and vice-versa new loggers get existing providers.

The flow for `CreateLogger` is to create the logger once and store it (providers get synchronized elsewhere).  Subsequent calls to `CreateLogger` will return the original instance.

```csharp
ILogger<MyController> _logger;
public MyController(ILoggerFactory loggerFactory) {
    _logger = loggerFactory.CreateLogger(nameof(MyController));
}
```

It seems to me like the code in [CreateLogger] could be re-arranged to optimize for the common case where a logger is already created and not block threads using a double-checked locking mechanism.

[CreateLogger]: https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging/LoggerFactory.cs#L28

```csharp
Logger logger;
if (_loggers.TryGetValue(categoryName, out logger))
{
    return logger;
}
lock (_sync)
{
    if (!_loggers.TryGetValue(categoryName, out logger))
    {
        logger = new Logger(this, categoryName);
        _loggers[categoryName] = logger;
    }
}
```

I think the only potential loss here would be that if `LoggerFactory.AddProvider` was called at the same time `LoggerFactory.CreateLogger` was at that point in time the providers could be out of sync.  It is not clear to me though that the original implementation could account for loggers that were already logging (where the CreateLogger call was already made).

I made some basic benchmarking tests using `Parallel.For` to repeat calls, and it seems like at low volumes (<10) of calls it can shave off a couple of milliseconds.  For higher volumes (>1000) it can shave of 10s of miliseconds.

**Comment by BrennanConroy** [comment]
The most common usage pattern for getting a logger is:
```
ILogger<MyController> _logger;
public MyController(ILogger<MyController> logger)
{
    _logger = logger;
}
```

This way `CreateLogger` is called once for this type of `Logger` and the DI system will manage giving this `Logger` type to your controller. This avoids the perf hit from calling `CreateLogger` over and over.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
