### ISSUE TITLE
loggerFactory.WithFilters doesn't work as expected

### ISSUE THREAD

**Issue by MichaCo** [aspnet/Logging#525]
Harsh title, I know, but hey, at least I was surprised and had to look at your code to figure it actually does only create a new FilteredLoggerFactory instance ;)

Given the following code

``` Csharp
            loggerFactory = new LoggerFactory();
            loggerFactory.WithFilter(new FilterLoggerSettings()
            {
                { "Test", LogLevel.Error }
            });
            loggerFactory.AddConsole();
            logger = loggerFactory.CreateLogger("Test");
            logger.LogInformation("Testing stuff...");
```

All looks fine right?
Expected result would be no log message because the filter should filter away the info message.

Unfortunately, `WithFilter` only creates a new logger factory and in case you don't use that one, the messages do not get filtered.

This also applies to use cases where you want to add filtering to in your Startup (Configure) method

``` Csharp
public void Configure(ILoggerFactory loggerFactory, IApplicationBuilder app)
{
    loggerFactory.WithFilter(new FilterLoggerSettings()
    {
        { "Microsoft", LogLevel.Warning }
    });           
```
This also does nothing of course.

This is not really a very critial issue because you can still inject/replace the ILoggerFactory during `ConfigureServices`, but still, it is not very friendly ;)
I guess it would be better if the base logger factory would know about the filters and WithFilters just adds those.

**Comment by justcurious** [comment]
I wouldn't have expected that to work.  What should work is either:

            loggerFactory = new LoggerFactory().WithFilter(new FilterLoggerSettings()
            {
                { "Test", LogLevel.Error }
            });

or 

            loggerFactory = new LoggerFactory();
            loggerFactory = loggerFactory.WithFilter(new FilterLoggerSettings()
            {
                { "Test", LogLevel.Error }
            });

**Comment by MichaCo** [comment]
@justcurious  Yeah, well, that's just, like, your opinion, man.
On a serious note, sure your 2 examples work, but that's not the point

 a) It is not obvious from the API that one call to AddStuff behaves different than WithFilter. In most fluent builders you modify the original or build a new one. But doing both is kinda...
 b) it doesn't work well at all with DI.

**Comment by HaoK** [comment]
@pakrym is this also supposed to be fixed now?

**Comment by MichaCo** [comment]
@HaoK It's just me but from the looks of things with the changes to global filters, yup ;)

**Comment by pakrym** [comment]
We removed old `WithFilter` API. There is only one LoggerFactory now and `AddFilter` appends to it's rules.

**Comment by HaoK** [comment]
Cool, we should close this issue as fixed in preview 2 then :)

**Comment by pakrym** [comment]
Fixed as pard of https://github.com/aspnet/Logging/pull/626 . `AddFilter` now adds a rule to the main logger factory

**Comment by RobertoPrevato** [comment]
Hi @pakrym ,
I know I am commenting on a old thread, but I just installed official Microsoft.Extensions.Logging.Filter package from Microsoft; and it does have `WithFilter` method, it doesn't have `AddFilter`. Wasn't it the same class you were speaking about?

**Comment by pakrym** [comment]
@RobertoPrevato  what version of the package do you have? AddFilter is on LoggerBuilder ( see sample at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x#log-filtering)

**Comment by RobertoPrevato** [comment]
@pakrym, thanks for answering. I installed the latest version [("Microsoft.Extensions.Logging.Filter" Version="1.1.2")](https://www.nuget.org/packages?q=microsoft.extensions.logging.filter). I am actually using this package for a NET Core 2.0 console application, not an ASP.NET application; does that make any difference?
