### ISSUE TITLE
Merge DebugLoggerProvider into Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Logging#531]
We should just merge the debugger logger into the main logging package so it's always available. We could even consider wiring it up by default given it doesn't do anything unless the debugger is attached. Having it be a separate package really seems unnecessary and just adds yet another package to the list of packages add to every default ASP.NET Core project.

**Comment by pakrym** [comment]
@DamianEdwards what about console?

**Comment by muratg** [comment]
@DamianEdwards reopen if you still care
