### ISSUE TITLE
Getting Information messages when set to Warning in Azure

### ISSUE THREAD

**Issue by runxc1** [aspnet/Logging#535]
I have an Azure website that is running on Asp.Net Core 1.1. The site is using the Azure Logging Extensions (see below) to set up logging. On the web application I have been able to turn on the "Application Logging(Blob)" under the Diagnostic logs and have set the level to warning. The only problem is the log file is getting flooded by Information messages. Is this an error in the code or something I haven't set up correctly?

```
 public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseAzureAppServices() // this sets up the Azure logging as well
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
```

**Comment by glennc** [comment]
@runxc1 I don't think you need to do anything more than that for this to work. Is the LogLevel setting making it to the file? IIRC it is in something like `/site/diagnostics/settings.json`. We have tests that check the LogLevel after changing a config file so AFAIK it should work as expected if the settings.json has the right stuff in it.

/cc @pakrym

**Comment by runxc1** [comment]
So the changes to the config file are persisted in /site/diagnostics/settings.json and I had seen some real hacky way that others had gotten it to no longer log all Information level messages but they involved triggering a LogLevel change as it looks like it only picks up the LogLevel if the app is already running and it changes.

I believe that there is already a proposed patch for this.  See
https://github.com/aspnet/AzureIntegration/issues/5

**Comment by glennc** [comment]
Ah, so fixing aspnet/AzureIntegration#5 should fix this then. Closing this one in favor of that bug.
