### ISSUE TITLE
AzureAppServices.Test needs 1.2.0-beta-001259-00

### ISSUE THREAD

**Issue by benaadams** [aspnet/Logging#537]
Build downloads `1.2.0-beta-001251-00` so `AzureAppServices.Test` fails

/cc @pranavkm

**Comment by benaadams** [comment]
See failures in https://github.com/aspnet/Logging/pull/538

**Comment by pranavkm** [comment]
👍 cc @Eilon - this is caused by https://github.com/aspnet/CoreCLR/issues/144. We need to automate this asap

**Comment by pranavkm** [comment]
Should be fixed now - https://github.com/aspnet/KoreBuild/commit/4831105b71846bfc19375094902720a090e5a700. We need to get the automation in place so we don't have to do this manually.

**Comment by benaadams** [comment]
Yep fixed
