### ISSUE TITLE
Remove duplicate TestLogger*

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Logging#540]
There are duplicate TestLogger* types in Microsoft.Extensions.Logging.Testing and Microsoft.Extensions.Logging.Test. They don't seem too different so maybe we can remove the duplication.

cc @BrennanConroy looks like when you moved these types to the testing repo, you didn't remove them from this repo so when @kichalla moved them back to this repo, we now have duplicates.

**Comment by BrennanConroy** [comment]
Fixed in #542
