### ISSUE TITLE
ILogger.BeginScope in async context

### ISSUE THREAD

**Issue by desmondgc** [aspnet/Logging#546]
I'm working on a WCF service that uses a custom security token validation method. There's a fair bit of boilerplate that was duplicated in every "secure" method where we validate the security token and throw an exception if invalid or continue with the operation otherwise. The token contains some relevant state information that I've been trying to add to a the Logger scope.

I had an idea that I could combine the validation logic and Logger scope into a single method and wrap chunks of code in using statements. It works perfectly _except_ that the validation method is async. I've discovered that ILogger.BeginScope doesn't appear to work in an async context. Is this expected?

Example code:

```
private class SecureScope : IDisposable
{
    private IDisposable _loggerScope;

    private bool _isDisposed;

    public SecureScope(IDisposable loggerScope)
    {
        _loggerScope = loggerScope;
    }

    public void Dispose()
    {
        if (!_isDisposed)
        {
            if (_loggerScope != null)
            {
                _loggerScope.Dispose();
            }

            _isDisposed = true;
        }
    }
}
```

```
private async Task<IDisposable> BeginSecureScope(SecurityToken securityToken)
{
    // validate security token
    var validateSecurityTokenResult = await securityTokenValidator.ValidateSecurityToken(securityToken);

    if (validateSecurityTokenResult.ResultCode != ValidateSecurityTokenResultCodes.TokenValid)
    {
        throw new WebFaultException(HttpStatusCode.Forbidden);
    }
    else
    {
        return new SecureScope(_logger.BeginScope(securityToken.MachineKey));
    }
}
```

```
public async Task<Result> DoWork(SecurityToken securityToken)
{
    using (await BeginSecureScope(securityToken))
    {
        _logger.LogInformation("here"); // doesn't include scope!
    }
}
```

If I modify the BeginSecureScope method and remove the async keyword, instead using GetAwaiter().GetResult(), and remove the await in the using statement, everything works perfectly. Why?

**Comment by JunTaoLuo** [comment]
`return Task.FromResult<IDisposable>(new SecureScope(_logger.BeginScope(securityToken.MachineKey)));`?

**Comment by benaadams** [comment]
Does you scope use AsyncLocal? If so its scoped by the await; like it would have been by the using

**Comment by JunTaoLuo** [comment]
There shouldn't be any reason why BeginScope shouldn't work in an async context. We use it in our code base.

@desmondgc let's try isolating the problem. Can you see if the problem still repros if you use a `await Task.Delay()` in `BeginSecureScope` instead of awaiting `ValidateSecurityToken`?

**Comment by davidfowl** [comment]
@desmondgc .NET Core or .NET Framework?

**Comment by desmondgc** [comment]
@JunTaoLuo Task.FromResult shouldn't be necessary in an async method.

@benaadams No AsyncLocal (unless WCF is using it implicitly that I'm not aware of?)

@JunTaoLuo Issue still occurs after replacing the validator call with Task.Delay(0).

@davidfowl  .NET Framework 4.5.2.

I removed the SecureScope class from the equation and now my BeginSecureScope method is just:

```
private async Task<IDisposable> BeginSecureScope(SecurityToken securityToken)
{
    await Task.Delay(0);
    return _logger.BeginScope(securityToken.MachineKey);
}
```

I also added the Console logger (Microsoft.Extensions.Logging.Console) to rule out a problem with Serilog/Seq. Interestingly, the Console logger generates an exception on Dispose:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Extensions.Logging.Console.ConsoleLogScope.DisposableScope.Dispose()
   at Microsoft.Extensions.Logging.Logger.Scope.Dispose()
   at MyService.<DoWork>d__148.MoveNext() in *REDACTED*
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Dispatcher.TaskMethodInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Dispatcher.TaskMethodInvoker.InvokeEnd(Object instance, Object[]& outputs, IAsyncResult result)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeEnd(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage7(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)
```

**Comment by desmondgc** [comment]
If it helps, I have reproduced the issue with this simple console application (using Framework 4.6.1):

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;

namespace ConsoleApplication1
{
    class Program
    {
        private ILogger _logger;

        public Program(ILogger logger)
        {
            _logger = logger;
        }

        public IDisposable BeginScope()
        {
            Task.Delay(0).GetAwaiter().GetResult();
            return _logger.BeginScope("inside BeginScope");
        }

        public async Task<IDisposable> BeginScopeAsync()
        {
            await Task.Delay(0);
            return _logger.BeginScope("inside BeginScopeAsync");
        }

        public void DoWork()
        {
            using (BeginScope())
            {
                _logger.LogDebug("inside DoWork");
            }
        }

        public async Task DoWorkAsync()
        {
            using (await BeginScopeAsync())
            {
                _logger.LogDebug("inside DoWorkAsync");
            }
        }

        static void Main(string[] args)
        {
            var loggerFactory = new LoggerFactory()
                .AddConsole(LogLevel.Debug, includeScopes: true);

            var logger = loggerFactory.CreateLogger(typeof(Program));

            var p = new Program(logger);

            // synchronous method includes scope
            p.DoWork();

            try
            {
                // async method does _not_ include scope (and generates NRE with Console logger)
                p.DoWorkAsync().GetAwaiter().GetResult();
            }
            catch (NullReferenceException ex)
            {
                Console.WriteLine(ex.ToString());
                Console.ReadKey();
            }
        }
    }
}
```

**Comment by benaadams** [comment]
Console logger [uses scopes on async local](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Console/ConsoleLogScope.cs#L28-L60) so they would be gone when the await completes

**Comment by desmondgc** [comment]
[And so does Serilog](https://github.com/serilog/serilog-extensions-logging/blob/dev/src/Serilog.Extensions.Logging/Extensions/Logging/SerilogLoggerProvider.cs#L93-L122), I've discovered. Thanks, @benaadams for pointing me in the right direction.

I guess scope "scoping" is an implementation detail. I found https://github.com/aspnet/Logging/issues/156 which links to a request for the NLog provider.
