### ISSUE TITLE
Add ILogger methods to write templated messages

### ISSUE THREAD

**Issue by lodejard** [aspnet/Logging#55]
```
  _logger.WriteTemplate(
    TraceType.Information, 
    "writing {filename} took {milliseconds}ms", 
    theFileName, theTimeElapsed); 
```

Assuming this would take level, messageTemplate, and params object[] values... Assuming there would be other overloads like InformationTemplate and ErrorTemplate that would call the base one with the enum value. I guess there would be overloads that take an exception also...

The extension method would call the ILogger _logger.Write() with the arguments for `object state, Exception eception, Func<object, Exception, string> formatter`

The state in this case would implement ILoggerStructure, and ILoggerStructure.GetValues() would enumerate the key-value pairs based on {markers} in the template and values in object[].

The formatter in this case would be a callback that downcasts the state object. Assuming the state object is holding onto the information needed to stringify.

**Comment by davidfowl** [comment]
This is done.
