### ISSUE TITLE
Microsoft.Extensions.Logging.AzureAppServices - any plan to support NetCoreApp 1.1?

### ISSUE THREAD

**Issue by kronwell** [aspnet/Logging#553]
I have ASP.NET Core application targeting netcoreapp1.1. When I add nuget package 
```
"Microsoft.Extensions.Logging.AzureAppServices" : "1.0.0"
```
it shows errors that there are dependencies that don't support ``NetCoreApp 1.1``, e.g. ``Microsoft.Data.Edm 5.6.4``

Am I something missing or it is not supported yet? Are there any plans to support it?
Thanks

**Comment by glennc** [comment]
The AzureAppServies logger uses the Azure Storage SDK to log to blob storage. The storage SDK currently has dependencies that do not explicitly support netstandard. You can get them to work using an import in project.json or a packagetargetfallback in csproj. See https://github.com/NuGet/Home/wiki/PackageTargetFallback-(new-design-for-Imports)

IIRC @bleroy was going to be chasing this to work with all the dependencies and get the packages rebuilt to remove this problem. I think it is only OData and its dependencies, the storage package itself is netstandard.

**Comment by glennc** [comment]
Looking at this again it appears that all the dependencies have no been updated, so theoretically we can ship an update of our packages to pull in the newer versions and everything will work. Will look at this now.

**Comment by glennc** [comment]
Ok. If you add a dependency to `WindowsAzure.Storage` version 8.1.0 then that will force the AppServiceIntegration package to use the newer version, removing the error you are getting without adding the TargetFallback or import.

We will look at updating and re-shipping our packages now so that this problem goes away.

**Comment by kronwell** [comment]
@glennc - thanks a lot! I will give it a try.

**Comment by glennc** [comment]
Let me know how you go :).

Created this issue to track updating our dependencies: https://github.com/aspnet/Logging/issues/562

We will do it in 2.0 at a minimum. Not as sure about shipping newer versions of the 1.x package. But we will see. Closing this one, but feel free to keep commenting on it as you work through it.

**Comment by kronwell** [comment]
The workaround is fine. Thanks once more @glennc

**Comment by kroonwijk** [comment]
Another confirmation that adding
 `<PackageReference Include="WindowsAzure.Storage" Version="8.1.0" />`
 works like a charm to workaround this issue.
