### ISSUE TITLE
Using the package in a .NET full framework application

### ISSUE THREAD

**Issue by fleed** [aspnet/Logging#558]
May I use the logger abstractions in a WPF application (obviously based on full .NET framework)?
May I just import the package and use it? I would prefer using a Microsoft-supported abstraction over 3rd party's, and I would like to avoid writing one myself.

Thank you

**Comment by natemcmaster** [comment]
Yes, Microsoft.Extensions.Logging.Abstractions is compatible with .NET Framework. Because it uses .NET Standard, make sure to use the latest [NuGet tooling](https://dist.nuget.org/index.html) for Visual Studio.

**Comment by fleed** [comment]
Good, thank you.
