### ISSUE TITLE
Make maximum log queue size configurable

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Logging#559]
https://github.com/aspnet/Logging/blob/db73396309d4989925486061e0a88997b966ae0a/src/Microsoft.Extensions.Logging.Console/Internal/ConsoleLoggerProcessor.cs#L12

**Comment by muratg** [comment]
@pakrym thoughts for 3.0.0?

**Comment by pakrym** [comment]
I think there is no point in doing it at all. Noone asked for it, console logger is slow and 1024 is plenty.
