### ISSUE TITLE
Information log statements flipping colors on OSX terminal

### ISSUE THREAD

**Issue by suhasj** [aspnet/Logging#56]
On OSX, the first time an Information level message is logged on the terminal, the foreground color is grey and background is white. Subsequent statements colors are switched with foreground color being white and background being black. 

The logging should preserve the color schema of the terminal window between logging statements

**Comment by muratg** [comment]
@BrennanConroy is this still an issue?

**Comment by BrennanConroy** [comment]
Shouldn't be, we use the ascii codes for color now, so it should be a lot more consistent.
