### ISSUE TITLE
Upgrade the WindowsAzure.Storage dependency

### ISSUE THREAD

**Issue by glennc** [aspnet/Logging#562]
We currently depend on 7.2.0 in the AzureAppServices logger. If we update to 8.1.0 we will remove the need for PackageFallbacks to make it work.

**Comment by muratg** [comment]
Related https://github.com/aspnet/Logging/issues/583

Could end up removing this altogether.

**Comment by natemcmaster** [comment]
Close? We upgraded to 8.1 in https://github.com/aspnet/Logging/pull/573. Or should we leave open to track removing this dependency?

**Comment by muratg** [comment]
Yes, closing. #583 tracks removing dependencies.
