### ISSUE TITLE
Add App Service on Linux support to Microsoft.Extensions.Logging.AzureAppServices

### ISSUE THREAD

**Issue by skolmer** [aspnet/Logging#564]
I'm running a dotnetcore 1.1 based api in a docker container on azure. When I activate "Application Logging (Blob)" under "Diagnostics logs" in the azure portal my application crashes with the following exception: 

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: instanceId
   at Microsoft.Extensions.Logging.AzureAppServices.Internal.AzureBlobLoggerProvider..ctor(String outputTemplate, String appName, String instanceId, String fileName, Int32 batchSize, Int32 backgroundQueueSize, TimeSpan period)
   at Microsoft.Extensions.Logging.AzureAppServices.Internal.AzureAppServicesDiagnosticsLoggerProvider..ctor(WebAppContext context, AzureAppServicesDiagnosticsSettings settings)
   at Microsoft.Extensions.Logging.AzureAppServicesLoggerFactoryExtensions.AddAzureWebAppDiagnostics(ILoggerFactory factory, AzureAppServicesDiagnosticsSettings settings)

```
I'm using the Microsoft.Extensions.Logging.AzureAppServices 1.0.0 package from nuget.
Are azure App Services on Linux already supported by Microsoft.Extensions.Logging.AzureAppServices?

**Comment by skolmer** [comment]
It looks like HOME and WEBSITE_INSTANCE_ID environment variables for App Services on Linux are not set correctly. 
In my dotnet core app HOME is set to /root and WEBSITE_INSTANCE_ID is undefined but the azure logging middleware requires this data:
https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.AzureAppServices/Internal/WebAppContext.cs#L21

**Comment by pakrym** [comment]
`Microsoft.Extensions.Logging.AzureAppServices` is not supported on linux right now

**Comment by davidfowl** [comment]
@davidebbo do you know why these values are null on linux?

**Comment by davidebbo** [comment]
@nickwalkmsft it seems like a bug if `WEBSITE_INSTANCE_ID` is not set on Linux.

**Comment by nickwalkmsft** [comment]
Yes, I'll track this on the App Service on Linux side. I dont't think any change should be needed to this library but I'll check.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Comment by nickwalkmsft** [comment]
FYI for anyone following this, we are tracking this internally from the App Service side.

We now set $WEBSITE_INSTANCE_ID correctly on Linux apps, but the handling of $HOME is still an open issue.
