### ISSUE TITLE
Configuration and Filtering changes

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Logging#565]
- [x] Add `void AddProvider(string providerName, ILoggerProvider provider)` to `LoggerFactory`
- [x] `LoggerFactory(IConfiguration config)` will be the way to add configuration to our factory
- [x] Support named providers
    - [x] Check `typeof(type).FullName`
    - [x] Name passed into `AddProvider` wins always
- [x] Example format:
```json
{
  "Logging": { // default values unless otherwise specified
    "LogLevel": {
        "System": "Trace"
    },
    "Console": {
        "LogLevel": {
          "Microsoft.Extensions": "Warning"
        }
    },
    "CustomProvider": { // e.g. factory.AddProvider("CustomProvider", new MyCustomProvider())
      "LogLevel": {
        "System": "Information"
      }
    }
  }
}
```
~~- [ ] Remove ability to call `AddProvider` whenever you want, only allowed during startup~~
- [x] Obsolete `AddConsole(this ILoggerFactory factory, IConfiguration configuration)`

Figure this out:
- [x] Obsolete `void AddProvider(ILoggerProvider provider)` on `ILoggerFactory`

Stretch goal:
- [x] Add `AddFilter(string providerName, Func<string, LogLevel, bool> filter)` to `LoggerFactory`
    - [x] `AddFilter` is additive

**Comment by cwe1ss** [comment]
Will you react to changes in the underlying configuration system? 

My desired scenario: Configuration is loaded from an external system like Consul. I want to be able to change the logging configuration in-flight without having to restart the application.

**Comment by BrennanConroy** [comment]
Yeah, we will handle config changes at runtime.
