### ISSUE TITLE
Move NullLoggerFactory to Microsoft.Extensions.Logging.Abstractions

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Logging#566]
From https://github.com/aspnet/DataProtection/pull/203#discussion_r104220371

We currently have `NullLogger` and `NullLoggerProvider` in Logging.Abstractions but `NullLoggerFactory` is in Logging.Testing. It should be moved to Logging.Abstractions so it can be used in other places like the one referenced above.

@Eilon

**Comment by Eilon** [comment]
@muratg @davidfowl @DamianEdwards - any objections? This seems like good cleanup because we have a mess of NullLoggerXyz's scattered around.

**Comment by davidfowl** [comment]
👍
