### ISSUE TITLE
Lttng Support

### ISSUE THREAD

**Issue by maverickeye** [aspnet/Logging#572]
Does Microsoft.Extensions.Logging.EventSource emit Lttng on Linux?

**Comment by DamianEdwards** [comment]
Yes, see https://github.com/dotnet/coreclr/blob/master/Documentation/coding-guidelines/cross-platform-performance-and-eventing.md for the original spec on this.

Note this functionality is provided by .NET Core itself, rather than Microsoft.Extensions.Logging.

@vancem

**Comment by DamianEdwards** [comment]
Better links:
- https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md
- https://blogs.msdn.microsoft.com/vancem/2016/10/07/collecting-performance-data-on-linux-using-perfcollect-and-perfview/

**Comment by maverickeye** [comment]
Yes, I have read that doc, I was assuming that was all proposed, is anyone using LTTng in place of ETW on Linux side?

**Comment by DamianEdwards** [comment]
@brianrob

**Comment by maverickeye** [comment]
we are using (eventsource) - Etw on Windows side to emit our logging telemetry for windows. Now we are building docker apps on Linux using NetCore, So if we use System.Diagnostics.Tracing.EventSource then telemetry will be LTTng when the platform is Linux and ETW when Windows?

**Comment by DamianEdwards** [comment]
That's my understanding, yes. @brianrob can answer more definitively.

**Comment by brianrob** [comment]
@maverickeye, LTTng support for EventSource is implemented on .NET Core.  Thus, your EventSource events should automatically light up on Linux.  See https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md for instructions on collection.  Note that the level of filtering that exists on Windows does not Linux, so all EventSource events come through one LTTng tracepoint with a JSON payload, which you can then parse.  There are some COMPlus variables to help with filtering, and we're working to make this better.

**Comment by maverickeye** [comment]
Awesome, thank you @brianrob  & @DamianEdwards.
