### ISSUE TITLE
the file name is ILoggerOfT.cs but Interface name is ILogger<T>

### ISSUE THREAD

**Issue by amdnaji** [aspnet/Logging#582]
Hi.
My question seems a little bit silly but when I was exploring Microsoft.Extensions.Logging.Abstractions i found the **ILoggerOfT.cs** file when i clicked on it the actual class name was **ILogger<out TCategoryName> : ILogger**. My problem is with the naming of the file and the class name.Is this OK to have file name different than class or Interface name!
Br,

**Comment by davidfowl** [comment]
We do it rarely, and this is one of the cases. Another alternative would be ILogger`1 but that looks silly :smile:

**Comment by amdnaji** [comment]
Agree with you.
All the best.
