### ISSUE TITLE
Microsoft.Extensions.Logging.AzureAppServices not compatible with Web.API template of asp.net core web application project

### ISSUE THREAD

**Issue by will-beta** [aspnet/Logging#584]
error info：Package Microsoft.Data.OData 5.6.4 is not compatible with netcoreapp ...

**Comment by BrennanConroy** [comment]
Could you try adding
```
<PackageTargetFallback>$(PackageTargetFallback);portable-net40+sl5+win8+wp8+wpa81;portable-net45+win8+wp8+wpa81</PackageTargetFallback>
```
to your csproj under `<TargetFramework>`

**Comment by will-beta** [comment]
@BrennanConroy it works! Thank you!

wondering if the logging DEV buddies would make the adding automatically ^_^

**Comment by glennc** [comment]
This will go away once we update the dependencies of the package, so 2.0 and upwards.
