### ISSUE TITLE
Update dependencies of AppServices logger

### ISSUE THREAD

**Issue by glennc** [aspnet/Logging#593]
I didn't see an issue for this, we need to make sure that we update the storage dependencies of the app services logger. once we do we will not need the PackageTargetFallbacks anymore. I thought we had logged this, but couldn't find it.

@muratg

**Comment by BrennanConroy** [comment]
I think this has been done, Azure Storage is 8.1.1

**Comment by muratg** [comment]
@pakrym?

**Comment by muratg** [comment]
@pakrym has another work item for trimming comments.

**Comment by pakrym** [comment]
@glennc we updated past package version that required `PackageTargetFallbacks` not sure we want to update everything to latest anymore because this is light up package and we talked about keeping dependencies as low as possible. Thoughts?

**Comment by pakrym** [comment]
https://github.com/aspnet/Logging/pull/647
