### ISSUE TITLE
NullLoggerFactory and friends are in the wrong namespace

### ISSUE THREAD

**Issue by rynowak** [aspnet/Logging#594]
All of these types are in the `Microsoft.Extensions.Logging.Abstractions` - whereas the types that they implement are in `Microsoft.Extensions.Logging`.

See: https://github.com/aspnet/Logging/issues/566 - I don't see any discussion of the namespace in this issue or the PR which leads me to believe it's not intentional.

**Comment by muratg** [comment]
cc @ajaybhargavb @Eilon @davidfowl

**Comment by Eilon** [comment]
I think we did see this while @ajaybhargavb was doing all the NullLoggerXyz cleanup, but perhaps it was too big of a breaking change? I don't recall exactly...

**Comment by ajaybhargavb** [comment]
I don't remember what exactly but some of these types were used in repos that only needed to depend on  `Microsoft.Extensions.Logging.Abstractions`.

**Comment by davidfowl** [comment]
We should fix it.

**Comment by rynowak** [comment]
> I don't remember what exactly but some of these types were used in repos that only needed to depend on Microsoft.Extensions.Logging.Abstractions.

The issue I'm raising here is that the namespace is wrong.

**Comment by Eilon** [comment]
@ajaybhargavb can you compare what was shipped in 1.1.x to what we have in 2.0-dev?

**Comment by muratg** [comment]
Assigned to @ajaybhargavb for investigation.

**Comment by ajaybhargavb** [comment]
![image](https://cloud.githubusercontent.com/assets/1579269/25298283/7be99304-26a8-11e7-9890-32d16de94190.png)

From the comparison, the namespace `NullLoggerFactory` is in is consistent with `NullLogger` and `NullLoggerProvider` from rel/1.1.2.

Do we want to change all of those to `Microsoft.Extensions.Logging`?

**Comment by muratg** [comment]
@ajaybhargavb will this fit in preview1?  If so please bring this back to 2.0.0-preview1 milestone. Thanks.

**Comment by ajaybhargavb** [comment]
I'll see how many repos will need the update. But first, are we okay with this breaking change?

**Comment by Eilon** [comment]
Talked with @muratg and @ajaybhargavb and given that this would be an annoying breaking for almost no value, so closing it.
