### ISSUE TITLE
Investigate perf for filtering

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Logging#595]
For example Noop on empty filter here https://github.com/aspnet/Logging/blob/4c83c25e08fa58ef537386fb3dffeb1a8e53ef34/src/Microsoft.Extensions.Logging/Logger.cs#L56
and cache values here
https://github.com/aspnet/Logging/blob/4c83c25e08fa58ef537386fb3dffeb1a8e53ef34/src/Microsoft.Extensions.Logging/LoggerFactory.cs#L426

Also, as part of this add Microbenchmarks

**Comment by pakrym** [comment]
I looked into this as part of https://github.com/aspnet/Logging/pull/917.
Filtering performance is acceptable and benchmarks are added.
