### ISSUE TITLE
I miss an Abstract.NullLoggerFactory

### ISSUE THREAD

**Issue by vpenades** [aspnet/Logging#602]
in Abstractions namespace there's Null* implementations of ILogger and ILoggerProvider, but there's nothing for ILoggerFactory.

In some scenarios, I would like to have a null implementation, specially to ensure that there's a valid fallback value for ILoggerFactory and prevent it to be null.

it should be something like this:

```
class NullLoggerFactory : ILoggerFactory
        {
            public void AddProvider(ILoggerProvider provider) { }

            public ILogger CreateLogger(string categoryName)
            {
                return NullLoggerProvider.Instance.CreateLogger(categoryName);
            }

            public void Dispose() { }
        }
```

**Comment by BrennanConroy** [comment]
You mean the `NullLoggerFactory` here? https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/NullLoggerFactory.cs

**Comment by vpenades** [comment]
yes :)
