### ISSUE TITLE
Clarify the semantics of EventId and possibly override Equals, etc.

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/Logging#607]
The API of EventId makes it look like the name is optional--i.e. I can create one with just an int. But if I do this, should it be considered the same as an EventId created with the same int but also a name?

If these are supposed to represent the same event, then shouldn't Equals, etc. be implemented on the type? if they are not, then can this be documented on the class to make it clear that the name, while being optional, is significant in the semantics of the type?

**Comment by Eilon** [comment]
Hmm I actually don't know what the semantics of this are. I know that if you have *only* ids, they must be unique. That was the original design (the concept of event-id, and thus a name, was introduced later).

But with names I have no idea. Is (id, name) supposed to be unique, or is name just extra data?

**Comment by Eilon** [comment]
cc @davidfowl @DamianEdwards @muratg - any idea what was intended here?

**Comment by muratg** [comment]
> I can create one with just an int. But if I do this, should it be considered the same as an EventId created with the same int but also a name?

IIRC, we didn't talk about this while discussing the design of EventID... @davidfowl do you remember? Either way, I think we'll need to doc whatever behavior we want to go with.

**Comment by Eilon** [comment]
cc @davidfowl @DamianEdwards - pingo-pongo please.

**Comment by muratg** [comment]
@DamianEdwards @davidfowl more pingo-pongo please?

**Comment by muratg** [comment]
Part of the work would be adding doc comments to `EventId` (#610)

**Comment by muratg** [comment]
I don't think we are doing this anymore. If I'm wrong, please pingo-pongo.
