### ISSUE TITLE
Wrap factory instead of adding provider for AzureAppServices

### ISSUE THREAD

**Issue by glennc** [aspnet/Logging#613]
Theoretically if we do something like wrap the ILoggerFactory, like EF does, then we can have the AzureAppServices logger lightup even when the user has replaced the factory with something else. We should consider this and decide if we want to do it.

**Comment by muratg** [comment]
@glennc do you want this in 2.1?

**Comment by muratg** [comment]
Doesn't seem to be much interest at the moment. Backlogging this for now.
