### ISSUE TITLE
AddConsole/AddDebug during DI configuration

### ISSUE THREAD

**Issue by crhairr** [aspnet/Logging#614]
I'm working with the latest bits, and I started getting this error today:

ConsoleLoggerExtensions.AddConsole(ILoggerFactory, IConfiguration)' is obsolete: 'This method is obsolete and will be removed in a future version. The recommended alternative is to call the Microsoft.Extensions.Logging.AddConsole() extension method on the Microsoft.Extensions.Logging.LoggerFactory instance.

This is not DI-friendly, as there appears to be no current/obvious way to achieve this during service configuration. Adding an optional Action<LoggerFactory> configuration callback to the AddLogging IServiceCollection extension method could help with this problem.

**Comment by BrennanConroy** [comment]
Yeah, sorry haven't posted an announcement yet. So what you'll want to do is use `ConfigureLogging` on the `WebHostBuilder` to set up providers and such. See https://github.com/aspnet/SignalR/blob/dev/samples/ChatSample/Program.cs#L15

**Comment by crhairr** [comment]
Fantastic! That's what I was looking for. Thanks for the quick response!
