### ISSUE TITLE
Discussion: Breaking Logging changes and new additions

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Logging#615]
The is the discussion issue for the announcement aspnet/Announcements#238.

**Comment by epignosisx** [comment]
In the old way of configuring logging, we could add to the Configure method additional services registered in DI that our logging provider would need. How can we achieve the same in the new style?

Fox example, in my app, I use Serilog, and I had a custom Enricher: WebEnricher, that would take care of logging of additional data like querystring. For that, I was injecting the HttpContextAccessor in the Configure method and then constructing the WebEnricher with it.

**Comment by epignosisx** [comment]
@BrennanConroy don't want to look pushy, but can you take a look at my comment above? Just trying to understand if we are losing use cases with the new approach.

**Comment by mgrishkov** [comment]
What's about non-web-hosted application? How should I use extension ConfigureLogging out of IWebHostBuilder?

**Comment by davidfowl** [comment]
> What's about non-web-hosted application? How should I use extension ConfigureLogging out of IWebHostBuilder?

How does this change affect that? If you're in a non hosted web application who is creating the concrete `LoggerFactory` instance?

**Comment by davidfowl** [comment]
@epignosisx That scenario is genuinely broken and it's something we're going to look at fixing for preview2. The only work around I can think of right now would be to downcase ILoggerFactory to LoggerFactory and call AddProvider the same way you did before (but more hackily). Or by suppressing the deprecated warning.

We have plans to better integrate logging with DI when running in ASP.NET Core.

**Comment by mgrishkov** [comment]
My code:

```
Configuration = new ConfigurationBuilder()
    .SetBasePath(Directory.GetCurrentDirectory())
    .AddJsonFile("appsettings.json", false, true)
    .Build();
....
Services = new ServiceCollection();
....
ServiceProvider = Services
                .BuildServiceProvider();
....
LoggerFactory = ServiceProvider.GetService<ILoggerFactory>();
LoggerFactory
    .AddDebug(LogLevel.Trace);
```

**Comment by davidfowl** [comment]
You're missing something there who added the ILoggerFactory to the container?

**Comment by mgrishkov** [comment]
Sorry. I use this code:
```
Services.AddLogging()
                .AddOptions();
```
I've fixed my code sample.

**Comment by cwe1ss** [comment]
@mgrishkov You would just do the following instead:
```csharp
// Create your own logger factory
LoggerFactory loggerFactory = new LoggerFactory();
loggerFactory.AddDebug(LogLevel.Trace);

Services = new ServiceCollection();
Services
    // Add your own logger factory to DI
    .AddSingleton<ILoggerFactory>(loggerFactory)
    .AddLogging() // This adds the remaining interfaces (e.g. ILogger)
    .AddOptions();
....
ServiceProvider = Services.BuildServiceProvider();
```
@davidfowl This is a good example for why I thought https://github.com/aspnet/Logging/pull/501 would have been nice. I think it's much more important now that people have to work with the concrete `LoggerFactory` type more often.

**Comment by mgrishkov** [comment]
Ok, thank you I'll check it.

**Comment by epignosisx** [comment]
Thanks @davidfowl. I'll keep eye for preview 2.

**Comment by davidfowl** [comment]
>Thanks @davidfowl. I'll keep eye for preview 2. Is this issue being tracked? Should I open an issue for better visibility?

Open an issue.

**Comment by teaquack** [comment]
Does this actually work for anyone? It doesn't work for me and I can't find examples where this works. My code:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, LoggerFactory loggerFactory)
        {
            loggerFactory.AddFilter(new Dictionary<string, LogLevel>
            {
                { "Microsoft", LogLevel.Warning },
                { "System", LogLevel.Error }
            });
            loggerFactory.AddConsole();
            ...
        }
```

```
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                            .ConfigureLogging(loggerFactory =>
                            {
                                loggerFactory.AddConsole();
                                loggerFactory.AddDebug();
                            })
                            .UseKestrel()
                            .UseIISIntegration()
                            .UseStartup<Program>()
                            .Build();
            host.Run();
        }
```

Both ".AddDebug" and ".AddFilter" throw error 
message: ''ILoggerFactory' does not contain a definition for 'AddDebug' and no extension method 'AddDebug' accepting a first argument of type 'ILoggerFactory' could be found (are you missing a using directive or an assembly reference?) [MyApi]'
message: ''LoggerFactory' does not contain a definition for 'AddFilter' and no extension method 'AddFilter' accepting a first argument of type 'LoggerFactory' could be found (are you missing a using directive or an assembly reference?) [MyApi]'

I tried switching between ILoggerFactory and LoggerFactory to no avail.
How can I make ".AddDebug()" work?

**Comment by BrennanConroy** [comment]
Closing this discussion as it has been superseded by https://github.com/aspnet/Announcements/issues/255. Take a look there and see if you can solve your issue.
