### ISSUE TITLE
Obsolete APIs in 3.0.0

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Logging#616]
Since we obsoleted some APIs in `2.0.0` we can delete them in `3.0.0`
See https://github.com/aspnet/Logging/pull/605 for original obsolete APIs

**Comment by muratg** [comment]
Since we decided not to obsolete the APIs in 2.0.0, we'll obsolete them in 3.0.0 and delete them in 4.0.0.

**Comment by ajcvickers** [comment]
@muratg @Eilon pragmas were added in a lot of places due to these obsoletions. I just checked EF and there are still there, so I suspect they are also still in other places. Do we have a plan to rectify that? Do we know all the places pragmas were added?

**Comment by muratg** [comment]
@ajcvickers I think so. @pakrym removed the obsolete attributes since it made a few things really hard, so I think we should remove the pragmas.

@Eilon, @pakrym, thoughts?

**Comment by Eilon** [comment]
Yes we need to remove the pragmas.

**Comment by ajcvickers** [comment]
My question was more along the lines of do we know where all the pragmas are, or even what repos they are in? Or does someone have to go through and search manually?

**Comment by Eilon** [comment]
Whoever added the pragmas should delete them 😄 Probably not too hard to look at all the commits from @BrennanConroy in a certain date range to see what was changed initially?

**Comment by pakrym** [comment]
Continued in https://github.com/aspnet/Logging/issues/879
