### ISSUE TITLE
Distributing LoggerFactoryExtensions and LoggerExtensions as source files

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Logging#62]
As `ILoggerFactory` and `ILogger` are both assembly neutral, I really don't need **Microsoft.Framework.Logging** library most of the time. I may need **Microsoft.Framework.Logging.Interfaces** if I'm outside of *aspnet50* and *aspnetcore50*.

However, **Microsoft.Framework.Logging** library contains really useful extension methods for `ILoggerFactory` and `ILogger`. I'd love to see these extension methods to be distributed as source files and internal extension methods. This way, I wouldn't need to have `Microsoft.Framework.Logging` library.

**Comment by davidfowl** [comment]
Don't need this anymore since we've nuked assembly neutral. You can use the Logging.Interfaces package without any dependency on an implementation though
