### ISSUE TITLE
Provide way to have DI services participate in the logger configuration (broken with 2.0 changes)

### ISSUE THREAD

**Issue by epignosisx** [aspnet/Logging#620]
Following the [announcement](https://github.com/aspnet/Announcements/issues/238) about the breaking changes in logging for 2.0, I noticed that we were losing the ability to add logging providers in ```Startup.Configure```. I posted the question in the [discussion](https://github.com/aspnet/Logging/issues/615#issuecomment-299353184) issue and it was later [confirmed](https://github.com/aspnet/Logging/issues/615#issuecomment-300416185) by @davidfowl.

Before I was able to configure serilog as such:

```cs
public void Configure(ILoggerFactory factory, IHttpContextAccessor httpContextAccessor)
{
    var logger = new Serilog.LoggerConfiguration()
        .WriteTo.RollingFile("log-{Date}.txt")
        .Enrich.With(new WebEnricher(httpContextAccessor))
        .CreateLogger();

    factory.AddSerilog(logger);
}
```

Note how the ```WebEnricher``` depends on the ```IHttpContextAccessor```. With the new style of configuring logging, we do not have access to DI.

**Comment by pakrym** [comment]
Fixed via https://github.com/aspnet/Logging/issues/626 
You can now inject services into `ILoggerProvider`
