### ISSUE TITLE
Advance notification of breaking changes in 2.0

### ISSUE THREAD

**Issue by nblumhardt** [aspnet/Logging#621]
Hello everyone!

With some design discussion obviously taking place around the 2.0 version of this library, would it be possible to get some early warnings when changes might impact the Serilog provider (and possibly for other popular providers)?

I.e., is there a test suite for this repository that checks existing providers for compatibility, and if so, could someone raise an issue on https://github.com/serilog/serilog-extensions-logging when something breaks?

We've got a basic test suite, and the Serilog contributors are keen to stay on top of any required changes, but testing on `dev` and/or each new preview creates quite a bit of busy work that we can't always keep up with.

(I am not sure what the anticipated scope of breaking changes might be; if you're intending not to break existing providers that would be great - it's just not clear from the threads I've followed so far.)

All the best,
Nick

**Comment by BrennanConroy** [comment]
For the recent `preview1` changes we purposefully didn't break any existing scenarios. When recompiling you may get warnings about obsolete APIs, and you can choose to ignore these until they get deleted (3.0.0 release) or update at your own pace.

**Comment by nblumhardt** [comment]
Hey Brennan, thanks for the reply. I'll work on the assumption that breaking changes affecting Serilog aren't currently planned for 2.0, which is great (we'll have an eye out for any issue reports, of course).

Cheers,
Nick
