### ISSUE TITLE
Logger refactoring

### ISSUE THREAD

**Issue by glennc** [aspnet/Logging#623]
@pakrym is spiking it now, we hope to resolve some of the deficiencies in preview1.

Impacted issues:
https://github.com/aspnet/Logging/issues/620
https://github.com/aspnet/Logging/issues/618
https://github.com/aspnet/Logging/issues/613

https://github.com/aspnet/Logging/issues/534
https://github.com/aspnet/Logging/issues/525

**Comment by cwe1ss** [comment]
Also related: https://github.com/aspnet/Hosting/issues/1071 

Looking forward to see what you come up with! 👍

**Comment by glennc** [comment]
We have an idea, but we decided it would be easier to discuss with code rather than write it all up first. Our backup plan is to just revert everything and go back to the way it was :).

**Comment by DamianEdwards** [comment]
@pakrym this is done now too?
