### ISSUE TITLE
Logger obsolete warnings are not helpful.

### ISSUE THREAD

**Issue by MicahZoltu** [aspnet/Logging#624]
If you try to add loggers the old-fashioned way you are alerted of a deprecation warning:
> [Obsolete("This method is obsolete and will be removed in a future version. The recommended alternative is to call the Microsoft.Extensions.Logging.AddConsole() extension method on the Microsoft.Extensions.Logging.LoggerFactory instance.")]

However, that deprecation warning is on the extension method:
`Microsoft.Extensions.Logging.AddConsole(this ILoggerFactory)` where `Microsoft.Extensions.Logging.LoggeryFactory` implements `ILoggerFactory`.

The `Obsolete` message appears to be self referential to the casual observer with the only difference being _really_ subtle.  After a bunch of googling I was able to figure out the new way to log but I think the obsolete message should be more useful, perhaps indicating that you now must configure logging via `ConfigureLogging` extension method on `WebHostBuilder`.

**Comment by solvingJ** [comment]
I ran into an equally unclear scenario trying to use the following overload:

`public static ILoggerFactory AddConsole(this ILoggerFactory factory, LogLevel minLevel)`

It's a very recent change, so I understand if the docs just need time to update, however I could find no clear example of how to simply AddConsole() while providing the log level. 

I ultimately achieved it with the code below.  I'm not convinced I this is the most elegant way to do it, if there's a better way please advise.  Obviously, running everything through filters is more flexible and perhaps maintainable, but without lots of samples and documentation, the below is much less intuitive and clean for the simple case.  Also, to get the same effect I had to parameterize the category to satisfy the API which is fundamentally new, more work, and unnecessary in my case.  If there's a way to wildcard the category or set to "All", that would be helpful.  

```
            Log = new LoggerFactory().AddFilter(new Dictionary<string, LogLevel>
                {
                    { logCategory , logLevel },
                })
                .AddConsole()
                .CreateLogger(GetType().Name);
```

**Comment by MicahZoltu** [comment]
My solution was (Kestrel app, in Main function):
```
new WebHostBuilder()
	.ConfigureLogging((context, factory) =>
	{
		factory.AddFilter(new Dictionary<String, LogLevel> { ["Default"] = LogLevel.Trace });
		factory.AddConsole();
	})
	...
	.Build()
	.Run();
```

**Comment by KalibGao** [comment]
@MicahZoltu  Yeah, the way you provider does work. I wanna a better way to use it when deploying into production  without change any code.  Could any one have some tips ?

**Comment by MicahZoltu** [comment]
`AddFilter` takes in an `IConfiguration` I believe, you can use whatever configuration mechanism you won't that way.  I just opted for hard coded config for my tiny project.

**Comment by muratg** [comment]
We removed the obsolete warning in 2.0.0, and plan to bring them back in 3.0.0.
