### ISSUE TITLE
Add LogTime Extension Method to Log Duration

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Logging#625]
It is common to want to log the duration, start and end time for running a piece of code. This is typically done using a stopwatch. It would be nice if we could do:

```
using (logger.LogTime(LogLevel.Information, 0, "Message"))
{
    // A long running piece of code e.g. DB/HTTP call etc.
    await Task.Delay(1000);
}
```

The extension methods to support this could look like this:

```
public static IDisposable LogTime(
    this ILogger logger,
    LogLevel logLevel,
    string message,
    params object[] args);

public static IDisposable LogTime(
    this ILogger logger,
    LogLevel logLevel,
    Exception exception,
    string message,
    params object[] args);

public static IDisposable LogTime(
    this ILogger logger,
    LogLevel logLevel,
    EventId eventId,
    string message,
    params object[] args);

public static IDisposable LogTime(
    this ILogger logger,
    LogLevel logLevel,
    EventId eventId,
    Exception exception,
    string message,
    params object[] args);
```

Implimentation is fairly trivial, in fact you already do something similar in your unit tests [here](https://github.com/aspnet/Logging/blob/321761301bf6319d42b054e9ba33b4bc74525f92/src/Microsoft.Extensions.Logging.Testing/AssemblyTestLog.cs#L35-L52).

**Comment by herecydev** [comment]
Use this all the time for tracking 3rd party dependencies/database times. I think it could be added fairly harmlessly but not sure how structured logging would work with it, unless it's always Nth parameter.

**Comment by muratg** [comment]
It's easy to write an extension to do this, so I'm hesitant to make it a part of public API.

@glennc @DamianEdwards, thoughts?  Do we want to do this?

**Comment by pakrym** [comment]
Closing, this can be easily done as an extension method.
