### ISSUE TITLE
LibLog

### ISSUE THREAD

**Issue by johnkors** [aspnet/Logging#63]
Is this project inspired by LibLog? :)

https://github.com/damianh/LibLog

**Comment by damianh** [comment]
Well now... I _do_ remember that logging discussion I was involved in on one of the katana calls where [this was discussed](https://github.com/ayende/ravendb/tree/master/Raven.Abstractions/Logging) (`LibLog` was previously known as `DH.Logging`)

Suffice to say, they have a (weak) shared ancestry :wink:
