### ISSUE TITLE
Microsoft.Extensions.Logging depends on Microsoft.Extensions.Configuration

### ISSUE THREAD

**Issue by MaxDeg** [aspnet/Logging#630]
Microsoft.Extensions.Logging depends on nuget Microsoft.Extensions.Configuration instead of Microsoft.Extensions.Configuration.Abstractions.

As Logging only use interface defined in Configuration.Abstractions it should reference this nuget. 
Isn't it much better for coupling to depend on Abstractions nuget only?

**Comment by DamianEdwards** [comment]
We intend to fix this in the following way:
- Remove dependency on `Microsoft.Extensions.Configuration` from `Microsoft.Extension.Logging`
- Add a new package `Microsoft.Extensions.Logging.Configuration` and move the configuration-dependent logging APIs & integration to it (it would depend on `Microsoft.Extensions.Logging.Configuration` or `Microsoft.Extensions.Logging.Configuration.Abstractions` as appropriate
- Update `Microsoft.AspNetCore` to depend on `Microsoft.Extensions.Logging.Configuration` and call the logging->configuration integration API to bring it all together.

**Comment by muratg** [comment]
@pakrym Good to close?
