### ISSUE TITLE
ConsoleLogger truncating last few lines

### ISSUE THREAD

**Issue by JeremyTCD** [aspnet/Logging#638]
## Issue
ConsoleLogger sometimes truncates latter parts of logs
## Cause
I think the issue may be related to the addition of `_outputTask.Wait(1500)` to `ConsoleLoggerProcessor.Dispose()`:
```csharp
// ConsoleLoggerProcessor.cs
public void Dispose()
{
    _messageQueue.CompleteAdding();

    try
    {
        _outputTask.Wait(1500); // with timeout in-case Console is locked by user input
    }
    catch (TaskCanceledException) { }
    catch (AggregateException ex) when (ex.InnerExceptions.Count == 1 && ex.InnerExceptions[0] is 
    TaskCanceledException) { }
}
```
If a queue takes longer than 1500ms to clear, logs will be truncated.
## Reproduction
[Repo](https://github.com/JeremyTCD/ConsoleLoggerOutput/tree/master). This is a simple reproduction of the issue. To use, build the solution and debug OutputCapturer. Debug output will reflect that some messages from OutputGenerator get truncated. 
## Additional Notes
I think it would be a good idea to guarantee that all log messages are always written (like before Console.WriteLine was moved out of the critical path). Otherwise, additional documentation to warn that logs may be truncated in certain scenarios should probably be added.

**Comment by muratg** [comment]
@JeremyTCD this is by design. Would you like a way to configure 1500 ms wait?

**Comment by JeremyTCD** [comment]
@muratg Thanks for replying. I understand that it is by design and have found workarounds for my own use cases. If this isn't an issue for anyone else I don't think configurable wait duration is necessary. Kindly close this issue if that is the case.
