### ISSUE TITLE
Consider moving IncludeScopes inside the provider-specific-config

### ISSUE THREAD

**Issue by rynowak** [aspnet/Logging#642]
Didn't see this discussed here https://github.com/aspnet/Logging/issues/565

Originally `IncludeScopes` was at the top level because we didn't have provider-specific configuration for levels. Now that we do, it might make more sense to move it next to `LogLevel` so you can turn it on and off for different providers.

Also `IncludeScopes` isn't really a 'global' setting, it's something that our providers implement. So it makes sense to belong to the provider node.

**Proposed**
```
{
  "Logging": {
    "Debug": {
      "IncludeScopes": false,
      "LogLevel": {
        "Default": "Debug",
        "System": "Information",
        "Microsoft": "Information"
      }
    },
    "Console": {
      "IncludeScopes": true,
      "LogLevel": {
        "Default": "Debug",
        "System": "Information",
        "Microsoft": "Information"
      }
    }
  }
}

```

**Current**
```
{
  "Logging": {
    "IncludeScopes": true,
    "Debug": {
      "LogLevel": {
        "Default": "Debug",
        "System": "Information",
        "Microsoft": "Information"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Debug",
        "System": "Information",
        "Microsoft": "Information"
      }
    }
  }
}

```

**Comment by muratg** [comment]
@pakrym claims that this is fixed
