### ISSUE TITLE
IncludeScopes in config doesn't work in the template

### ISSUE THREAD

**Issue by rynowak** [aspnet/Logging#643]
The `WebHost` configuration of the console logger doesn't hook up the configuration to the console logger's settings https://github.com/aspnet/MetaPackages/blob/dev/src/Microsoft.AspNetCore/WebHost.cs#L183

This means that `IncludeScopes` in configuration will be ignored.

**Comment by pakrym** [comment]
Done in https://github.com/aspnet/Logging/pull/706, `IncludeScopes` options is moved to `Console` section under `Logging`
