### ISSUE TITLE
IncludeScopes doesn't work with ConsoleLoggerOptions

### ISSUE THREAD

**Issue by rynowak** [aspnet/Logging#644]
When a logger is created it will be created using the value of `IncludeScopes` from `_settings.IncludeScopes`  https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Console/ConsoleLoggerProvider.cs#L107

The problem is that `_settings` will neither be initialized nor update when using `ConsoleLoggerOptions`.

The result of this is that when the options value changes it will update all **existing** `ConsoleLogger`s, but new `ConsoleLogger`s will be created with the default value of `false`.

**Comment by pakrym** [comment]
Fixed by https://github.com/aspnet/Logging/pull/666
