### ISSUE TITLE
It's too hard to unconfigure default logging

### ISSUE THREAD

**Issue by rynowak** [aspnet/Logging#648]
Imagine using `WebHost.CreateDefaultBuilder` but wanting to replace the default console logger with the serilog console logger.

You have to do something like:
```
var providers = b.Services.Where(d => d.ServiceType == typeof(ILoggerProvider)).ToArray();
foreach (var provider in providers)
{
    b.Services.Remove(provider);
}
```

This is pretty gross and non-obvious. Getting rid of `CreateDefaultBuilder` makes you fall off of a complexity cliff the other way.

**Comment by moozzyk** [comment]
Also see: https://github.com/aspnet/MetaPackages/issues/162

**Comment by pakrym** [comment]
Fixed by https://github.com/aspnet/Logging/pull/659

There is `ClearProviders` extension method on `ILoggerBuilder` now.
