### ISSUE TITLE
ILoggerFactory.AddConsole() needs a LogLevel overload

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Logging#65]
The AddConsole method currently has the following overloads:
```
public static ILoggerFactory AddConsole(this ILoggerFactory factory); // Defaults to Information
public static ILoggerFactory AddConsole(this ILoggerFactory factory, Func<string, LogLevel, bool> filter);
```

If I want to enable verbose then it looks like this:
`factory.AddConsole((s, l) => true);`

This would be much clearer:
factory.AddConsole(LogLevel.Verbose);

**Comment by Praburaj** [comment]
This is fixed.
