### ISSUE TITLE
Consider implementing ILoggerFactory on ILoggerBuilder

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Logging#669]
I order to bridge the gap between older extension methods on ILoggerFactory and ILoggerBuilder, consider implementing the interface. CreateLogger of course would just throw `NotSupportedException`.

/cc @glennc @pakrym

**Comment by pakrym** [comment]
There are some issues:
1. If we try to return `LoggingBuilder` (class) from `AddLogging` while implementing both `ILoggerFactory` and `ILoggerBuilder` we get ambiguous method error for extension methods with same arguments (AddConsole for example, where we want to use `IOptions` for DI mode but keep legacy overloads too).
2. Old style logger extension methods return `ILoggerProvider` which breaks chaining if we inherit `ILoggerBuilder`  from`ILoggerFactory` or implement both on `LoggingBuilder`.

**Comment by pakrym** [comment]
I doubt we would do this.
