### ISSUE TITLE
Add the ability to flow log scope manually

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Logging#67]
Today when you call ILogger.CreateScope the scope is tracked using the thread context until you dispose it.  There are several places where the thread context does not naturally flow and needs to be updated manually (TaskCompletionSource.TrySetResult, Task.Run, Task.Factory.StartNew, etc.).

WebListener is the worst example so far. We want to have it establish a scope around the lifetime of a request, but there are a few explicit thread hops before the request enters the application pipeline. Figure out how to flow the context across those hops. See:
https://github.com/aspnet/WebListener/blob/dev/src/Microsoft.Net.Http.Server/AsyncAcceptContext.cs#L98
https://github.com/aspnet/WebListener/blob/dev/src/Microsoft.AspNet.Server.WebListener/MessagePump.cs#L139

**Comment by muratg** [comment]
@Tratcher let's sync up on this cc @kichalla
