### ISSUE TITLE
Support scopes in all providers

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/Logging#674]
The following providers currently don't support scopes:

* [AzureAppServices->BatchingLogger](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.AzureAppServices/Internal/BatchingLogger.cs#L22)
* [DebugLogger](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Debug/DebugLogger.cs#L40)
* [EventLogLogger](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.EventLog/EventLogLogger.cs#L66)
* [TestLogger](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Testing/TestLogger.cs) (also important to test scope behavior)
* [Application Insights](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLogger.cs#L35) (external, but from Microsoft)

IMO scopes are a very important part of logs and should be supported (at least optional) in every provider. 

I'm wondering if this missing support is just due to lack of time or if supporting scopes is too complex right now?!

Is there something that could be done to make it easier for providers to support scopes? E.g. could there be a default AsyncLocal implementation (like [ConsoleLogScope](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Console/ConsoleLogScope.cs)) in the `Microsoft.Extensions.Logging.Abstractions` package that providers could just use?

PS: Is it even required, that every provider has to do this on its own? Isn't this something that could be hidden completely from providers? `Microsoft.Extensions.Logging` could handle the scopes and just pass the calculated scope to the Log-method of the provider. (This would probably require a breaking change though)

**Comment by pakrym** [comment]
Yes, we are going to provide a base class with scope support and use it in our loggers.

**Comment by muratg** [comment]
Planned work tracked here: https://github.com/aspnet/Logging/issues/682.
