### ISSUE TITLE
Can't get full exception info when exception has InnerException

### ISSUE THREAD

**Issue by fs7744** [aspnet/Logging#675]
Diagnostics use [LogError Method](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs#L308) in [Here](https://github.com/fs7744/Diagnostics/blob/62cc1bd80bc9eeaf78189f68936f58e5e98c5239/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerMiddleware.cs#L48)

The default [MessageFormatter](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs#L462) in LoggerExtensions will ignore Exception , only keep user's message 

So if a exception has InnerException, the Diagnostics will not handle InnerException
And Diagnostics think InnerException should be handle by logger

I confused with this, if logger get message and Exception both, should log them both ?
And if message has Exception.Message in it, the info will be redundant ?

The Diagnostics discussion is in  https://github.com/aspnet/Diagnostics/pull/402

**Comment by davidfowl** [comment]
> Diagnostics use LogError Method in Here
> The default MessageFormatter in LoggerExtensions will ignore Exception , only keep user's message

Here's some background https://github.com/aspnet/Logging/issues/442. It's an unfortunate design flaw of logging. Ultimately, the formatter should be ignored in most cases as reasonable loggers will use the exception argument passed in. 

> So if a exception has InnerException, the Diagnostics will not handle InnerException
And Diagnostics think InnerException should be handle by logger

I'm confused by this. What do you mean it will not handle the inner exception? The logger is passed the entire exception object. Were you using a logging that doesn't print out the exception details?

**Comment by fs7744** [comment]
@davidfowl Thanks a lot.
Before read [#442](https://github.com/aspnet/Logging/issues/442), I didn't know that. 
I write a custom logger .
The Diagnostics 's code for log is this : 
```
_logger.LogError(0, ex, "An unhandled exception has occurred: " + ex.Message);
``` 
So i just log info from MessageFormatter 
After read #442, i will handle MessageFormatter and exception both
Although it will log redundant info for ex.Message
