### ISSUE TITLE
How to get scopes in an exception handler that sits outside of the using-block?

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/Logging#677]
I'd like to get the original scopes in my exception handler as they usually contain important information for troubleshooting (e.g. the UserId). I've [read about a trick/hack](https://nblumhardt.com/2016/11/ilogger-beginscope/#comment-3012254418) that uses C# exception filters to execute the logging statement within the context of the location that throws the exception. Thanks to @nblumhardt and @skomis-mm for pointing this out.

However, it seems like this only works as long as there is no `TaskAwaiter` involved:

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        new WebHostBuilder()
            .UseKestrel()
            .UseContentRoot(Directory.GetCurrentDirectory())
            .ConfigureLogging(logging =>
            {
                logging.AddConsole(options => options.IncludeScopes = true);
                logging.AddFilter("Microsoft", LogLevel.Warning);
            })
            .Configure(app =>
            {
                var logger = app.ApplicationServices.GetRequiredService<ILogger<Program>>();

                app.Map("/sync", subApp =>
                {
                    // Exception handler
                    subApp.Use(async (context, next) =>
                    {
                        try
                        {
                            await next();
                        }
                        catch (Exception ex) when (LogError(logger, ex))
                        {
                        }
                    });
                    // Logic
                    subApp.Run((context) =>
                    {
                        using (logger.BeginScope("UserId:100"))
                        {
                            throw new InvalidOperationException("Something went wrong");
                        }
                    });
                });

                app.Map("/async", subApp =>
                {
                    // Exception handler
                    subApp.Use(async (context, next) =>
                    {
                        try
                        {
                            await next();
                        }
                        catch (Exception ex) when (LogError(logger, ex))
                        {
                        }
                    });
                    // Logic
                    subApp.Run(async (context) =>
                    {
                        using (logger.BeginScope("UserId:100"))
                        {
                            await Task.Delay(100); // Force TaskAwaiter
                            throw new InvalidOperationException("Something went wrong");
                        }
                    });
                });
            })
            .Build()
            .Run();
    }

    public static bool LogError(ILogger logger, Exception ex)
    {
        logger.LogError(ex, "Unhandled exception");
        return true;
    }
}
```

A request to "/sync" outputs the "UserId:100" scope for the "LogError"-call:
```
fail: HostingLogging.Program[0]
      => ConnectionId:0HL6NFB0MJHO8 => RequestId:0HL6NFB0MJHO8:00000001 RequestPath: => UserId:100
      Unhandled exception
System.InvalidOperationException: Something went wrong
   at HostingLogging.Program.<>c__DisplayClass0_0.<Main>b__5(HttpContext context) in C:\src\tmp\HostingLogging\Program.cs:line 51
   at HostingLogging.Program.<>c__DisplayClass0_0.<<Main>b__4>d.MoveNext() in C:\src\tmp\HostingLogging\Program.cs:line 40
```
A request to "/async" does NOT output the "UserId:100" scope for the "LogError"-call:
```
fail: HostingLogging.Program[0]
      => ConnectionId:0HL6NFB0MJHO8 => RequestId:0HL6NFB0MJHO8:00000002 RequestPath:
      Unhandled exception
System.InvalidOperationException: Something went wrong
   at HostingLogging.Program.<>c__DisplayClass0_0.<<Main>b__8>d.MoveNext() in C:\src\tmp\HostingLogging\Program.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HostingLogging.Program.<>c__DisplayClass0_0.<<Main>b__7>d.MoveNext() in C:\src\tmp\HostingLogging\Program.cs:line 63
```
As this feels like a hack anyway, I guess there's no way to get the scopes in async-scenarios, right?

I know that I could catch exceptions within each scope but this isn't really an option IMO as this would result in multiple log entries (one for each scope).

Are there any alternatives for what I want or would it be worth discussing possible solutions?

**Comment by cwe1ss** [comment]
Any update on this? Are people not using scopes or do they just don't care about them not popping up in error logs?

**Comment by aidansteele** [comment]
@cwe1ss I've been thinking about this since I saw your thread a few weeks ago and it occurred to me why we're seeing this behaviour. Methods marked `async` get rewritten by the compiler and part of the rewritten code is wrapping the entire body of the `async` method in ` try { ... } catch { ... }`.

You can see the behaviour here: https://sharplab.io/#v2:CYLg1APgAgDABFAjAbgLAChYMQVjejKAZgQCY4BhOAbwznoRKgA4EA2OAWQAoBKGugyFQAnOwB0FAPYBbAA4AbAKYAXJcCht8QgL4YdQA===

Without modifying the IL emitted by the compiler, I'm not sure there's much we can do. I was very excited by the possibilities raised by that trick, but I think we're stuck.

**Comment by cwe1ss** [comment]
@aidansteele thx for sharing the snippet. That explains the behavior! I don't see a simple solution for this either. That's very unfortunate and quite a big point against using scopes IMO. 😞

@muratg @davidfowl Just curious if you guys have any guidance on this?

**Comment by muratg** [comment]
@cwe1ss Not a lot of ideas on my side... @pakrym any thoughts/guidance on this?

**Comment by BrianLPeterson** [comment]
its not a good solution but you can try catch append headers which contain the scope information up the stack to your error handler which logs all the scope info

**Comment by cwe1ss** [comment]
@muratg As there's probably nothing that can be done here in a non-breaking way, I'm fine with this being closed. Or do you want to keep this in backlog e.g. for 3.0?

**Comment by davidfowl** [comment]
Agreed. I don't see a way to do this realistically. Closing this out.
