### ISSUE TITLE
Unable to build releases

### ISSUE THREAD

**Issue by JeremyTCD** [aspnet/Logging#681]
# Issue
Unable to build releases "2.0.0-preview1" and "2.0.0-preview2". The following error occurs in the restore target of a build:

```
Restoring packages for C:\Users\Jeremy\Desktop\LibrariesAndTools\AspNetCore.Logging\Logging\src\Microsoft.Extensions.Logging.TraceSource\Microsoft.Extensions.Logging.TraceSource.csproj...
C:\Users\Jeremy\.dotnet\x64\sdk\2.0.0-preview1-005957\NuGet.targets(97,5): error : Unable to resolve 'Internal.AspNetCore.Sdk (>= 2.1.0)' for '.NETStandard,Version=v1.1'. [C:\Users\Jeremy\Desktop\LibrariesAndTools\AspNetCore.Logging\Logging\.build\KoreBuild.proj]
```

# What are the EXACT steps to reproduce this problem?
1. `git clone https://github.com/aspnet/Logging.git`
2. `cd Logging`
3. `git checkout rel/2.0.0-preview1`
4. `.\build.ps1` 

# What operating system are you using?
Windows 10

# Notes
I've added `https://dotnet.myget.org/feed/aspnetcore-tools/package/nuget/Internal.AspNetCore.Sdk` to my system-wide Nuget.Config. The error still occurs everytime I try to build the solution. I guess my system probably isn't set up right. I'm able to build release 1.1.2 though. Would appreciate any tips, thanks!

**Comment by muratg** [comment]
@natemcmaster Any thoughts?

**Comment by natemcmaster** [comment]
@smitpatel  - it looks like you removed a required feed in https://github.com/aspnet/Logging/commit/469f0b03d37fbc0cc70f14eefce64b60af7349b5

**Comment by natemcmaster** [comment]
@JeremyTCD the system-wide feed doesn't any effect because the local NuGet.config has `<clear />` in it. You'll need to re-add `<add key="AspNetCoreTools" value="https://dotnet.myget.org/F/aspnetcore-tools/api/v3/index.json" />` to the local Nuget.config file after the `<clear />`

**Comment by smitpatel** [comment]
At the time of making tags, I copy pasted the NuGet.config given to me. Probably that was incorrect one. Due to dogfood VM, I wasn't able to verify builds. I will update the tag.

**Comment by smitpatel** [comment]
I updated both tags. I am not able to build (probably due to having newer CLI & packages downloaded)

**Comment by natemcmaster** [comment]
Does it work if you add a global.json file?

**Comment by JeremyTCD** [comment]
@natemcmaster Thanks for the tip! I now get a bunch of package incompatibility errors though. Probably similar to @smitpatel's:

```
Errors in C:\Users\Jeremy\Desktop\LibrariesAndTools\AspNetCore\Logging\src\Microsoft.Extensions.Logging\Microsoft.Extensions.Logging.csproj
      Package Microsoft.Extensions.Configuration 2.0.0 is not compatible with netstandard1.1 (.NETStandard,Version=v1.1). Package Microsoft.Extensions.Configuration 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      Package Microsoft.Extensions.DependencyInjection.Abstractions 2.0.0 is not compatible with netstandard1.1 (.NETStandard,Version=v1.1). Package Microsoft.Extensions.DependencyInjection.Abstractions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
      One or more packages are incompatible with .NETStandard,Version=v1.1.
```
I think it has to do with the AspNetCoreVersion property in build/dependencies.props:
```
<AspNetCoreVersion>2.0.0-preview1-*</AspNetCoreVersion>
```
It is used to specify package versions. For example in Microsoft.Extensions.Logging.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\build\common.props" />

  <PropertyGroup>
    <Description>Logging infrastructure default implementation for Microsoft.Extensions.Logging.</Description>
    <TargetFramework>netstandard1.1</TargetFramework>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageTags>logging</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.Extensions.Logging.Abstractions\Microsoft.Extensions.Logging.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="$(AspNetCoreVersion)" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(AspNetCoreVersion)" />
  </ItemGroup>

</Project>
```
As a result, `2.0.0-preview1-*` versions are being imported into `netstandard1.1` projects.

**Comment by natemcmaster** [comment]
So what _should_ be happening is that `2.0.0-preview1-*` should resolve to `2.0.0-preview1-final`, which was before we did the netstandard2.0 conversion. https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Abstractions/2.0.0-preview1-final. but for reasons I don't understand, NuGet is skipping over "2.0.0-preview1-final" to "2.0.0".

If you change that line in dependency props to 2.0.0-preview1-final, you should be able to restore correctly.

https://github.com/aspnet/Logging/blob/8ee11b6cd5d67d80d55883f21425c374adcd216f/build/dependencies.props#L3

That said, you're still likely to encounter other errors, especially if you want to use VS. We don't normally support building pre-releases, especially once we have released a stable version. We are constantly using pre-release versions of VS and the .NET Core SDK, and there are usually several breaking changes between early previews and the final RTM releases.

**Comment by JeremyTCD** [comment]
Ah sorry for bothering you all. Just realized that 2.0.0 has been released and it builds fine. Thanks for the in depth explanation anyway!
