### ISSUE TITLE
Add Logger base class with scope logic

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Logging#682]
Today many custom logger implementations don't properly implement scopes. We can make this a bit easier by providing a base class which handles scopes with an async local and provides a nice overload that aggregates them.

**Comment by cwe1ss** [comment]
Is it a performance issue that each provider manages its own copy of scopes? Would there be a way to solve this once in `Microsoft.Extensions.Logging` and just pass scopes to the providers somehow?

My example: I use two providers, ApplicationInsights for most logs and the Console-logger with MinimumLevel.Critical to output application crashes and other custom critical errors (mainly for easier troubleshooting with Service Fabric). 
So the console logger doesn't do anything most of the time, but it still holds its own AsyncLocal storage for scopes.

**Comment by davidfowl** [comment]
I'm not sure anything else can be done besides the base class that doesn't cause breaking changes.

**Comment by muratg** [comment]
See: https://github.com/aspnet/Logging/issues/674

**Comment by davidfowl** [comment]
https://github.com/aspnet/Logging/pull/723
