### ISSUE TITLE
Package Microsoft.Extensions.Logging 2.0.0 is not compatible with netcoreapp1.1 

### ISSUE THREAD

**Issue by a-h** [aspnet/Logging#686]
Scenario
======

- A developer is setting up a new project in .NET Core 1.1 (the latest stable version at time of report)
    - `dotnet new console`
- A developer attempts to add Microsoft.Extensions.Logging to a project with the command
    - `dotnet add package Microsoft.Extensions.Logging`
- Even though this used to work, the developer now get an error message.

```
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  Writing /var/folders/v0/gv8rbbt9157g5599sh8qljpr0000gn/T/tmplgLNYu.tmp
info : Adding PackageReference for package 'Microsoft.Extensions.Logging' into project '/Users/adrian/dnn/dnn.csproj'.
log  : Restoring packages for /Users/adrian/dnn/dnn.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/index.json 491ms
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/2.0.0/microsoft.extensions.logging.2.0.0.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/2.0.0/microsoft.extensions.logging.2.0.0.nupkg 500ms
error: Package Microsoft.Extensions.Logging 2.0.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Extensions.Logging 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.1.
error: Package 'Microsoft.Extensions.Logging' is incompatible with 'all' frameworks in project '/Users/adrian/dnn/dnn.csproj'.
```

Two choices, upgrade my app to .NET Core 2.0 (don't want to, it's still in beta) or use the latest stable .NET Core 1.1 version of the library:

```
dotnet add package Microsoft.Extensions.Logging -v 1.1.2
```

This changed 3 days ago, when Microsoft.Extensions.Logging 2.0.0 lost it's preview tags. Given it's not compatible with 1.1, and there are 15k downloads a day, then I'd guess the NuGet change will break more than a few builds and/or cause some confusion.

I don't know about this project and how this is supposed to work, but it was surprising to me, given that for years, NuGet packages have supported net3.5, net4.5 all inside the same package.

If all of the Microsoft packages are adopting this, it won't be good for .NET Core since it could make many online tutorials and blog posts broken.

My suggestion is to provide a version that works against .NET Core 1.1 in the 2.0.0 package, at least for some sort of handover period until .NET Core 2.0.0 is stable.

**Comment by davidfowl** [comment]
This is really a nuget issue. Even when 2.0.0 is stable, nuget won't detect which version is most compatible and add it to your project. It'll still fail at install time. We're not planning to support netstandard < 2.0 in our 2.0.0 packages (they're already done at this point), so you'll have to specify the version to install.

PS: There's no guarantee that these packages are compatible across major versions. All Microsoft.Extensions.* packages version 2.0.0 require .NET Standard 2.0

**Comment by davidfowl** [comment]
This shouldn't break any builds unless you has logic that was installing a fresh version of logging on every ci build. If you were installing the latest version on each build then being broken when a new version comes out is by design.

**Comment by a-h** [comment]
Thanks for the response. I guess since .NET Core 2.0 is now RTM, no problem anyway!
