### ISSUE TITLE
How FormattedLogValues is working ?

### ISSUE THREAD

**Issue by WernerMairl** [aspnet/Logging#694]
Hi
i see a unexpected behavior, not sure if i'm doing something wrong....
(using .net Core 2.0.0 and packages in version 2.0.0)

Assuming that the following extension method is working like string.Format!

`public static void LogTrace(this ILogger logger, string message, params object[] args)
`
the following sample should return 2 idenical trace strings!

```
string s = string.Format("{1} Bytes Markdown written to '{0}'", fn, markdown.Length);
this.Logger.LogTrace(s);
this.Logger.LogTrace("{1} Bytes Markdown written to '{0}'", fn, markdown.Length);
```

returns the following output on the Console-Logger (different strings)

trce: XXX[0]
      352 Bytes Markdown written to 'c:\xxx.md'
trce: XXX[0]
      c:\xxx.md Bytes Markdown written to '352'

This is a known issue/behavior ?
assuming that the problem comes from using format placeholder {0},{1} ordered in DESC not ASC
"{1} Bytess Markdown written to '{0}'"

internally the string calculation is done in the class FormattedLogValues, so i'm assuming that the behavior comes from there....

regards
Werner

**Comment by davidfowl** [comment]
See https://messagetemplates.org/. Those aren't regular format strings. They are message templates. You should be using meaningful names in there.

**Comment by WernerMairl** [comment]
David, 
that's a valid explanation but then i suggest to change comments on the Arguments => Usability!

```
        /// <summary>
        /// Formats and writes a trace log message.
        /// </summary>
        /// <param name="logger">The <see cref="ILogger"/> to write to.</param>
        /// <param name="message">Format string of the log message.</param>
        /// <param name="args">An object array that contains zero or more objects to format.</param>
        public static void LogTrace(this ILogger logger, string message, params object[] args)
```
As a "very old" C# coder, everything in this Method declaration lets me assume that i can use string.format syntax!
The parameter "message" is commented with **Format string**

so please document (xml comments, Intellisense etc) that a different syntax then string.format must be used!!

it costs me a full day to find out why my tracing is producing wrong output....


regards
Werner

**Comment by davidfowl** [comment]
@WernerMairl Sorry :disappointed: we'll improve both the documentation and the doc comments here.

/cc @pakrym @muratg @Rick-Anderson

**Comment by pakrym** [comment]
Updated doc comments in #702, doc changes tracked in https://github.com/aspnet/Docs/issues/4093
