### ISSUE TITLE
Add less verbose logger extensions.

### ISSUE THREAD

**Issue by nilss0n** [aspnet/Logging#698]
Using the logging methods in their current form is somewhat verbose. In my team we have created a simplified set of logging methods (extensions), one for each logging level.

Example:
```csharp
public static void Debug(this ILogger logger, string message, Exception error = null)
{
	Log(logger, LogLevel.Debug, message, error);
}

private static void Log(ILogger logger, LogLevel level, string message, Exception error)
{
    logger.Log(level, new EventId(), message, error, Formatter);
}

private static string Formatter(string s, Exception exception)
{
    if (exception != null)
    {
        return s + Environment.NewLine + exception;
    }
    return s;
}
```
Our suggestion is to add these extension methods to `LoggerExtensions.cs`, i.e. `LogDebug` etc. 

We also tend to stay with static loggers instead of leveraging the constructor dependency. That's only for logging. We treat the logging as an infrastcture thing, not as a direct dependency. So we tend to use the old log4net style, using static factory method. To simplify the setup of this, we created a static Logger factory which lets us create a logger like this:
```csharp
static ILogger logger = LoggerFactory.CreateClassLogger(true);
```
The factory itself looks like this:
```csharp
public static readonly LoggerFactory Instance;

public static ILogger CreateLogger(string loggerName) => Instance.CreateLogger(loggerName);
public static ILogger CreateLogger(bool useFullName = false) => CreateClassLogger(useFullName, new StackFrame(1).GetMethod()?.DeclaringType);

private static ILogger CreateClassLogger(bool useFullName, Type type)
{
    if (type == null) throw new ArgumentNullException(nameof(type));

    string fullName = TypeNameHelper.GetTypeDisplayName(type);
    return Instance.CreateLogger(useFullName ? fullName : fullName.Split('.').Last());
}
```

If any of this is of interest we'll create a PR.

**Comment by muratg** [comment]
We don't plan to do this.  It's easy to add these in your app if you find the usage simpler.

cc @glennc FYI
