### ISSUE TITLE
Cannot implicitly convert type 'System.IDisposable' to 'System.IDisposable' 

### ISSUE THREAD

**Issue by cilerler** [aspnet/Logging#699]
Created a **.NET Standard 2** class library and added code below

```csharp
logger.BeginScope("{url}",url))
{
//...
}
```
into it and receiving the error **Cannot implicitly convert type 'System.IDisposable' to 'System.IDisposable'**

![2017-09-03_13-41-08](https://user-images.githubusercontent.com/385958/30005689-f86cb056-90b5-11e7-8f69-7792f0be3082.png)

**Comment by cilerler** [comment]
It turned out that **Microsoft.Extensions.Primitives** is needed in the project to fix that issue.

However It did came with **Microsoft.Extensions.Configuration.Abstractions** and not with **Microsoft.Extensions.Logging.Abstractions**.

**Comment by davidfowl** [comment]
@cilerler I think you're missing a bunch of steps to reproduce the problem. A .NET Standard 2.0 library doesn't include Microsoft.Extensions.Logging, did you mean an ASP.NET Core 2.0 project?

**Comment by cilerler** [comment]
Nope, added as a Nuget library here is the project file

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.5.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.0.0" />
  </ItemGroup>

</Project>
```

**Comment by davidfowl** [comment]
@cilerler Can you push a repro project to github? That has the above error message?

**Comment by cilerler** [comment]
😕 I tried but no luck to reproduce it...  I'm glad I took a screenshot...  All I had was creating brand new project.  Anyway, closing this since no way to reproduce.  Thanks for the response 🤗
