### ISSUE TITLE
Don't set AsyncLocal for scope if not included

### ISSUE THREAD

**Issue by benaadams** [aspnet/Logging#714]
Adding ConsoleLogger disturbs the `ExecutionContext` even if scopes aren't being used and causes allocations to wildly increase.

Without ConsoleLogger (no-changes to AsyncLocal)
![](https://aoa.blob.core.windows.net/aspnet/tasks-action.png)

With ConsoleLogger and no scopes - but not logging anything to Console (changes to AsyncLocal)
![](https://aoa.blob.core.windows.net/aspnet/async-local.png)

You can see the allocations of `Action` and `MoveNextRunner` disproportionately increase

**Comment by benaadams** [comment]
@pakrym resolved by https://github.com/aspnet/Logging/pull/723?

**Comment by pakrym** [comment]
Nope, It's made harder to resolve by that PR. Central storage doesn't know if anyone is planning to log scope values so they have to be collected all the time.

**Comment by stephentoub** [comment]
@benaadams, I'm curious how those screenshots change using 2.1?

**Comment by benaadams** [comment]
274,597 requests (with asynclocals); Action has lost its top spot

![image](https://user-images.githubusercontent.com/1142958/35487896-2ae6e9e8-0479-11e8-80ec-74d0eb1e2e4e.png)

**Comment by stephentoub** [comment]
Great, thanks, glad to see the async builder improvements helped.

**Comment by benaadams** [comment]
374,490 requests without logging (no asynclocals)
![image](https://user-images.githubusercontent.com/1142958/35488209-be804f7a-047c-11e8-898d-9ab4bd090a61.png)

**Comment by stephentoub** [comment]
Right, in 2.1 Action allocations should no longer be impacted by AsyncLocals.

**Comment by benaadams** [comment]
Backtracing Action most aren't from AsyncMehodBuilder anymore; the are from [`LoggingThreadPool.Schedule(Action<object> action, object state)`](https://github.com/aspnet/KestrelHttpServer/blob/bbe8851f32984264282d80ea1a0fe4c70cbffa95/src/Kestrel.Core/Internal/Infrastructure/LoggingThreadPool.cs#L58-L62)

![image](https://user-images.githubusercontent.com/1142958/35488289-00746302-047e-11e8-9270-a2828948ff93.png)

**Comment by davidfowl** [comment]
With the new design of the external scope provider, this is actually much harder to achieve.

**Comment by davidfowl** [comment]
@benaadams if you want to take a look, have at it!

**Comment by snakefoot** [comment]
A good starting point would be if the new logic in #723, re-introduced the optimization it had removed:

```
if (loggers.Length == 1)
    return loggers[0].Logger.BeginScope(state);
```
