### ISSUE TITLE
Azure App Service provider not automatically available on ASP.NET Core 2 when target full framework

### ISSUE THREAD

**Issue by nphmuller** [aspnet/Logging#716]
According to [the docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging?tabs=aspnetcore2x#appservice) the Azure App Service logging provider should automatically be configured on ASP.NET Core 2.x. This doesn't happen when targeting the full framework.

When I add the logging provider manually all seems to work. I.e.:
``` c#
.ConfigureLogging(builder =>
{
    builder.AddAzureWebAppDiagnostics();
});
```

**Comment by muratg** [comment]
This is by design.  Light-up features don't work well with .NET Framework.

cc @glennc FYI
