### ISSUE TITLE
Concerns around how log messages are evolving

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/Logging#72]
Watching how logging is rolling out and I'm getting a little concerned around how `ILoggerStructure` seems to be evolving as a shortcut to not having type properties. 

If we take a look at the new `ControllerActionDescriptorValues` log object which is being proposed, it looks like the [following](https://github.com/aspnet/Mvc/blob/logging-assemblies/src/Microsoft.AspNet.Mvc.Core/Logging/ControllerActionDescriptorValues.cs) (note, I've copied it here to more easily see the issue):
```
    public class ControllerActionDescriptorValues : ILoggerStructure
    {
        public ControllerActionDescriptor Inner { get; }

        private Dictionary<string, object> _values;

        public ControllerActionDescriptorValues(ControllerActionDescriptor inner)
        {
            Inner = inner;
        }

        public string Format()
        {
            return LogFormatter.FormatStructure(this);
        }

        public IEnumerable<KeyValuePair<string, object>> GetValues()
        {
            if (_values == null)
            {
                _values = new Dictionary<string, object> {
                    { "ActionName", Inner.Name },
                    { "Method", Inner.MethodInfo.Name },
                    { "Parameters", Inner.Parameters.Select(p => new ParameterDescriptorValues(p)).ToList() },
                    { "Controller", Inner.ControllerName },
                    { "Type", Inner.ControllerDescriptor.ControllerTypeInfo.FullName },
                    { "FilterDescriptors", Inner.FilterDescriptors.Select(
                        f => new FilterDescriptorValues(f)).ToList() },
                    { "RouteConstraints", Inner.RouteConstraints.Select(
                        r => new RouteDataActionConstraintValues(r)).ToList() },
                    { "AttributeRouteInfo", new AttributeRouteInfoValues(Inner.AttributeRouteInfo) },
                    { "ActionConstraints", Inner.ActionConstraints == null ? string.Empty : string.Join(
                        ", ", Inner.ActionConstraints) }
                };
            }
            return _values;
        }
    }
```

In cases like this where the log message is proxying the target object, I'm wondering if various issues will start to arise:
 - Logging consumers having the ability to mutate the state.
 - Memory leaks where log messages aren't being process immediately and the GC can't release resources that it normally would
 - Messages that aren't being processed immediately might have properties on the target object changed after the log statement occurred
 - etc

Hence I'm proposing that the following recommendations for log messages:
 - Target objects are only used used inside the scope of the constructor (hence releasing the object as soon as the object is created).
 - Typed properties be added to the log message class which target the properties of interest (very similar to the ones found in the `GetValues()` result
 - The `GetValues()` be switch to pull the data from these new properties
 - Not all properties need to be primitive (for instance `MethodInfo` could be brought across as an object as that is immutable).

I understand that this might be limiting some options and more thought needs to be put upfront around which properties are needed, but I'm not sure if there are too many ways of avoiding the afore mentioned issues.

**Comment by muratg** [comment]
@kichalla will talk to @rynowak for some of the details.

**Comment by rynowak** [comment]
This feedback is based on a bunch of code that we've removed. I'm not sure there's anything actionable in this work item.

**Comment by muratg** [comment]
@rynowak Yeah, we thought most of it is already covered by removed code or updates with the API review, we suspected some maybe still actionable. If not, this should be good to close.

**Comment by rynowak** [comment]
It's not actionable in MVC and Routing. The other place to look would probably be Identity.

**Comment by kichalla** [comment]
I couldn't find any other place where we are doing this anymore. So we are good to close this one.
