### ISSUE TITLE
Warning C4691 when building a C++/CLI executable

### ISSUE THREAD

**Issue by malachib** [aspnet/Logging#734]
As the title reads, I am attempting to utilize the logging library from a C++/CLI (.NET Framework 4.6) executable.  Original MSDN thread with artifacts [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/fae48caa-7746-4c8f-9c44-839bd23ed128/warning-c4691-when-building-a-ccli-executable-referencing-microsoftextensionslogging-via-nuget?forum=vcgeneral)

It actually works quite well, but I am experiencing concerning warnings inclusive of the following:

```
>c:\projects\ucpro\application\ucpront\logging.h(33): warning C4691: 'System::Exception': type referenced was expected in unreferenced assembly 'System.Runtime', type defined in current translation unit used instead
>c:\projects\ucpro\application\ucpront\logging.h(33): note: This diagnostic occurred while importing type 'Microsoft::Extensions::Logging::ILogger ' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
>c:\projects\ucpro\application\ucpront\logging.h(33): warning C4691: 'System::Func': type referenced was expected in unreferenced assembly 'System.Runtime', type defined in current translation unit used instead
>c:\projects\ucpro\application\ucpront\logging.h(33): note: This diagnostic occurred while importing type 'Microsoft::Extensions::Logging::ILogger ' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```

As you can see in the warnings, the logging package versions are 1.1.2

Exact steps for recreating the issue are outlined in the MSDN thread, but to summarize, merely opening and compiling SW-132 project in [SW-132v2](https://www.dropbox.com/s/9261ina8p4gyce1/SW-132v2.zip?dl=0) exhibits the issue.

**Comment by muratg** [comment]
@emgarten any thoughts about these restore warnings?

**Comment by muratg** [comment]
@malachib my current guess is that you're using those assemblies from the .NET Framework (which is installed on your machine) while the reference is from a package.  This normally works with .NET projects without warnings AFAIK, but this is something we never really tested.  If I had to guess, I'd say the warnings seem benign.

**Comment by malachib** [comment]
@muratg they do seem benign; we're effectively using this code for dev and diagnostic purposes.  However, we have a pretty strict warning policy here and until we can conclusively determine that they are indeed benign, we can't take this code into production

**Comment by muratg** [comment]
@malachib it looks like you did a project to project reference and bring the dependencies through the sister project.  Do you still get warnings if you reference the packages directly from your main project?

**Comment by malachib** [comment]
@muratg, That's actually an interesting aspect to all this.  The sister project is necessary, one is not able to directly nuget-install this (and all others I've tried) .NET library into a C++/CLI project.  

I believe it has something to do with nuget identifying the C++/CLI project as a C++ and not a .NET project.

I did a manual DLL browse to the exact net46 folders in which NuGet retrieved Microsoft.Extensions.* to achieve the explicit references you see in the SW-132 project

**Comment by emgarten** [comment]
I'm not sure how NuGet would cause this. Did this work in the past?

**Comment by muratg** [comment]
@emgarten Yeah, I don't think it's nuget either.  There are explicit references from a the c++ project to the assemblies earlier restored through another project.
```
    <Reference Include="Microsoft.Extensions.Logging">
      <HintPath>NuGetShim\bin\Debug\net46\Microsoft.Extensions.Logging.dll</HintPath>
    </Reference>
```

@malachib It's appears that the warnings are coming from the C++ compiler. Perhaps some of the suggestions on this thread would help:  https://social.msdn.microsoft.com/Forums/vstudio/en-US/c72e8a1a-db15-42cb-92dd-48a12348b8e8/warning-c4691-when-building-a-ccli-library-referencing-a-pcl?forum=vcgeneral

**Comment by malachib** [comment]
@muratg yes, I've read through and tried the suggestions in that thread.  Unfortunately it appears that they, like myself, did not reach a firm conclusion or fix.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
