### ISSUE TITLE
Proposal: LogLevel triggered buffered LoggerDecorator

### ISSUE THREAD

**Issue by glatzert** [aspnet/Logging#735]
We had a situation, where our normal logging level of warning did not provide enough information, but the information logs would show the information. Unfortunately information logs will generate lots more of output, which might or might not be useful.

So my proposal is that there should be a logger which will:
 - Create a Log-Buffer for every incomming request
 - Write into that buffer
 - when an log message of level x (e.g. ERROR) is sent to the logger, it will flush all messages of level y to whatever Logger is decorated by the buffered-log-level-triggered-LoggerDecorator.
 - when no log message of level x is received, all messages are silently discarded.

X and Y could be configured as well as the logger it decorates.

**Comment by davidfowl** [comment]
@glatzert This doesn't sound like something that would be built into our logging library. Sounds like it could be useful as a 3rd party logger provider though.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
