### ISSUE TITLE
Remove/obsolete AzureAppServicesDiagnosticsSettings.OutputTemplate

### ISSUE THREAD

**Issue by pakrym** [aspnet/Logging#736]
It's not used since we moved off Serilog.

**Comment by muratg** [comment]
@pakrym obsolote in 2.1, remove in 2.2?

**Comment by pakrym** [comment]
Technically it's a breaking change.

**Comment by muratg** [comment]
Meh. Obsolete now, remove in 3?

**Comment by pakrym** [comment]
OK

**Comment by davidfowl** [comment]
We can deprecate it but it's a breaking change to remove it so lets not.

**Comment by muratg** [comment]
Yes. Let's put the attribute in preview2 @pakrym.
