### ISSUE TITLE
Limit use of ReflectionBasedLogValues

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/Logging#74]
I'm wondering if, as a guideline, we can try not to use `LoggerStructureBase` for anything in the framework (in the aspnet github org)? I can see reasons for it to exist but I'm worried about it being used for core logging.

My reasoning around this is that when we start listing to logs, if we are relying heavenly on `ILoggerStructure`, triggering the style of reflection on every single log message is fairly heavy. I know this means that we spend a little more time now in development manually creating the dictionaries, but that time spend now, is going to save so much for so many people in the future.

**Comment by avanderhoorn** [comment]
@Eilon @lodejard Just wondering if/when this is going to get looked at? Since things are being cleaned up it seems like this is something that should be looked at. I'm worried that tapping these properties will be impractical without some sort of IL code gen, etc.

**Comment by Eilon** [comment]
Most of our current perf analysis work is focused only on startup time right. As far as other engineering efforts we're trying to lock down on features and critical bugs. As more of the team frees up to look at perf work we'll definitely spend a good chunk of time analyzing logging overhead to see what the optimal improvements are.

**Comment by avanderhoorn** [comment]
@Eilon Sounds good. Just wanted to make sure it wasn't missed as we will be relying on this a lot.

**Comment by kichalla** [comment]
I no longer see any usage of `ReflectionBasedLogValues` under any repos of `aspnet` organization, so I think we are good to close this issue.
