### ISSUE TITLE
AppService logging to BlobStorage can lead to memory exhaustion 

### ISSUE THREAD

**Issue by Costo** [aspnet/Logging#742]
We recently updated our web app to Asp.Net Core 2.0 (from 1.1). After we deployed this change to AppService in Azure, we started to see high memory usage and OutOfMemoryExceptions after a while (a few hours). Only a restart would temporarily fix the problem.

Here is what we were seeing with  App Service diagnostics:
<img width="735" alt="napkin 17-12-06 5 14 33 pm" src="https://user-images.githubusercontent.com/46972/33688307-ee21b870-daa8-11e7-946f-14f559536eb0.png">

After some time we noticed that the Blob Storage application logging level was set to "Verbose": 

![screen shot 2017-12-06 at 10 22 03 am](https://user-images.githubusercontent.com/46972/33688080-3fbddb7e-daa8-11e7-9c86-e58419e39510.png)

This was not intentional, so we reverted the level to "Warning". After this change, the memory problem disappeared.

So my question is: Is this a bug, or is this by design? The logging level should not have been set to "Verbose" in the first place and this was our error. But clearly this problem didn't exist with Asp.Net Core 1.1

Thank you.

**Comment by pakrym** [comment]
OOM comes from overfilling logger message queue, there is an option to limits it's size: 

https://github.com/aspnet/Logging/blob/a314c687957329262da0eb4513c6b96f8f2f1ff6/src/Microsoft.Extensions.Logging.AzureAppServices/AzureAppServicesDiagnosticsSettings.cs#L130

But it's zero by default. 

Not sure why you didn't observe similar behaviour previously, maybe Serilogs internal limits prevented this.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
