### ISSUE TITLE
Consider moving BatchingLogging to Logging

### ISSUE THREAD

**Issue by msmolka** [aspnet/Logging#746]
Batching logging is nice implementation for concurrent and heavy log messages. It would be useful to put this implementation outside Azure logging. 
Then it would be easy reused for File logging, database and other external providers.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
