### ISSUE TITLE
Input data can create exception

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/Logging#748]
Are there any best practices to sanitize input data - see this issue

https://github.com/IdentityServer/IdentityServer4/issues/1931

**Comment by pakrym** [comment]
Yes, using message template (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x#log-message-template) would avoid the issue.

**Comment by leastprivilege** [comment]
OK - given that almost no-one uses message templates - it's pretty easy to provoke unhandled exceptions in many asp.net core apps by adding curly braces to input.

I can see the problem - but shouldn't this be handled more gracefully?

**Comment by leastprivilege** [comment]
OK - I see, we also have some manual string concatenation going on in addition.

I guess we will switch to LoggerMessage.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
