### ISSUE TITLE
ILogger log.Error in AppInsights cannot log Dictionary<string,string>

### ISSUE THREAD

**Issue by skec0912** [aspnet/Logging#749]
I have problem when I want to log Dictionary or my custom class in app insights.
My code is :

loggerFactory.AddApplicationInsights(app.ApplicationServices);
       try
            {
                throw new Exception("This is a test exception for app insights.");
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Exception message",new Dictionary<string, string>() { {"Controller","Error" } });
 throw;
}

Any idea?

**Comment by muratg** [comment]
@skec0912 What exactly are you trying to attempt, and what's the issue you're seeing

**Comment by skec0912** [comment]
I want to log error with this args, where args are dictionary<string,string>. I log error but args didnt atempt in app insight.

**Comment by hkusulja** [comment]
Application insights allows custom object to be sent, but logger has issues about forwarding it to AppInsights. Simply it is not forwarded. Any idea?

**Comment by hkusulja** [comment]
#753

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
