### ISSUE TITLE
logger.LogError object params not working with Application Insights

### ISSUE THREAD

**Issue by hkusulja** [aspnet/Logging#753]
Dear all,
I have ASP.NET Core 2 WebAPI project and I am using successfully logger with Application insights

```
//ILoggerFactory loggerFactory;
ILogger logger = loggerFactory.CreateLogger("MyLog");
loggerFactory.AddApplicationInsights(app.ApplicationServices);
```

I have issues with using LogError and sending custom object that will be forwarded to Application Insights. 

```
decimal myobject = (decimal)3.14;
logger.LogError(new Exception(), "MyMessage", myobject);
```

Any idea how to make this works?
If I am using directly Application Insights class, then it is working OK.

Thank you

**Comment by NickPolyder** [comment]
From what i understand you are using wrong the api. 
(Or the api has missing features.) 

When you are using: [LogError(this ILogger logger, Exception exception, string message, params object[] args)](https://github.com/aspnet/Logging/blob/fb0103e6b7cc7987dbfc1cc91f7a20b14eaa4937/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs#L361)

The args passed in the method call is part of a string.Format mechanism called [FormattedLogValues](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/Internal/FormattedLogValues.cs)
which basically all it does is to match placeholders with values provided by the `args` array.

Now looking at the implementation of the ApplicationInsightsLogger found here: [Microsoft.ApplicationInsights.AspNetCore](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/master/src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLogger.cs), the implementation will try to add the formatted messages in the dictionary. If the message does not have any placeholder it will not show the values - args passed to the log message. Instead it will show the Original Message.

**Comment by chigivigi** [comment]
Can i somehow pass an object in log error message that shows the property values of the given object ?

**Comment by NickPolyder** [comment]
@chigivigi concerning ApplicationInsights implementation you can use the `ILogger` interface method
`void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)`    
and pass to the state an object that inherits from `IReadOnlyList<KeyValuePair<string, object>>` 
that way you can sent any number of property - object pairs you want.

**Comment by chigivigi** [comment]
But is there a way to pass a object as parameter and not in a string message ?

**Comment by NickPolyder** [comment]
@chigivigi Yes. As i said you can pass an object that implements the `IReadOnlyList<KeyValuePair<string, object>>` 
The `TState` parameter of the `Log` function can take any kind of object. The problem here is that the Application Insights implementation will use only the  `TState` types that implement the `IReadOnlyList<KeyValuePair<string, object>>`  interface

**Comment by muratg** [comment]
@chigivigi Let us know if you have more issues with this.
