### ISSUE TITLE
Proposal: Remove all extensions accepting "string message, params object[] args"

### ISSUE THREAD

**Issue by aanttila** [aspnet/Logging#754]
Several times over the last few months, my team has attempted to use our own extensions to ILogger, but were unaware until looking at the logs that the default LogDebug/etc implementation was used because of the "string message, params object[] args" signature accepting what should calls to a different override.

The overrides I'm asking to be removed can be replaced with the $"{variable}" syntax in newer version so f C#; for older versions consumers can always call String.Format themselves.

This would result in a breaking change, but would add the benefit of the compiler ensuring that the correct override is called (or can't be found).

**Comment by n9** [comment]
I think this will break structural logging. Check for instance: https://www.codeproject.com/Articles/1204083/ASP-NET-Core-Structured-Logging

**Comment by herecydev** [comment]
As @n9 pointed out you can't remove one of the most powerful features. What are you trying to do with the `ILogger` that's not working?

**Comment by davidfowl** [comment]
We're not going to make a breaking change of this magnitude.

**Comment by aanttila** [comment]
To answer a few questions above, the reason for this requested change was the issue with other extension methods like the following:

```
public static void LogDebug(this ILogger logger, string message, ILoggable loggable)
{
    ...
}
```

Such an extension method works as long as Microsoft.Extensions.Logging AND our custom namespace are pulled in with using statements.  If a developer (including me) forgets to reference our custom namespace, the code still compiles, but uses the Microsoft.Extensions.Logging version of the LogDebug method, and we only find out after a deployment and the logs are examined.

I think it's really easy to find ourselves in this situation, and if there is an alternative way to prevent this (without renaming the LogDebug method), I'd love to hear suggestions.

**Comment by n9** [comment]
I would suggest to put loggable before message (if you can).

**Comment by herecydev** [comment]
I would make a roslyn analyzer that detects if they're calling the "wrong" overload and you can create a code fix to import your namespace. Should be pretty simple and doesn't involve changing the `aspnet/logging` system to suit your use case.
