### ISSUE TITLE
Remove TypeNameHelper from Logging

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Logging#756]
We have the one true copy of `TypeNameHelper` in Common. Unfortunately the type here is used to calculate the logger name \ `categoryName`, so there are some scenarios where using the one from Common might change this value and break existing filters. Might be something to consider for 3.0.

**Comment by Eilon** [comment]
Yeah I believe the various helpers have diverged somewhat. The use case in Logging and in other places (such as showing a pretty type name in an error message) are quite different. I don't think there's value in trying to unify them - aside from the negative value of a more complex code base...
