### ISSUE TITLE
Question: Logging scopes with correlation id

### ISSUE THREAD

**Issue by rdcm** [aspnet/Logging#759]
Could not find similar issue.

Following InvokeAsync method  in my middleware  perfect include scope to console, but can i include 
scopes global, not only for console?  For example in txt file scopes not included.

```
        public async Task InvokeAsync(HttpContext context)
        {
            var correlationId = _correlationIdEnricher.Enrich(context);
            var correlationScope = new KeyValuePair<string, Guid>(_correlationIdEnricher.CorrelationIdHeader, correlationId);
            using (_logger.BeginScope(correlationScope))
            {
                _logger.LogInformation(await context.Request.ReadRequestAsync());

                await _next(context);

                _logger.LogInformation(await context.Response.ReadResponseAsync());
            }
        }
```

**Comment by davidfowl** [comment]
No there's no feature to allow that. I suggest that you use something like Serilog which has these features.

**Comment by rdcm** [comment]
Yes, you right, Serilog add scope to own "properties", without explicit adding template `outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss} [{Level}] {Message}{NewLine}{Exception}{Properties}"` to serilog config, scope not logging in file.
