### ISSUE TITLE
LoggerExtensions prematurely create FormattedLogValues and potentially exhaust cache of LogValuesFormatter

### ISSUE THREAD

**Issue by mikevanoo** [aspnet/Logging#762]
This is more of a discussion initially...

The LogXXX extension methods in [LoggerExtensions](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs) create a new instance of [FormattedLogValues](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/Internal/FormattedLogValues.cs) without being guarded by any IsEnabled check. In turn, FormattedLogValues holds a cache of [LogValuesFormatter](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/Internal/LogValuesFormatter.cs) instances with a hard-coded limit of 1024 instances. After that, all new formatters that aren't in the cache are created as a new instance and thrown away each time.

Whilst the [guidelines](https://github.com/aspnet/Logging/wiki/Guidelines) recommend adding IsEnabled guards around calls to LogXXX, the code samples [here](https://github.com/aspnet/Logging/tree/dev/samples) and [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x) do not use them. 

As this cache is static, it is shared across all ILogger users in the process: the framework, the application and any 3rd party packages. It seems quite possible (even likely) that code without IsEnabled code guards (possibly written using the samples above or possibly just relying on log filtering) could use up the cache of LogValuesFormatter instances and thus impact performance.

So:

1. Should the cache strategy be changed, for example, to use a keep MRU or evict LRU strategy?
2. Should the 1024 limit be higher or made configurable?
3. Should the code expose a way to determine the current state of the cache to allow an application developer to determine if the limit should be up-ed?
4. Should the LogXXX extension methods perform an IsEnabled check?

**Comment by davidfowl** [comment]
Our docs are a bit sparse on the best practices here. The way to optimize logging in general is to use the LoggerMessage type to create a "pre-compiled" logger. https://github.com/aspnet/Logging/blob/9506ccc3f3491488fe88010ef8b9eb64594abf95/src/Microsoft.Extensions.Logging.Abstractions/LoggerMessage.cs

Here's an example on how it's used:
https://github.com/aspnet/SignalR/blob/bfa2df1fc650fda6c92ca52c7a83c187b25e2583/src/Microsoft.AspNetCore.Sockets/Internal/SocketLoggerExtensions.cs

Our default implementation should be a little less naive and should implement a better caching strategy. I'm not sure the limit should be configurable, it's one of those things you should never have to tweak.

**Comment by mikevanoo-fsg** [comment]
Thanks for your reply David. However, that is a bit ... err ... cumbersome.

For every message template you want to log you statically create a delegate (that caches the formatter) regardless of whether the message will ever actually be logged. I guess this would ensure that your formatters are "cached" but it does bypass the purpose of the limited cache. 

**Re: "Our default implementation should be a little less naive and should implement a better caching strategy."**
I think it boils down to this statement as this is the way the vast majority will use the loggers...

**Comment by StephenCleary** [comment]
[Docs are here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/loggermessage)

I'm experimenting with a pattern that avoids the delegate creation (and template parsing etc) for logs that are never called. However, this pattern does require `(CategoryName, EventId)` to be a unique tuple:

```C#
public static class Logger
{
  private static class DelegatesFor<TLoggerCategory>
  {
    public static readonly ConcurrentDictionary<int, object> Delegates = new ConcurrentDictionary<int, object>();
  }

  public static void Log<TLoggerCategory, T1>(ILogger<TLoggerCategory> logger, int eventId, LogLevel logLevel, string format, T1 arg1, [CallerMemberName] string eventName = null)
  {
    var action = (Action<ILogger, T1, Exception>)DelegatesFor<TLoggerCategory>.Delegates.GetOrAdd(eventId, _ =>
      LoggerMessage.Define<T1>(logLevel, new EventId(eventId, eventName), format));
    action(logger, arg1, null);
  }
  ... other overloads for more parameters / no parameters, plus exceptions
}
```

The above is a helper type that only needs to be written once and can be placed in a library.

Then, defining each set of log messages:

```C#
internal static partial class Logging
{
  public static void RequestReceived(this ILogger<DocumentationFunction> logger, int jsonVersion, string packageId, string packageVersion, string targetFramework) =>
    Logger.Log(logger, 1, LogLevel.Debug, "Received request for jsonVersion={jsonVersion}, packageId={packageId}, packageVersion={packageVersion}, targetFramework={targetFramework}",
      jsonVersion, packageId, packageVersion, targetFramework);

  public static void UpdateRequired(this ILogger<DocumentationFunction> logger, int requestedJsonVersion, int currentJsonVersion) =>
    Logger.Log(logger, 2, LogLevel.Error, "Requested JSON version {requestedJsonVersion} is old; current JSON version is {currentJsonVersion}",
      requestedJsonVersion, currentJsonVersion);
}
```

Note that all these methods are only defined on generic `ILogger<T>`, not `ILogger`. This helps ensure the proper logs are being used.

Things I like about the pattern:

- Provides a less cumbersome/verbose way to use `LoggerMessage`.
- The event ids line up nicely in the source file. It's pretty easy to read down them and see `1`, `2`, `3`, `4`, `5` and know they're all different.
- The event names are autodetected (`CallerMemberName` instead of `nameof`).

Things I don't like about the pattern:

- Silent failure (with weird logs) if you do mess it up. This is also a drawback to the more verbose pattern.
- Requires generic logger. I occasionally need a logger for a static class, which cannot be used as a generic type. As a workaround, I define a tag type in my `Logging` class.

**Comment by pakrym** [comment]
LoggerMessage.Define should be used to all the cases where exhausting message template cache is a concern.
