### ISSUE TITLE
Unnecessary code execution in LogValuesFormatter

### ISSUE THREAD

**Issue by mikevanoo** [aspnet/Logging#763]
### Title
Unnecessary code execution in LogValuesFormatter. The ctor contains the following code:

https://github.com/aspnet/Logging/blob/5a906a4e8492f709d25a2f7cc737da2915771d44/src/Microsoft.Extensions.Logging.Abstractions/Internal/LogValuesFormatter.cs#L38-L53

However, as `formatDelimiterIndex` is only ever used inside the `else` block, it should be moved there, thus removing some unnecessary calls to `FindIndexOfAny`.

### Functional impact
No functional impact, just more optimal code execution.

**Comment by davidfowl** [comment]
Sounds like it would make a great pull request.

**Comment by mikevanoo-fsg** [comment]
Fair point, I'll see what I can do....

**Comment by d-saravanan** [comment]
I have submitted a [pull-request](https://github.com/aspnet/Logging/pull/771). Please review the same and let me know the review comments.
