### ISSUE TITLE
Add a monochrome output option to ConsoleLogger

### ISSUE THREAD

**Issue by joergjo** [aspnet/Logging#764]
Microsoft.Extensions.Logging.Console.ConsoleLogger should allow to suppress colored output.

Rationale: The colored category output from ConsoleLogger breaks several log viewing features in container orchestration platforms like Service Fabric (Service Fabric Explorer trips over the ANSI escape sequences) or Kubernetes (`kubectl logs` dumps garbage characters on a Windows console). Therefore it would be useful to turn off colored console output to play along nicely with these platforms.

```
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.RedirectToActionResult[1]
      Executing RedirectResult, redirecting to /Cart/Index?returnUrl=%2FChess%2FPage1.
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action SportsStore.Controllers.CartController.AddToCart (SportsStore) in 28.8502ms
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 40.7131ms 302
```

(Applies to Microsoft.AspNetCore.All 2.0.5 and previous versions.)

**Comment by davidfowl** [comment]
> (Applies to Microsoft.AspNetCore.All 2.0.5 and previous versions.)

We won't backport changes like this to all prior versions of ASP.NET Core but we can add a new option to disable this for 2.1.

/cc @muratg @Eilon @glennc

**Comment by joergjo** [comment]
That's OK for me. Just wanted to adhere to the issue contribution guidelines :-)

**Comment by muratg** [comment]
We would accept a PR for this.  If anyone wants to contribute, it may be useful to talk about the approach here first.

**Comment by bruce-lindsay** [comment]
@muratg I would like to fix this. What are you looking for in terms of approach?

**Comment by davidfowl** [comment]
We should expose an option on ConsoleLoggerOptions  to disable the colors.

/cc @pakrym @glennc

**Comment by pakrym** [comment]
https://github.com/aspnet/Logging/pull/772
