### ISSUE TITLE
Cannot configure Logging that uses Configuration from DI

### ISSUE THREAD

**Issue by couven92** [aspnet/Logging#768]
The way to configure logging services in your DI container looks like this:

``` csharp
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace THNETII.Common.Cli.Sample
{
    public static class Program
    {
        public static void Main(string[] args)
        {
            var configBuilder = new ConfigurationBuilder();
            // Add Configuration sources
            IConfiguration config = configBuilder.Build();
            var serviceCollection = new ServiceCollection();
            serviceCollection.AddLogging(
                // Usually you call config.GetSection("Logging") here
                logging => logging.AddConfiguration(config));

            var serviceProvider = serviceCollection.BuildServiceProvider();
        }
    }
}
```

The problem here is that the `ILoggingBuilder` extension method `AddConfiguration` takes an `IConfiguration` instance. I have situations where Logging is configured in a different call site to where Configuration is built, meaning that the ILoggingBuilder will have no concrete IConfiguration instance (yet), but will have it when the DI-container actually has been built.

So Ideally, I'd want something like this:

``` csharp
var serviceCollection = new ServiceCollection();

// Add Configuration service
var configBuilder = new ConfigurationBuilder();
// Add Configuration sources
serviceCollection.AddSingleton<IConfiguration>(configBuilder.Build());

// Add Logging service
// AddConfiguration will add the necessary services wich pull the IConfiguration instance out
// of DI when logging services are requested
serviceCollection.AddLogging(loggingBuilder => loggingBuilder.AddConfiguration());

// Build ServiceProvider
var serviceProvider = serviceCollection.BuildServiceProvider();
```

**Comment by pakrym** [comment]
Unfortunately, there is nothing currently that might allow you to do this. We will consider adding `AddConfiguration` overload in the future. 

The only workaround I can think of is to create a new `IConfiguration` implementation that will proxy to `serviceProbvider` based `IConfiguration` when that would get created and force a reload.

**Comment by muratg** [comment]
Like @pakrym said, this is not supported.
