### ISSUE TITLE
Make ILogger context-aware out of the box

### ISSUE THREAD

**Issue by Grinderofl** [aspnet/Logging#773]
Consider the following base class:

```c#
public abstract class MessageHandlerBase<T> : IHandleMessages<T>
{
    private readonly ILogger _logger;

    protected MessageHandlerBase(ILogger logger)
    {
        _logger = logger;
    }

    public async Task Handle(T message)
    {
        _logger.Log($"START :: HANDLING {typeof(T)}"); 
        await HandleCore(message);
        _logger.Log($"END :: HANDLING {typeof(T)}");
    }
    
    protected abstract Task HandleCore(T message);
}
```

When inheriting from this class and letting roslyn or resharper generate the missing parts, you'll get something like this:

```c#
public class MyMessageHandler : MessageHandlerBase<MyMessage>
{
    public MyMessageHandler(ILogger logger) : base(logger)
    {
    }

    protected override Task HandleCore(T message)
    {
    }
}
```

When you try to run this, the DI framework will complain that ILogger is not registered. I would expect injecting an ILogger to try to resolve ILogger<ClassThisIsInjectedInto>. Could we have this tiny QoL upgrade - ability to forego having to add silly generic arguments to simple stuff like ILogger - just for code generation to work properly please?

**Comment by davidfowl** [comment]
The DI container doesn’t expose enough context to implement this (nor can it because that would impose more requirements on other container adapters). So no, this can’t work out if the box. If you’re using a third party container however, it might be possible I write a factory for ILogger

**Comment by muratg** [comment]
As explained by @davidfowl, this is not supported. Should be doable with another container.
