### ISSUE TITLE
Logger Extensions should use Exception

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Logging#776]
As discussed [here](https://github.com/aspnet/KestrelHttpServer/issues/2384) our logger extensions take an exception, but don't use it to do anything. This confuses a lot of people and leads to Logging messages that end up being uninformative. Even just including the type of the exception would be an improvement.

**Comment by muratg** [comment]
Triage: This is a breaking change that we don't want to take at this point.

**Comment by ryanbrandenburg** [comment]
I'd like us to re-consider. It's very confusing behavior to take the exception then do nothing with it. I think people see that parameter and pass exceptions in assuming something will be done with it, setting themselves up to not have the logging they expect when something goes wrong.

We might not want this for 2.2.0, but I don't know why we wouldn't take it for 3.0.0.

**Comment by davidfowl** [comment]
I don’t see how we can not break existing loggers if we make this change. What about the ones we don’t own. Ones that already handle this behavior...

**Comment by ryanbrandenburg** [comment]
I was going to say that then we should change our ILogger implementations to include the exception themselves, but looking at the code of a couple implementations it seems they now do. That being the case I'm fine with the state of things.
