### ISSUE TITLE
Consider adding support for wildcarding interior segments of log sources

### ISSUE THREAD

**Issue by rynowak** [aspnet/Logging#779]
Some discussion here: https://github.com/aspnet/HttpClientFactory/issues/51

The HttpClient factory creates log sources like:
```
Microsoft.Net.Http.HttpClient.foo.ClientHandler
Microsoft.Net.Http.HttpClient.foo.Polly
Microsoft.Net.Http.HttpClient.bar.ClientHandler
Microsoft.Net.Http.HttpClient.bar.Polly
```

The 5th segment represents the 'client name' - a logical identifier assigned by the application author. The 6th segment represents a specific source associated with that 'client name'.

Configuring the log level for a given client *by name* is the most primary scenario, so we like this design.... 

**BUT** 

It would be really handy to be able to configure.... say, the log level of Polly across all of your logical clients. That would require the ability to write a logging filter like:
```
Microsoft.Net.Http.HttpClient.*.Polly
```

**Comment by pakrym** [comment]
Is supporting a single * enough or would you like to be able to have multiple wildcarding interior segments (e.g., `*.HttpClient.*.Polly`)?

I prefer supporting only a single wildcard because it would allow us to avoid writing complicated matching logic or using regexes.

**Comment by rynowak** [comment]
Yeah I think there's a real rabbit hole of complexity here if you try to support everything that could be imagined. The scenario that I care about is the one in the original post.

I'd also be OK with us closing this, no one has actually asked for this, I just thought it would be nice.
