### ISSUE TITLE
Wiring up logging in console app

### ISSUE THREAD

**Issue by andrasg** [aspnet/Logging#781]
I am trying to get logging wired up in a console app with the standard DI. Are there any examples how to do it the new dotnetcore2.0 way using `ILoggingBuilder` instead of `ILoggerFactory`?

I had success wiring up DI in Program.cs to mimic what's happening in aspnetcore:
```cs
            Startup startup = new Startup();

            var services = new ServiceCollection();

            serviceProvider = startup.ConfigureServices(services);

            startup.Configure(serviceProvider);
```
Followed by adding this to my `ConfigureServices()` in `Startup`:

```cs
            services.AddLogging(b => b
                .AddConfiguration(Configuration.GetSection("Logging"))
                .AddConsole()
                .AddDebug());
```
Any cleaner way to do this?

**Comment by muratg** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the `asp.net-core-<tag>` tag.
