### ISSUE TITLE
Some documentation examples do not match in LoggerExtensions

### ISSUE THREAD

**Issue by ChrisSimmons** [aspnet/Logging#791]
See [this](https://github.com/aspnet/Logging/blob/fb0103e6b7cc7987dbfc1cc91f7a20b14eaa4937/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs#L81), for example, where the example is for one of the other methods.

I will have a PR to follow shortly.

**Comment by muratg** [comment]
@pakrym PR: https://github.com/aspnet/Logging/pull/786
