### ISSUE TITLE
Test file logger behaviour on file collision

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Logging#794]
I noticed that if multiple tests end up with the same test name, the logs are overwritten. Since we need to manually create the test name for Theory tests, it's possible that we'll get it wrong. I think it's a good idea to log a warning in the global test log at least.

We could also explore adding a collision resolution. For example, create logs with new names like DuplicateTest.log, DuplicateTest.1.log, DuplicateTest.2.log ...

**Comment by JunTaoLuo** [comment]
cc @anurse

**Comment by muratg** [comment]
Parking in 2.2

**Comment by JunTaoLuo** [comment]
Ah I forgot I filed an issue for these improvements. I added the logic required for collision and long paths in https://github.com/aspnet/Logging/pull/795 so I'll mark this one as done.
