### ISSUE TITLE
Need ability to have console logger log to stderr

### ISSUE THREAD

**Issue by DotNetRockStar** [aspnet/Logging#796]
I am using a product that requires my logs to be console and logs that are errors to be logged to stderr.  Does the console logger let me configure it so that I can perform this
```
System.Console.Error.WriteLine(...);
```
Instead of always doing it this way
```
System.Console.WriteLine(...);
```
??

If not, is there any way to extend what is here to make that happen or do i need to roll my own ILoggingProvider?

Thanks in advance.

**Comment by muratg** [comment]
Dup of https://github.com/aspnet/Logging/issues/661
