### ISSUE TITLE
TestSink should be thread safe

### ISSUE THREAD

**Issue by halter73** [aspnet/Logging#797]
aspnet/KestrelHttpServer#2427

**Comment by Eilon** [comment]
Is that even possible? The API looks a bit weak to enable that:

https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Testing/TestSink.cs#L26-L28

We could add thread-safety guards to the *methods* that operate on the properties, but guarding the properties doesn't seem possible without a breaking change. So, even if we guard *one* way of doing writes, we can't guard all writes, and we can guard none of the reads.

**Comment by Eilon** [comment]
If what I said is right, an alternative would be to create a new set of thread-safe types (ThreadSafeTestSink, etc.), and design those from the ground up to be safe...

**Comment by halter73** [comment]
I was thinking we could expose the Scopes and Writes properties as ConcurrentQueues instead of Lists. Enumerating a ConcurrentQueue takes a snapshot so it's possible to see if something was logged previously while new logs are still being added. I agree that if we can't change the API, thread safety won't be possible.

**Comment by halter73** [comment]
@muratg @JunTaoLuo mentioned he's already looking into this, so I assigned it.

**Comment by JunTaoLuo** [comment]
I need to fix this after adding a TestSink to every LoggedTest by default. This blocks https://github.com/aspnet/KestrelHttpServer/issues/2390

**Comment by muratg** [comment]
@JunTaoLuo to be closed today? :)

**Comment by JunTaoLuo** [comment]
Yup. The PR is approved and preemptive reaction PRs have been merged. I just need to make sure I didn't break anything else in Universe.
