### ISSUE TITLE
Thread safety issue when creating loggers

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Logging#810]
I think there is a thread safety issue in LoggerFactory.CreateLoggers

https://travis-ci.org/aspnet/SignalR/jobs/367879272#L2081

```
  System.AggregateException: An error occurred while writing to logger(s). (Index was outside the bounds of the array.) ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
     at Microsoft.Extensions.Logging.LoggerFactory.CreateLoggers(String categoryName)
     at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
```

**Comment by benaadams** [comment]
Its under lock https://github.com/aspnet/Logging/blob/073a98266684d9c643a02ac3f0f30712a35a9914/src/Microsoft.Extensions.Logging/LoggerFactory.cs#L70-L82

However... `AddProviderRegistration` in `AddProvider` isn't https://github.com/aspnet/Logging/blob/073a98266684d9c643a02ac3f0f30712a35a9914/src/Microsoft.Extensions.Logging/LoggerFactory.cs#L85-L94

Which will change the size of the `_providerRegistrations` List

**Comment by muratg** [comment]
Ugh. @BrennanConroy can you take a look please?

**Comment by benaadams** [comment]
Fix is https://github.com/aspnet/Logging/pull/813

**Comment by muratg** [comment]
@davidfowl thoughts? You know the drill for RC1.
