### ISSUE TITLE
Introduce extension Method per LogLevel for IsEnabled

### ISSUE THREAD

**Issue by tomap** [aspnet/Logging#811]
Hi,

Could you introduce extension Method much like LogInformation, LogWarn, LogError for IsEnabled?
The name would be IsEnabledWarn (or IsWarnEnabled) and would just redirect to IsEnabled(LogLevel.Warn)

This already exists in Common.Logging:
https://github.com/net-commons/common-logging/blob/master/src/Common.Logging.Core/Logging/ILog.cs#L669

Same in log4net: 
https://git-wip-us.apache.org/repos/asf?p=logging-log4net.git;a=blob;f=src/Core/LogImpl.cs;h=9afed22637a49ea564cb327daebc130a3e224d4d;hb=HEAD#l1216
and nlog:
https://github.com/NLog/NLog/blob/19de4feb0a6f1292e9d0c69da5c75b73efda3ea1/src/NLog/Logger-generated.cs#L76

Please tell me if the concept is ok and the naming you prefer and I can create a PR :)

**Comment by pakrym** [comment]
We are not planning to add more logging extension methods at this moment.
