### ISSUE TITLE
Xunit logger throws when class is not taking ITestOutputHelper 

### ISSUE THREAD

**Issue by pakrym** [aspnet/Logging#819]
`StartTestLog` would always throw when we create `TestOutputHelper` and don't call `Initialize` on it.

https://github.com/aspnet/Logging/blob/a8115c9660357e7032e9c680e5459bf5299aadb6/src/Microsoft.Extensions.Logging.Testing/Xunit/LoggedTestInvoker.cs#L72-L85

**Comment by JunTaoLuo** [comment]
Initialization and uninitialization logic lives here: https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Testing/Xunit/LoggedTestInvoker.cs#L33-L51. I'm not sure why it's not working.

**Comment by JunTaoLuo** [comment]
I'll see if there's a more robust way of doing it.

**Comment by pakrym** [comment]
`StartTestLog` tries to log inline so initialization logic doesn't have a chance to run.
