### ISSUE TITLE
Memory leak in blob logger

### ISSUE THREAD

**Issue by pakrym** [aspnet/Logging#821]
Some customers observe a memory leak when using Azure Blob logging. 
Examining a memory dump showed lots of log messages stuck in the outgoing queue.
My current thinking is that writing loop somehow fails and stops consuming messages from queue.

Additionally, queue size limit is disabled by default causing the queue to grow indefinitely.

**Comment by yufeih** [comment]
@pakrym, we are also seeing this memory leak. Here is a dump screenshot:

![image](https://user-images.githubusercontent.com/511355/39561456-53f33b3a-4ed8-11e8-8833-3e6be280d25e.png)

![image](https://user-images.githubusercontent.com/511355/39561459-595ba33c-4ed8-11e8-8e44-d8e56b1249d1.png)

**Comment by jesong** [comment]
Any progress on this? we have to disable our logging on blob now.

**Comment by pakrym** [comment]
@muratg 2.1.3 candidate.

**Comment by muratg** [comment]
@pakrym What's the risk?

 If you'd like this in 2.1.5, could you fill out the shiproom template? Thanks.

**Comment by pakrym** [comment]
We don't have a fix. Risk is an application running out of memory and crashing.

**Comment by muratg** [comment]
Of course I mean the risk of the potential fix.

If we need to send it to the ship room, you'll need to have a PR with the fix.

**Comment by muratg** [comment]
(After talking to Pavel in person, punting this to 2.1.6)

**Comment by davidfowl** [comment]
cc @DamianEdwards

**Comment by DamianEdwards** [comment]
Let's get this fixed for 2.2.0 then consider for servicing in 2.1.6 please.

**Comment by muratg** [comment]
@pakrym could you fill out the shiproom template (in the PR #823) please?

**Comment by pakrym** [comment]
Shouldn't we fill a template when we have a fix?

**Comment by muratg** [comment]
My bad, yes we'll need a PR.

**Comment by davidfowl** [comment]
https://stackoverflow.com/questions/52405552/how-to-read-microsoft-logger-extension-high-memory-usage-from-dump

**Comment by DamianEdwards** [comment]
Is this being fixed yet folks?

**Comment by pakrym** [comment]
Currently, I'm trying to finish all ANCM shim work before it gets locked down.

**Comment by pakrym** [comment]
@yufeih can you please share your memory dump? How much are you logging per request? How many request per second were you getting when hitting this issue?

**Comment by muratg** [comment]
@pakrym Could you add the workaround here?

**Comment by pakrym** [comment]
From what I was able to gather in my investigations it looks like it's not a memory leak per se. Current thinking is that log write falls back because of the number of logs written and we don't cap log queue by default.

The workaround is to cap the queue size and uncap the batch size in ConfigureServices:

```
           serviceCollection.Configure<AzureBlobLoggerOptions>(options => {
                options.BackgroundQueueSize = 1000;
                options.BatchSize = null;
            });

            serviceCollection.Configure<AzureFileLoggerOptions>(options => {
                options.BackgroundQueueSize = 1000;
                options.BatchSize = null;
            });
```

**Comment by swatDong** [comment]
@pakrym - we tried the suggested configuration:
```
           serviceCollection.Configure<AzureBlobLoggerOptions>(options => {
                options.BackgroundQueueSize = 1000;
                options.BatchSize = null;
            });
```
Unfortunately another issue occurred - threads hang at adding message.

Here's the call stack from the memory dump - threads blocked at the same method
![image](https://user-images.githubusercontent.com/7642967/49566444-96b11180-f965-11e8-92c2-0a38bc0b5a48.png)

And also from the dump the queue is already full (count = 1000):
![image](https://user-images.githubusercontent.com/7642967/49566534-e1328e00-f965-11e8-9afd-2fdf47b3a3bb.png)

Any fix or workaround for this?
