### ISSUE TITLE
Unneeded LogValuesFormatter instanciation with null formatting values

### ISSUE THREAD

**Issue by fredericDelaporte** [aspnet/Logging#824]
When constructing a `FormattedLogValues` instance with a `null` `values` argument, a `LogValuesFormatter` is created.

This causes the `format` string to be parsed for formatting arguments, while this is not the case with a zero length `values`, resulting in a discrepancy in behavior when logging with an empty `values` argument (default case when no formatting arguments are supplied) and when logging with a `null` `values` argument (may happen in some corner cases).

This is due to following code:
https://github.com/aspnet/Logging/blob/db0ba840ab99f891aee42c9ad77d9f914af07b39/src/Microsoft.Extensions.Logging.Abstractions/Internal/FormattedLogValues.cs#L25-L28

As explained in this [comment](https://github.com/aspnet/Logging/commit/db0ba840ab99f891aee42c9ad77d9f914af07b39#r28824640), I do not think `values?.Length != 0` achieves the intended result.

If `values` are `null`, this condition will be true, because `null != 0` is `true` with .Net (and not unknown like with SQL, resolving to something falsy).
So this code ends up creating a formatter while there is nothing to format when `values` is `null`.

Shouldn't it be `values?.Length > 0`? This one would be `false` if `values` is null or has a `Length` equal to zero.

**Comment by muratg** [comment]
Related: #775
