### ISSUE TITLE
Logger<T> doesn't check if the created logger is null

### ISSUE THREAD

**Issue by paulomorgado** [aspnet/Logging#828]
https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/LoggerOfT.cs#L29

        public Logger(ILoggerFactory factory)
        {
            if (factory == null)
            {
                throw new ArgumentNullException(nameof(factory));
            }

            _logger = factory.CreateLogger(TypeNameHelper.GetTypeDisplayName(typeof(T)));
        }

Is this the intended behavior?

**Comment by pakrym** [comment]
Yes, `ILoggerFactory` is not supposed to return nulls
