### ISSUE TITLE
Logger provider to log exceptions to Windows Event Log

### ISSUE THREAD

**Issue by JesperTreetop** [aspnet/Logging#83]
ASP.NET 4 and older logs escaped exceptions to the Windows Event Log with the event ID 1309. Is a logger provider that logs this information in a similar way planned?

([I started issue 72 in Diagnostics](https://github.com/aspnet/Diagnostics/issues/72) because I thought this would be a middleware or at least a shorthand extension (something like `app.LogErrorsToWindowsEventLog();`) and was asked to bring this here instead.)

**Comment by davidfowl** [comment]
@JesperTreetop Where did you get with this?

**Comment by JesperTreetop** [comment]
Sorry, I got around to starting it but not to finishing it due to unexpected events. I'll see if I can get it to a state this weekend where it can at least be considered as a pull request or Gist for someone else to pick up - I know I don't have the cycles to drive this myself at this time and I understand you needing to start buttoning things up.

**Comment by davidfowl** [comment]
@JesperTreetop if you have something we can start from that would help as well.

**Comment by JesperTreetop** [comment]
Great, I'll get back with what I have.

**Comment by JesperTreetop** [comment]
Posted pull request #147 as per above - I don't believe it's perfect by any means, but it's something you can start from. I included a way to log extra details from the current HttpContext to be able to eventually match the extensive contextual logging of the current event log entry in ASP.NET 4 (but actually logging all that information is currently left as an exercise to the maintainer...).

**Comment by davidfowl** [comment]
Looking at this PR I'm thinking we should maybe have a separate EventLog class shared by our windows specific web servers to log unhanded exceptions. This really is Windows specific and if we end up having an event log provider, then it would be a generic component, instead of one tied to ASP.NET

**Comment by kichalla** [comment]
commit 9a6b53d75d6fbfcfbc1888d6badf1411f1a4b137
