### ISSUE TITLE
The implementation of LogValuesFormatter.Format will consume a data reader

### ISSUE THREAD

**Issue by dongbeifeng** [aspnet/Logging#830]
There is a problem in LogValuesFormatter.Format:

```c#
    // if the value implements IEnumerable, build a comma separated string.
    var enumerable = value as IEnumerable;
    if (enumerable != null)
    {
        values[i] = string.Join(", ", enumerable.Cast<object>().Select(o => o ?? NullValue));
    }
```
if the `value` is a data reader, it will be consumed by the Select method and return nothing when the program reads records from it after logging.

**Comment by pakrym** [comment]
Can you show your logging code, please? What are you intending to get logged when passing data reader to a .Log call?

**Comment by dongbeifeng** [comment]
The code comes from nhibernate example:

https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate.Example.Web/Infrastructure/NHibernateToMicrosoftLogger.cs

please look at line 30, it constructs a FormattedLogValues and the second can be a data reader. the data  will be eaten by the logger, nhibernate will fail to get data from it.

**Comment by pakrym** [comment]
Any data structure that doesn't support reenumeration or enumeration of which has side effect should not be passed as logging parameter.

**Comment by muratg** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
