### ISSUE TITLE
How to configure ConsoleLogger to IncludeScopes using appsettings.json?

### ISSUE THREAD

**Issue by tmds** [aspnet/Logging#835]
According to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.0&tabs=aspnetcore2x#log-scopes:

> Configuration of IncludeScopes using appsettings configuration files will be available with the release of ASP.NET Core 2.1.

I'm trying to get this to work with 2.1-rc1.
This is my appsettings.json with `dotnet new mvc`:
```json
{
  "Logging": {
    "IncludeScopes": true,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "Console":
  {
    "IncludeScopes": true
  }
}
```
I'm not sure where to add "IncludeScopes" so I put it in two places...

The logging doesn't include the scopes:
```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 6.8377ms 307 
```

**Comment by tmds** [comment]
ok, figured it out, Console is at the wrong level:
```
{
  "Logging": {
    "IncludeScopes": true,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    },
    "Console":
    {
      "IncludeScopes": true
    }
  }
}
```

Is there a `IncludeScopes` at the Logging level too? This seems to be so from the [doc](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.0&tabs=aspnetcore2x#log-scopes).

**Comment by pakrym** [comment]
Yes, IncludeScope setting was moved to Console logger level
