### ISSUE TITLE
Pass EventId by reference (in)

### ISSUE THREAD

**Issue by gfoidl** [aspnet/Logging#838]
https://github.com/aspnet/Logging/pull/829 made `EventId` a `readonly struct` so we could gain advantage by passing it by reference (`in`) instead of passing by value.

For instance
https://github.com/aspnet/Logging/blob/1094c068210ff28ff4ecfa4aecf01365497d5732/src/Microsoft.Extensions.Logging.Abstractions/ILogger.cs#L22
would need to be changed to 
```c#
void Log<TState>(LogLevel logLevel, in EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter);
```
but this is a breaking change (changes the call from "pass by value" to "pass by reference"). So changing to `in` may not be ideal.

For field-reads the compiler avoids creating a defensive copy too, but changing from property to field in `EventId` is also a breaking change.

Are there any other possibilities for avoiding the (unnecessary) struct-copies (besides improments in the JIT)?

**Comment by muratg** [comment]
@pakrym thoughts on this?

This is obviously a breaking change, so if we ever do this, it would be a major release.

**Comment by pakrym** [comment]
EventId is not a large struct so I'm not to keen to use `in` here.

**Comment by pakrym** [comment]
If anything state should be the one passed using `in` as it might be a large struct. EventId is not worth a breaking change.
