### ISSUE TITLE
Allow to specify the Culture used in log-values

### ISSUE THREAD

**Issue by gfoidl** [aspnet/Logging#842]
The culture is fixed to the invariant culture. I'd like to configure the culture used in https://github.com/aspnet/Logging/blob/adac42c183a525813ea9759717620bb0aad14fb3/src/Microsoft.Extensions.Logging.Abstractions/Internal/LogValuesFormatter.cs#L145
Default should remain invariant, but via config a different culture should be allowed.

For Europeans like me especially date-formats are odd, and like today (06/01/2018) I'll get easily trapped by 6th Jan 2018 :wink:

Should we go for this or are there any reasons to stick to invariant culture?

**Comment by muratg** [comment]
Thanks for the report, @gfoidl. 

@davidfowl was there any good (or historical) reason why this wasn't configurable? Or is it just a miss?

**Comment by muratg** [comment]
We don't see a good way to achieve this at the abstraction level. One option would be using a sink that supports Culture.
