### ISSUE TITLE
Abbreviation in GetLogLevelString()

### ISSUE THREAD

**Issue by gqqnbig** [aspnet/Logging#843]
In [ConsoleLogger.GetLogLevelString()](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs#L205), level Trace outputs as trce, missing letter a; level debug outputs as dbug, missing letter e, etc. 

Why does it need to use abbreviation? At the first time I saw the log output, I thought it's a typo.

I blame the file and found the code was submitted in 9e6e1674523649430dfe07bbbb74592c1c009b87, changing fully-spelled word to the current abbreviation form, but didn't give explanation.

If alignment is needed, we can use spaces. The current "dbug", "trce" look awkward, like a typo, and contrast to .NET framework's naming convention of not using abbreviation. (though I understand .NET framework's naming convention only applies to identifiers in the code)

**Comment by muratg** [comment]
The main reason was alignment, I believe. I don't expect we would change this after 3 years though. Spaces could work, but some folks' would likely get broken if we make a change like this at this point. 

Is your main concern that it looks like a typo?

**Comment by gqqnbig** [comment]
Somewhat yes. When I was trying this library, I only use `log.debug(...),` and it outputs  "dbug". I didn't realize the omission is for alignment until I use other log levels. If the method name is `log.dbug()`, it outputing "dbug" will not supprise me so much.

Is there a possibility to change GetLogLevelString() to protected method? This way supports customization and localization.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
