### ISSUE TITLE
Consider making EventSourceLogger public

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Logging#846]
It's unfortunate that I can't do this 😢 
```csharp
loggingBuilder.AddFilter<EventSourceLogger>("Default", LogLevel.Warning);
```

**Comment by muratg** [comment]
Let's consider this in 3.0.0.

**Comment by pakrym** [comment]
Is there any point in changing `EventSourceLogger` level in app code? In ETW listener controls filters/levels it wants to be applied.

**Comment by shirhatti** [comment]
Well I filed this issue before you changed the EventSourceLogger. Agree that it probably doesn't make any sense now 😄
