### ISSUE TITLE
Assembly File Load Exception with SampleApp

### ISSUE THREAD

**Issue by kscott5** [aspnet/Logging#86]
```
Dev_Env (x86) F:\apps\web\aspnet\Logging\samples\SampleApp>k run
System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Threading, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Framework.Logging.LoggerFactory.Create(String name)
   at SampleApp.Program..ctor()
```

**Comment by kscott5** [comment]
That is the difference between the release and master branch?

**Comment by Praburaj** [comment]
This contains some inforamtion on these branches : https://github.com/aspnet/Home/wiki/Engineering-guidelines#branch-strategy

**Comment by kscott5** [comment]
I appreciate the help with this. I removed the contains in the following directories (OK):
@powershell remove-item %USERPROFILE%\.kre -recurse -force
@powershell remove-item %USERPROFILE%\.kpm -recurse -force

I executed the following commands (OK):

git clone https://github.com/aspnet/kvm.git --branch master
git clone https://github.com/aspnet/Home.git --branch master
git clone https://github.com/aspnet/Logging.git --branch master

Executed the following commands to pull the KRE (OK):

kvm install latest -x86 -r CoreCLR -f 
kvm install latest -x86 -r CLR -f

Execute the following commands from Logging\samples\SampeApp (OK):

kpm restore --no-cache
k run

While my original issue is fixed, pull all code from master branches breaks the Home\sample\HelloMvc and Home\sample\HelloWeb samples with the following errors:


But now there are conflicts with other samples particularly Home\samples.
Executed the following commands from Home\samples\HelloMvc (Restore Complete: NOT OK)

kpm restore --no-cache

Unable to locate Newtonsoft.Json >= 6.0.6
Unable to locate System.Collections.Immutable >= 1.1.32-beta
Unable to locate System.Reflection.Metadata >= 1.0.17-beta
Restore complete, 5310ms elapsed

Which appear to be depends of 

Microsoft.AspNet.Hosting
Microsoft.AspNet.Mvc
Microsoft.AspNet.Mvc.Core
and many more.

**Comment by Praburaj** [comment]
The below error is possibly because your default nuget feed is disabled for some reason. Open VS -> Tools -> Options -> Nuget sources -> Enable your https://www.nuget.org/api/v2 feed and do a `kpm restore` again. 

```
Unable to locate Newtonsoft.Json >= 6.0.6
Unable to locate System.Collections.Immutable >= 1.1.32-beta
Unable to locate System.Reflection.Metadata >= 1.0.17-beta
```

**Comment by kscott5** [comment]
I pull the release branch, execute the kpm restore, then master branch and all works.

But I'm not using VS. Could this be set within Nuget.config?

**Comment by Praburaj** [comment]
Yes you could set that in the `Nuget.config`. Open `%appdata%\NuGet\NuGet.Config` and see if your default nuget feed is under `<disabledPakageSources>` node. move it in to `<packageSources>` node.

**Comment by kscott5** [comment]
After having further issues, I decided to scratch the whole thing and start over. So, tell me what are the correct steps to getting KRE update and running. Should I pull from dev or master branches? Can you mix dev and master?

```DOS
Dev_Env (x86) G:\apps>kvm install latest -x86 -r CoreCLR
Determining latest version
Console-Write-Error : Exception calling "DownloadString" with "1" argument(s):
"The remote server returned an error: (403) Forbidden."
At G:\apps\aspnet\kvm\src\kvm.ps1:827 char:22
+   Console-Write-Error <<<<  $_
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,Console-Write-Error
```

Note: I have windows 7 pro with .net 3.

**Comment by Praburaj** [comment]
`master` corresponds to `beta1`. `dev` corresponds to `rc1` (a future release). You can choose any of these, but just make sure that you have all binaries, kre etc are from the same corresponding branch. You cannot mix branches. 

Where did you install `kvm` from? Is your kvm pointing to master feed or dev feed?

**Comment by kscott5** [comment]
I tried both but the binaries could have gotten mixed. I will try dev branch and see what happens
