### ISSUE TITLE
Consider making GetLogLevelString() protected

### ISSUE THREAD

**Issue by hishamco** [aspnet/Logging#861]
As I has seen [here](https://github.com/aspnet/Logging/blob/d9b34d1c36fde204bd736d09b89b86451bd82e95/src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs#L205) there's no to override the logic of the `GetLogLevelString()`, if someone ask why we need this? a simple case localizing the entire log message

**Comment by muratg** [comment]
We won't be doing this. Thanks for the suggestion.
