### ISSUE TITLE
Wrong property comment/description in AzureFileLoggerOptions

### ISSUE THREAD

**Issue by lmcarreiro** [aspnet/Logging#863]
Property `FileName` has the same description/comment as property `RetainedFileCountLimit`:

https://github.com/aspnet/Logging/blob/master/src/Microsoft.Extensions.Logging.AzureAppServices/AzureFileLoggerOptions.cs

**Comment by Eilon** [comment]
Good find! This issue is up-for-grabs in case anyone would like to send a PR. This is a pretty easy one to get started with!
