### ISSUE TITLE
Microsoft.Extensions.Logging.EventLog 2.1.1 Not Logging in IIS 8.5

### ISSUE THREAD

**Issue by AmerjitSingh** [aspnet/Logging#864]
I am using EventLog nuget package 2.1.1 on Asp.net Core 2.1(Full Framework) on Windows 2012 Standard.
Have created WebSite in IIS 8.5 using standard AppPool Identity, have set code to the following.
```c# 
           WebHost.CreateDefaultBuilder(args)
                .CaptureStartupErrors(true)
                .UseSetting(WebHostDefaults.DetailedErrorsKey, "true")
                .UseStartup<Startup>()
                .ConfigureLogging(logging => logging.SetMinimumLevel(LogLevel.Information));`

and 
`            loggerFactory.AddEventLog(new EventLogSettings
            {
                SourceName = "Source",
                LogName = "App Service Logs"
            });
```
when I use ILogger to **any** LogLevel, there is **no output** with SourceName "Source" but LogName exists. Have given AppPool Identity permission in the EventLog registry settings.

**Comment by muratg** [comment]
@AmerjitSingh are you still having issues? If so, could you share an app that reproduces the issue?

**Comment by pakrym** [comment]
Closing. Please reopen if more information is available.
