### ISSUE TITLE
Virus alert on macOS

### ISSUE THREAD

**Issue by ahmelsayed** [aspnet/Logging#865]
_From @jon-shipley on August 17, 2018 12:19_

Installing on macOS results in a Virus alert:

```
 > node --version
v10.8.0
 > npm i -g azure-functions-core-tools@core --unsafe-perm true
attempting to GET "https://functionscdn.azureedge.net/public/2.0.1-beta.35/Azure.Functions.Cli.osx-x64.2.0.1-beta.35.zip"
[==================] Downloading Azure Functions Cli
+ azure-functions-core-tools@2.0.1-beta.35
updated 1 package in 23.892s
 > 
```

This results in Intego VirusBarrier 10.9.15 in detecting the "W32/Generic" Virus in `Microsoft.Extensions.Logging.dll` which is unexpected.

![screen shot 2018-08-17 at 13 16 15](https://user-images.githubusercontent.com/13945069/44265831-26e51280-a220-11e8-96e1-7e8dafee0237.png)

Any advice appreciated.

_Copied from original issue: Azure/azure-functions-core-tools#633_

**Comment by jon-shipley** [comment]
Thanks @ahmelsayed 

I've submitted the file to Intego.  Hopefully, they can confirm it as a false positive and update their product.

**Comment by Eilon** [comment]
All the signed binaries produced here are virus scanned already, so this is most likely a false positive (assuming the Microsoft Authenticode signature is still valid). Reporting this to the author of the virus scanner is the only action to take. Closing this issue in the meantime.

**Comment by Eilon** [comment]
Thanks for the update!
