### ISSUE TITLE
Commenting out log statements impacting later log statements

### ISSUE THREAD

**Issue by johnkors** [aspnet/Logging#868]
Hi,

Related to [this issue](https://github.com/RetireNet/dotnet-retire/issues/18) — is there any coupling between log statements that could lead to this behaviour?

Commenting out one log statement causes later log statements to dissapear.

![kapture 2018-08-19 at 22 09 01](https://user-images.githubusercontent.com/206726/44312773-a3811800-a3fd-11e8-9179-2ce32e341b7b.gif)

**Comment by Eilon** [comment]
That is... quite odd! Can you attach a debugger and see what's going on? Or add regular `Console.WriteLine(...)` calls?

**Comment by johnkors** [comment]
Hi @Eilon , the project is open source at https://github.com/retirenet/dotnet-retire . If you `dotnet run` the `dotnet-retire` project, you can see this behaviour. 

Adding `Console.WriteLine`s in that method writes all instances of Writeline wherever I put them.

**Comment by Eilon** [comment]
Maybe an issue with flushing in the console logger because it queues up writes? @pakrym could that be possible?

**Comment by johnkors** [comment]
Funny. I added a `Thread.Sleep(1000)` at the end of the method, and now it logs. 

![image](https://user-images.githubusercontent.com/206726/44444396-e6e5ad00-a5dc-11e8-9ac7-a7d53e719ad4.png)

**Comment by davidfowl** [comment]
Yep

**Comment by johnkors** [comment]
Ah, perfect. Disposing the DI container fixed that and other issues I had with the logger.

Fix:
```
(services as IDisposible)?.Dispose();
```

**Comment by davidfowl** [comment]
You don't need to cast.

**Comment by johnkors** [comment]
Ah, I was using `IServiceProvider`, not `ServiceProvider`. Thanks.

**Comment by johnkors** [comment]
Closing as this is a dup of #631
