### ISSUE TITLE
LogLevel

### ISSUE THREAD

**Issue by kscott5** [aspnet/Logging#87]
Please correct me but isn't LogLevel an internal enum of the System namespace. There seems to be mismatch between what's in master branch and what's been displayed on Logging/samples/SampleApp/Program.cs

**Comment by Praburaj** [comment]
No. This `LogLevel` is defined in https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging.Interfaces/LogLevel.cs.

**Comment by kscott5** [comment]
Great. But you had me pull from the master branch which is using TraceType.cs

**Comment by Praburaj** [comment]
Yeah looks like `TraceType` got renamed to `LogLevel`.
