### ISSUE TITLE
LoggerInformation should call into ILogger.IsEnabled

### ISSUE THREAD

**Issue by pakrym** [aspnet/Logging#871]
So logger like EventSourceLogger can provide additional filtering.

**Comment by Eilon** [comment]
Any perf concerns here? I don't recall any specifics here, but I recall in general that a lot of the logger stuff was written in a particular way due to perf. But maybe not this.

**Comment by pakrym** [comment]
We would only call into the child logger if all other filters are satisfied. This doesn't regress filtering-out case and even improves perf when logger has a stricter internal filter.

**Comment by pakrym** [comment]
Checked this again, we call `logger.IsEnabled` later down the line.
