### ISSUE TITLE
How to configure custom EventLog Name and Source using appsettings.json?

### ISSUE THREAD

**Issue by Madison-Smith** [aspnet/Logging#873]
It seems that by default, the created logger object writes to the Application log using the Application event source. I've created a new Event Log that I want all my event to be written to instead so events are easier to find and I can have a longer audit trail history by not having the Application log rotate when it gets full from events from other sources. 

How can I do this using appsettings.json as opposed to using the overloaded method (ILoggingBuilder.AddEventLog(EventLogSettings)?
In Program.cs I have:
```csharp
logging.AddEventLog(); 
logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
```
It'd be nice to be able to do this in appsettings.json (perhaps you can and I'm using the wrong keys here but I can't find a reference on how these map to the Logger objects):
```json
  "Logging": {
    "Log": "myLog",
    "Source": "Account Management Portal",
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning",
      "myLog": "Critical"
    }
  }
```
I can do this by using the overload for .AddEventLog(EventLogSettings) like so: 
```csharp
logging.AddEventLog(new EventLogSettings() { LogName = "myLog", SourceName = "mySource" });
```
but the disadvantage of course is configuration flexibility across environments.

**Comment by muratg** [comment]
We are not currently supporting this.

**Comment by FeodorFitsner** [comment]
Provided you have the following `appsettings.json`:

```json
{
    "Redis": {
      "ConnectionString": "localhost"
    }
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information"
    },
    "EventLog": {
      "LogName": "MyLogName",
      "SourceName": "My App"
    }
  }
}
```

You can configure EventLog logger like this:

```csharp
...
.ConfigureLogging((hostingContext, logging) =>
{
	logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
	logging.AddConsole();
	logging.AddEventLog(hostingContext.Configuration.GetSection("Logging:EventLog").Get<EventLogSettings>());
})
...
```

Hope that helps.
