### ISSUE TITLE
Configuration is reloaded twice on change

### ISSUE THREAD

**Issue by adams85** [aspnet/Logging#874]
**Is this a Bug or Feature request?:**

Bug

**Description of the problem:**

After changing the logger provider configuration, the event handler callback registered using `IOptionsMonitor<T>.OnChange()` fires two times. According to my tests the framework actually reloads the configuration data twice.

**Steps to reproduce the problem:**

appsettings.json

```
{
  "Console": {
    "IncludeScopes": false
  }
}
```

Program.cs

```
using System;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Console;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;

namespace loggertest
{
    class Program
    {
        static void Main(string[] args)
        {
            var config = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .Build();

            var services = new ServiceCollection();
            services.AddLogging(b =>
            {
                b.AddConfiguration(config);
                b.AddConsole();
            });

            using (var sp = services.BuildServiceProvider())
            {
                var options = sp.GetRequiredService<IOptionsMonitor<ConsoleLoggerOptions>>();
                options.OnChange((o, name) => Console.WriteLine($"Name = {name}, Hash = {o.GetHashCode()}, Content = {JsonConvert.SerializeObject(o)}"));
            }

            Console.ReadLine();
        }
    }
}
```

Run the program, edit the contents of the settings json file and save it.

**Additional notes:**

The problem doesn't occur when I manually configure the options:

```
services.AddLogging(b =>
{
    b.AddConsole();
    b.Services.Configure<ConsoleLoggerOptions>(config);
});
```

The problem is not specific to file system watchers or `PhysicalFileProvider`. The memory implementation of `IFileProvider` used in my tests produces the same effect.

The issue seems to be related to the following commit:
https://github.com/aspnet/Logging/commit/cc350d7ef616ef292c1b4ae7130b8c2b45fc1164

**Version:**

Microsoft.Extensions.Logging 2.1.0+

**Comment by pakrym** [comment]
I looked into this, two events are caused by how ConfigurationBuilder handles adding two sections from the same original configuration object.

We add both a section with loggers full type name and an alias to configuration builder [here](https://github.com/aspnet/Logging/blob/d5686ecc8b342ae2b24f09463fd9a3a23d31af31/src/Microsoft.Extensions.Logging.Configuration/LoggerProviderConfigurationFactory.cs#L27-L41) and when event fires for original IConfiguration it causes a reload per each section. /cc @HaoK 

There is not much we can do here from logging perspective.
