### ISSUE TITLE
Logging should get IExternalScopeProvider from DI?

### ISSUE THREAD

**Issue by benaadams** [aspnet/Logging#875]
So you can register something like the following to disable scopes entirely
```csharp
public class LoggerScopeProvider : IExternalScopeProvider
{
    private readonly static IDisposable _disposable = new Scope();

    public void ForEachScope<TState>(Action<object, TState> callback, TState state)
    { }

    public IDisposable Push(object state) => _disposable;

    private class Scope : IDisposable
    {
        public void Dispose()
        { }
    }
}
```

Rather than have it strongly typed
https://github.com/aspnet/Logging/blob/d9b34d1c36fde204bd736d09b89b86451bd82e95/src/Microsoft.Extensions.Logging/LoggerFactory.cs#L23

And initalized to that type
https://github.com/aspnet/Logging/blob/d9b34d1c36fde204bd736d09b89b86451bd82e95/src/Microsoft.Extensions.Logging/LoggerFactory.cs#L120-L125

Related "Logging infrastructure impact performance" https://github.com/aspnet/Logging/issues/827

/cc @pakrym @davidfowl

**Comment by benaadams** [comment]
It defines all the methods `LoggerExternalScopeProvider` has; you use it instead of `new`ing `LoggerExternalScopeProvider`?

**Comment by pakrym** [comment]
What if we just add EnableScopes flag to LoggerFactory options?

**Comment by benaadams** [comment]
That would probably work; or DisableScopes depending on what the default state should be?

(I assume EnableScopes as they are normally switched off in the templates?)

**Comment by muratg** [comment]
Related #827

**Comment by pakrym** [comment]
Closing because `CaptureScopes` flag was added.

**Comment by pakrym** [comment]
> Am I understanding that correctly? If so, do we even need to be calling Push() in our loggers?

No, if you implement `ISupportExternalScope` you don't need to call `.Push()`
