### ISSUE TITLE
Support for Application Insights without ASP.NET Core

### ISSUE THREAD

**Issue by ChristopherHaws** [aspnet/Logging#876]
In https://github.com/aspnet/Logging/issues/463 it is mentioned that there is an implementation of `ApplicationInsightsLoggerProvider` that lives [here](https://github.com/Microsoft/ApplicationInsights-aspnetcore/tree/17cc5de23ba58872650f7f2c4eaf0f0f2e47a823/src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation). This is great if the app is running on ASP.NET Core, but this doesn't take into account other types of apps such as ASP.NET 4 websites or Windows Services.

From what I can see, this code is not dependent on ASP.NET Core. Is there a chance that this logger could be moved to this repo as `Microsoft.Extensions.Logging.ApplicationInsights`? Is there a good reason this hasn't been done already?

Thanks!

**Comment by davidfowl** [comment]
This issue should be moved to that repository.

**Comment by ChristopherHaws** [comment]
Ok. Moved to https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/749

Thanks!
