### ISSUE TITLE
Add overloads to `Log*` in `LoggerExtensions`

### ISSUE THREAD

**Issue by daniel-white** [aspnet/Logging#878]
It would be great if there were additional extension methods in `LoggerExtensions` that would avoid allocating the `object[]` when the log level is not turned up. `String.Format` has overloads that takes up to 3 additional arguments that don't require a `object[]` to be allocated.

**Comment by muratg** [comment]
We don't plan to add more extensions. And you're correct about that - `LoggerMessage.Define`.
