### ISSUE TITLE
Obsolete/remove old style logging APIs

### ISSUE THREAD

**Issue by pakrym** [aspnet/Logging#879]
When logging moved to DI a lot of filtering/options APIs got duplicated to keep backwards compatibility. We need to either obsolete or remove them in 3.0.

Should we obsolete them in 2.2?

@davidfowl

**Comment by Eilon** [comment]
Do we think all users should use only the newer set of APIs? Is there anything that the old APIs did but there is no good alternative in the new APIs?

**Comment by pakrym** [comment]
The feature set is exactly the same the only additional thing old APIs did is work without DI container.

**Comment by Eilon** [comment]
And it is important that no one use them? Or are there still scenarios where those are important?

**Comment by pakrym** [comment]
>And it is important that no one use them?

Not exactly. It would allow us to clean up a lot of duplicated logic. And make it easier to make future improvements without requiring two ways of doing the same thing.

>Or are there still scenarios where those are important

I don't know of any, if there are we should fix`ILoggerBuilder` to support them.
