### ISSUE TITLE
Allow mapping of log levels in logging configuration

### ISSUE THREAD

**Issue by marcin-chwedczuk-meow** [aspnet/Logging#880]
I keep track of all errors from all micro-services in tools like Kibana. I had defined queries and dashboards that show me various metrics including logged error statements. Unfortunately some libraries that I use e.g. IdentityServer4 log e.g. failed logging attempts as errors. For me this makes no sense and I think that they should be logged instead as warnings. Currently I have no option to override log level in my logging configuration, I can only turn a particular logger on or off (which for security reasons I do not want).

It would be nice to have an option to redirect log levels from certain loggers to different log levels e.g. to make an error logged by IdentityServer4.Endpoints.AuthorizeEndpoint logger to appear as Info in log output.
```
{
  "Logging": {
    "Console": {
      "IncludeScopes": false,
      "LogLevel": {
        "Microsoft.AspNetCore.Mvc.Razor.Internal": "Warning",
        "Microsoft.AspNetCore.Mvc.Razor.Razor": "Debug",
        "Microsoft.AspNetCore.Mvc.Razor": "Error",
        "Default": "Information"
      },
	  
	  // Proposed syntax
	  "MapLogLevels": {
		"IdentityServer4.Endpoints.AuthorizeEndpoint": {
			// All log statements with level Error will be logged with level  Debug
			"Error": "Information",
		}
	  }
    }
  }
}
```

UPDATE: Actually something like NLog filtering can also solve my problem: https://github.com/NLog/NLog/wiki/Filtering-log-messages.

**Comment by muratg** [comment]
:+1:
