### ISSUE TITLE
Logger.BeginScope with IncludeScopes = false gets performance hit

### ISSUE THREAD

**Issue by snakefoot** [aspnet/Logging#894]
Normally one can have very fast logging when registering a single LoggerProvider with IncludeScopes = false, where BeginScope returns a NullScope.

Now because of #723 then extra allocation occurs because the following optimization was removed:

```
if (loggers.Length == 1)
    return loggers[0].Logger.BeginScope(state);
```

If the LoggerProvider attempts to implement ISupportExternalScope (And has IncludeScopes = false), then the LoggerFactory will generate even more garbage-allocation because it forces creation of AsyncLocal-state that must be transferred when using async-threading-tasks.

Again if the above optimization was used, then one could skip the external-scope-provider-logic when only a single LoggerProvider (IncludeScopes = false would continue to work).

See also #714

**Comment by davidfowl** [comment]
#714 is valid but those profiles are extremely old. If you have performance numbers showing a sizable performance difference then it would be great. There have been a large number of optimizations since then and I actually suspect it isn't a big problem anymore.

**Comment by davidfowl** [comment]
Can you share your profile? What tool are you using and what async locals are you looking at? We’d want to add this to our performance test suite.

**Comment by snakefoot** [comment]
Not using any special tools. Just net472 and `AppDomain.CurrentDomain.MonitoringTotalAllocatedMemorySize`.

Then just output the delta after completed test-exercise. I used the TestLoggerProvider in this issue to perform the test.

```
    public class FooExtLog
    {
        private readonly ILogger<FooExtLog> _logger;
        private static readonly Action<ILogger, int, int, Exception> _messageDefine =
            LoggerMessage.Define<int, int>(Microsoft.Extensions.Logging.LogLevel.Information, default(EventId), "Log message {number} / {total}");

        public FooExtLog(ILogger<FooExtLog> logger)
        {
            _logger = logger;
        }

        public void Bar(int index, int totalCount)
        {
            using (_logger.BeginScope("Hello {World}", "Earth"))
            {
                _messageDefine(_logger, index, totalCount, null);
            }
        }
    }
```

```
for (var i = 0; i < logEventCount; i++)
   foo.Bar(i, logEventCount);
```
