### ISSUE TITLE
FormatException at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)

### ISSUE THREAD

**Issue by huorswords** [aspnet/Logging#907]
**Note**: Opened originally on [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore](https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/issues/52) by @miaodadao. Kudos for him.

When the end user passes to the `LogInformation()` method a format string as follows:

```csharp
ILogger logger = null;
// Initialize the logger through the loggerFactory.
logger.LogInformation("{0}{0}", "OK"); // Exception is thrown
```

The logging system returns a `FormatException`, within the message: 

    Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

The next unit test snippet can be included on Microsoft.Extensions.Logging.Test.LoggerTest class to test the behavior:

```csharp
[Fact]
public void TestFormatBug()
{ 
	// Arrange
	var store = new List<string>();
	var loggerFactory = new LoggerFactory();
	var logger = loggerFactory.CreateLogger("Test");

	loggerFactory.AddProvider(new CustomLoggerProvider("provider1", ThrowExceptionAt.None, store));

	// Act
	var text = string.Format("{0}{0}", "OK"); // text is "OKOK"
	logger.LogInformation("{0}{0}", "OK"); // Unexpected exception at this point
	Assert.True(false);
}
```

Can you please clarify it this behavior can be considered as-designed?

**Comment by pakrym** [comment]
Yes, it is by design.

Logging message format uses named format specifiers and doesn't support repeating same format specifier multiple times.

**Comment by huorswords** [comment]
@pakrym good to know.

Thank you by your answer.
