### ISSUE TITLE
Class name can be beautified when generic class in Console logger

### ISSUE THREAD

**Issue by suhasj** [aspnet/Logging#91]
When the Console logger is hooked into the application, the logs are of the format [classname] [log level] and so on. The class is the fully qualified class name and looks good for normal class. When the class is a generic type, it prints it with a tilde and the closed type `T` is printed with full assembly information. This makes it hard to read on the console and does not look good. It would be good if that can be cleaned up

Example 

![error](https://cloud.githubusercontent.com/assets/1919946/5727081/41c26cc6-9b15-11e4-8138-76053faa2068.png)

In the above image, if you look at the SigninManager, the closed type `T` which is the ApplicationUser is displayed along with assembly information which is not needed

**Comment by Eilon** [comment]
I think I pointed @NTaylorMullen a while ago to some ancient code I write that prints beautified generic type names. Taylor, do you have that around somewhere?

**Comment by NTaylorMullen** [comment]
Forwarded :smile:

**Comment by suhasj** [comment]
Thanks :)

**Comment by kichalla** [comment]
Looks like this is already fixed?

![image](https://cloud.githubusercontent.com/assets/6559784/7756767/3e1902f4-ffb2-11e4-9644-de75a6d3ca99.png)

@muratg

**Comment by suhasj** [comment]
sure it was fixed by this https://github.com/aspnet/Logging/pull/105 
This can be closed

**Comment by Eilon** [comment]
Yup.
