### ISSUE TITLE
LoggedTest and its siblings should have a consistent default log level

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Logging#918]
It's set to:
Information: https://github.com/aspnet/Logging/blob/master/src/Microsoft.Extensions.Logging.Testing/LoggedTest/LoggedTestBase.cs#L41
Trace: https://github.com/aspnet/Logging/blob/master/src/Microsoft.Extensions.Logging.Testing/LoggedTest/LoggedTestBase.cs#L68
Debug: https://github.com/aspnet/Logging/blob/master/src/Microsoft.Extensions.Logging.Testing/AssemblyTestLog.cs#L61

We should just make these consistent and set the default to Debug everywhere.

**Comment by BrennanConroy** [comment]
Done
