### ISSUE TITLE
regression: recent API changes have broken scenarios that do not use logging directly

### ISSUE THREAD

**Issue by borgdylan** [aspnet/Logging#93]
I have an app that does not use the logging APIs directly. A recent change has removed a function forcing the static files middleware to stop working.

```
Missing method Microsoft.Framework.Logging.LoggerExtensions::WriteWarning(ILogger,string,string[]) in assembly /home/dylan/.kpm/packages/Microsoft.Framework.Logging/1.0.0-rc1-10713/lib/aspnet50/Microsoft.Framework.Logging.dll, referenced in assembly /home/dylan/.kpm/packages/Microsoft.AspNet.StaticFiles/1.0.0-rc1-11087/lib/aspnet50/Microsoft.AspNet.StaticFiles.dll
```

**Comment by davidfowl** [comment]
Delete all of your packages and try restoring again. Everything is now beta 3 so you're likely mismatched

**Comment by davidfowl** [comment]
Same for the KRE

**Comment by borgdylan** [comment]
That fixed it, however i found a missing thing in static files...will report
