### ISSUE TITLE
Have a Write overload that takes an expression and is executed conditionally

### ISSUE THREAD

**Issue by suhasj** [aspnet/Logging#97]
The current methods and overloads take string or an object with LogFormatter along with state. We can have a method that takes an expression which logs or creates a log object and is invoked only if the LogLevel is enabled. This makes it efficient in a sense that we don't need to have an additional check before calling the logger.Write method

**Comment by Eilon** [comment]
Be aware that allocating a delegate isn't free either.

**Comment by suhasj** [comment]
I debugged this and the `Func<object, Exception, string> formatter` parameter in the `Write` method already does this. A caveat is that it is not async. Making it async along with having a WriteAsync would be really helpful

**Comment by glennc** [comment]
Does this achieve the same thing as https://github.com/aspnet/Logging/issues/100?
