### ISSUE TITLE
Dispose IDisposable ILogger or dispose IDisposable ILoggerProvider

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/Logging#99]
I am implementing a custom Logger and I am facing to a IDisposable problem.

My loggerProvider own an IDisposable object (a BlockingCollection). 
I am unable to dispose this object because the LoggerFactory does not try to dispose the ILoggerProviders.
The LoggerFactory should be able to register the provider when it is added and to dispose it at its own Dispose().

**Comment by Eilon** [comment]
Curious - I think in general loggers would at best be disposed when the app shuts down, right? So at that point, what would calling `Dispose()` really help? The app is exiting, so the OS will clean up anything that needs to be cleaned up.

And of course during an unexpected shutdown (i.e. a crash) the `Dispose()` wouldn't get called anyway.

Any thoughts on this?

**Comment by ycrumeyrolle** [comment]
My main concern is that without the IDisposable pattern, I am not sure that my logger logs all my messages. 
An example would be with the DiagnosticsLogger. If I use a TextWriterTraceListener with AutoFlush=Off, I can lost some information at the daily app pool recycling. 
With a IDisposable pattern, I will be able to a call the traceSource.Flush() at the App_End().

**Comment by ycrumeyrolle** [comment]
IMHO the IDisposable pattern should be supported for the ILoggerProvider, not for the ILogger because of ILoggerProvider lifecycle is managed by the Logging framework, ILogger lifecycle is manager by the application.

**Comment by Eilon** [comment]
Ah, I see, this makes more sense now.

**Comment by sandorfr** [comment]
I have the same need/issue building a Azure table based logger. To get proper performance I want logging to happen asynchronously and using batches. But to ensure that everything is logged I need some mechanism to ensure that everything has been flushed.

**Comment by lodejard** [comment]
+1

**Comment by wenhx** [comment]
If LoggerFactory implemente IDisposable interface, it means that if we don't dispose it may be problematic,but in most situations we don't need to dispose LoggerProvider.
So, if someone need dispose LoggerProvider, he can create a custom LoggerFactory.

**Comment by kichalla** [comment]
commit b65fc9692043a3204662b5f4794c0930f499078e
